### ISSUE TITLE
Abstraction layer for attestations

### ISSUE THREAD

**Issue by hhalpin** [w3c/webauthn#1]
We are looking for the correct way to define an abstraction for attestations so that we don't have to go to operating-system particular (i.e. Android) discussions in the W3C spec.

**Comment by rlin1** [comment]
At this time, the attestationStatement is intended to provide such an abstraction.

However, since some existing components already have implemented a very specific encoding of attestation data, such "binary" data needs to be included in such abstraction layer. 
This is done in theattestationStatement.core.rawData field.

At this time, the spec also includes the details of the different rawData variants (aka attestation types).

**Comment by rlin1** [comment]
Some attestation types are vendor specific (i.e. proprietary).  Others are either referring to external alliances (such as tcg or FIDO).

**Comment by leshi** [comment]
Discussed in https://www.w3.org/2016/04/06-webauthn-minutes.html

**Comment by rlin1** [comment]
see discussion in http://www.w3.org/2016/04/06-webauthn-minutes.html
summary:
- structure of attestation and signature MUST remain normatively specified
- we just want to move the details to a different place.
