### ISSUE TITLE
Section 4.3: add reference to privacy

### ISSUE THREAD

**Issue by rlin1** [w3c/webauthn#100]
We already mention that in section 4.3.4.1. but it is important to already be mentioned in the into

**Comment by equalsJeffH** [comment]
at the time @rlin1 submitted this issue, S 4.3.4.1 mapped to this spot in the spec source (index.src.html): `{#sec-attestation-privacy}`.   we need to note such spec source anchors in issues because section #s will change over time as we move sections around.  

What i interpret this issue to be about is:   there are various privacy considerations specific to attestation, and the various manners in which it (attestation) may be manifested. Thus there should be some, perhaps modest, notation of such in the overall spec's introduction since we mention attestation there, and even if the detailed specification for  the values of WebAuthnAttestation.statement is moved to a different spec (see #108), we will still have linkage to said attestation spec  and the notion that WebAuthn Scoped Credentials are "attested".

**Comment by equalsJeffH** [comment]
hm. given the level of abstraction the spec's Introduction is written at, it seems to me that a forward link to `{#sec-attestation-privacy}` is most appropriate in the section "Credential Attestation Statements ## {#attestation}"
