### ISSUE TITLE
User agent / key management [authenticator] interoperability requirements?

### ISSUE THREAD

**Issue by mhano** [w3c/webauthn#1020]
One of the primary challenges with previous asymmetric cryptography browser based authentication schemes has been key management (and notably keys being locked into devices/applications/user agents).

#### Some of the Historic Issues:
- Keys lost on OS upgrade / re-installs / wipes / device loss.
- Keys not usable across form factors (mobile app vs desktop browser).
- Keys not usable across devices from different walled ecosystems (apple, google etc.).
- Keys not usable across user-agents / applications.
- Security of keys compromised by malware on devices (sure addressable if user is going to use an external USB key store but these are problematic on many form factors).

Has consideration been given to requiring that user agents support a minimum set of standard APIs for connecting to external software/hardware authenticators / key stores (such that key managers [authenticators] are made available to the user agent via a simple standardised minimum set of APIs / easy user registration).

Note, none of this requires sharing private key material between devices (this is simply about ensuring that 'user agents' can connect to compliant 'authenticators' in standardised ways rather than allowing user agent vendors to support this spec by simply extending their existing walled-ecosystem password/key-management solution).

### Network API
Require that user agents support a Network API which requests authentication (where supported by platform i.e. all network connected devices).
- e.g. Allow user to authorise website login on a desktop device by biometric authentication / presence confirmation / pin entry / etc. on a mobile device (obviously dependant on mobile device app push notifications etc.)

### Local Software API
Require that user agents allow registering of key manager locally. I.e. a conformant 3rdp party password manager (where supported by platform).
- e.g. Key manager could be a local password manager (used across browsers / apps) or software that defers authentication to a more trusted device (i.e. mobile / specialised device etc.) via either a network or local (physical / USB / Bluetooth / NFC) communication.

## Why

Unless the specification mandates and standardises the minimum level of support for external key management there is potentially a risk that these keys will be locked into single platforms like passwords are today (chrome vs safari vs msie password management solutions).

## References

[Ref: 2.2:](https://www.w3.org/TR/webauthn/#conforming-authenticators) As described in §1.1 Use Cases, an authenticator may be implemented in the operating system underlying the User Agent, or in external hardware, or a combination of both.

[Ref: 5.1.3:](https://www.w3.org/TR/webauthn/#createCredential) During the above process, the user agent SHOULD show some UI to the user to guide them in the process of selecting and authorizing an authenticator.

**Comment by equalsJeffH** [comment]
wrt...
> Unless the specification mandates and standardises the minimum level of support for external key management there is potentially a risk that these keys will be locked into single platforms....

this is a known aspect of the present design,  there are things RPs can do to accommodate in the use cases they implement for, see also issue #334

**Comment by emlun** [comment]
I'd say plenty of consideration has been given to these concerns. Some main topics:

**Key loss / account recovery**

1. Individual credentials are designed to be narrowly scoped, disposable and replaceable, rather than ubiquitous and long-lived. We expect users to have more than one credential registered to their account; this way losing one does not lock them out of the account, and the lost credential can simply be revoked and replaced.

**Key mobility**

2. External ("roaming") authenticators are explicitly designed for the use case of using the same credential across multiple client devices - or for initial login to a new client device before a platform credential can be created there - and may implement several transport modes to support a wide variety of client devices (e.g., USB-A for desktops/laptops and NFC for mobile devices).
3. WebAuthn is designed to be compatible with the [FIDO Client to Authenticator Protocol (CTAP)][ctap] as a standardised protocol for external authenticators. Although WebAuthn doesn't actually _require_ implementers to support CTAP, at least Chrome, Firefox and Edge are implementing it.
4. Client platforms may make their platform authenticators available to other client devices - for example, Google is interested in making the platform authenticators on Android smartphones available as roaming authenticators over Bluetooth. This will also use the CTAP protocol for communication between the smartphone and the other client device.

We don't provide any standardised API for software-based authenticators to integrate with, however, although such things should be possible to do as browser plugins.

I don't think the "Network API" example would work with WebAuthn, since there are no central servers for a separate device to be connected to to listen for authentication requests. It could be doable with a third-party browser plugin, server and listener app, but nothing we could feasibly standardise at this point. The "mobile device as bluetooth authenticator" use case solves much the same things, though.

[ctap]: https://fidoalliance.org/specs/fido-v2.0-rd-20170927/fido-client-to-authenticator-protocol-v2.0-rd-20170927.html

**Comment by emlun** [comment]
>We expect users to have more than one credential registered to their account

I think it would be a good idea to add an implementation considerations/best practices section recommending RPs to encourage this. This is related to #403.

**Comment by nadalin** [comment]
@emlun I'm OK with t his but not sure if this can be done in time or we punt this to next level
