### ISSUE TITLE
Ambiguous/wrong instructions in Android Key Attestation Statement Format verification procedure

### ISSUE THREAD

**Issue by sbweeden** [w3c/webauthn#1022]
According to: https://w3c.github.io/webauthn/#android-key-attestation

The verification procedure includes a number of instructions related to processing attestation certificate extension data. 

1. It would be useful to point out that this extension data is oid: "1.3.6.1.4.1.11129.2.1.17"
2. Some verification procedure instructions refer to AuthorizationList:
  - The AuthorizationList.allApplications field is not present, since PublicKeyCredential MUST be bound 
to the RP ID.
  - The value in the AuthorizationList.origin field is equal to KM_TAG_GENERATED.
  - The value in the AuthorizationList.purpose field is equal to KM_PURPOSE_SIGN.

According to the information available at: https://source.android.com/security/keystore/attestation#id-attestation  there are actually TWO AuthorizationList elements within a KeyDescription.

These are:
- softwareEnforced
- teeEnforced

It is ambiguous as to which (or any, or both) of these AuthorizationList objects should be checked for the indicated attributes.

From parsing a test message, I found:
 -  allApplications is in neither (that's ok)
 - origin is in teeEnforced, but not in softwareEnforced
 - ~~purpose appeared in neither (this seems like either a bad attestation test message, or bad advice to check for it)~~ (See comment below)

The specific AuthorizationList(s) to check should be indicated in the verification procedure for these attributes.

I also think that this check is wrong:
 - AuthorizationList.origin field is equal to KM_TAG_GENERATED

I can find no reference anwhere, to any constant in Android called KM_TAG_GENERATED, and expect this was supposed to say: KM_ORIGIN_GENERATED

(see example at https://github.com/NuclearAndroidProject1/android_hardware_libhardware/blob/master/include/hardware/keymaster_defs.h)

**Comment by sbweeden** [comment]
I have one correction to make to my observations above. The "AuthorizationList.purpose" field IS present in the teeEnforced AuthorizationList in the test message I received. That was a bug in my parser that has now been fixed (thanks @herrjemand ). I believe the rest of the comments are still relevant.

**Comment by arnar** [comment]
Thank you for these observations.

Which authorization list to use depends on what the RP wants. If they are satisified with software enforcment the appropriate thing is to consider the union of the two lists. If they require TEE enforcement they should only check the teeEnforced list. It may even be appropriate to look at different lists for the different authorizations. For example an RP might want the key to originate from a TEE, and thus should check that .origin = KM_ORIGIN_GENERATED is on the teeEnforced list - but at the same time be satisified that the "allApplications" is absent from both list.

I'm not sure the best thing is to spell this out in the spec, rather than refer the reader to the Android SafetyNet documentation. We can add language that makes it clear that the RP should pick a combination of authorizationLists that fits their requirement w.r.t. TEE enforcement. What do folks think?

KM_TAG_GENERATED has indeed changed to KM_ORIGIN_GENERATED. Perhaps it's also better here to say something like "If desired, verify that the key material originated from the device by verifying that the .origin field in the authorization list is KM_ORIGIN_GENERATED. If software keys are acceptable, use a combination of softwareEnforced and teeEnforced, if a key generated in a TEE is required use only teeEnforced."

If that sounds reasonable I can type this in a PR.

**Comment by arnar** [comment]
(@agl @nadalin Feel free to assign to me)

**Comment by sbweeden** [comment]
Thanks - that helps a lot. I was coming at this with no prior Android Safety-net experience. Those types of comments in the spec, or even clearly spelt out in the Android Safety-net spec and referenced from webauthn would help a lot.

**Comment by nadalin** [comment]
@arnar Please create PR

**Comment by nadalin** [comment]
@agl Unless a PR is created today we will push this off to L2
