### ISSUE TITLE
Verify signature first in RP operations?

### ISSUE THREAD

**Issue by emlun** [w3c/webauthn#1064]
It's good hygiene in cryptographic operations to [verify signatures before doing anything else][doom]. The [RP Operations][rp] currently list verifying the signature as one of the last steps. Should we rearrange the RP Operations steps to verify the signature as early as possible?

Doing this would not break any compatibility since this is all RP implementation details.

[doom]: https://moxie.org/blog/the-cryptographic-doom-principle/
[rp]: https://w3c.github.io/webauthn/#rp-operations

**Comment by ralshammrei2** [comment]
التنقيه

**Comment by agl** [comment]
Moxie's post is about the dangers of mixing secrets with unauthenticated data. Since the RP is verifying public-key operations, it doesn't apply here.

None the less, if we assume that some RPs might miss some of the enumerated checks, having &ldquo;check the signature&rdquo; be step 16 of 17 might be a little dangerous. So I wouldn't object to prioritising it if someone wanted to make the PR.

**Comment by emlun** [comment]
Yes, I agree it's different in this case since there's no encrypted data in this protocol, so it's probably not a big deal. Rather something that might be worth considering.
