### ISSUE TITLE
Leap of Faith not only for Self and None Attestation Types

### ISSUE THREAD

**Issue by milesstoetzner** [w3c/webauthn#1088]
Do the [Considerations for Self and None Attestation Types](https://www.w3.org/TR/webauthn/#sctn-no-attestation-security-attestation) also apply for any kind of attestation type?

Lets assume that there is a man-in-the-middle (MiM) who owns the same authenticator as the user or any authenticator that is accepted by the Relying Party. The attacker could simulate that a user is present or that a user is verified - for example by a device touching a button or entering a PIN on the attackers authenticator (this is not bypssing test of user presence or user verification). Therefore the attacker can automatically perform registrations (using any attestation type) and authentications.

During Registration the MiM replaces the attestationObject, that had been generated by the users authenticator, with the attestationObject, that had been generated by the attackers authenticator using the mentioned device.

The Relying Party can not detect the attack. Therefore we are in the same situation as if we would have used Self or None Attestation: leap of faith.

Three considerations: 
- The Relying Party could restrict the allowed AAGUIDs. But I think we can assume that if a user can buy an accepted authenticator, the attacker can also buy one.
- The Relying Party could only accept biometric user verification. But I think we can ignore this case since the Relying Party cant detect this without using optional extensions.
- I know that this attack is even more difficult than the one mentioned in the specification which is already declared as difficult and as easy to detect.

What do you think about that? 

I hope this is not a repost. I could not find anything about that.

Greetings, 
Miles

**Comment by emlun** [comment]
Hm, I think you are right. In fact, perhaps we should just delete the whole section [§13.3.1. Considerations for Self and None Attestation Types and Ignoring Attestation][sec], and also remove "Registration and" from item (3) in [§13.3. Security Benefits for WebAuthn Relying Parties][secben].

Biometric user verification also wouldn't help, since that only verifies what was established at registration time.

[sec]: https://www.w3.org/TR/webauthn/#sctn-no-attestation-security-attestation
[secben]: https://www.w3.org/TR/webauthn/#sctn-rp-benefits

**Comment by milesstoetzner** [comment]
I would not delete the whole section. The considerations should be extended in regards of all attestation types.

**Comment by emlun** [comment]
I drafted a rewrite of this in PR #1095. @milesstoetzner you're welcome to review it; preview is available [here][preview] and diff [here][diff].

[preview]: https://pr-preview.s3.amazonaws.com/w3c/webauthn/pull/1095.html#sctn-attestation-guarantee-limitations
[diff]: https://pr-preview.s3.amazonaws.com/w3c/webauthn/1095/2056fee...782c678.html#sctn-rp-benefits

**Comment by equalsJeffH** [comment]
hm, if I understand correctly, there's various nuances to the overall man-in-the-middle (MITM) class of attacks and how webauthn defends against them than the [original post](https://github.com/w3c/webauthn/issues/1088#issue-364977414) (OP) assumes/discusses:
> Lets assume that there is a man-in-the-middle (MiM) who owns the same authenticator as the user or any authenticator that is accepted by the Relying Party.  

If the above imagines that the attacker places a discrete MITM system between the user's system and the RP's server, it seems to me that it will be detectable by RPs who properly perform verification at the TLS layer and up. Caveat: the attacker must have managed to have a trusted CA mis-issue an impostor TLS cert for the RP (the discrete MITM system will need to terminate the RP <--> ATKR  and ATKR <--> USER  TLS connections).  

In this situation, without such an impostor cert the user likely will be presented with a "dangerous connection" interstitial page, and if HSTS policy has been by the RP (or established via pre-loading), the user will have no click-through recourse (if HSTS is faithfully implemented by the user agent).

Even with such an impostor cert, if the user already has interacted with the RP in the past, and established a [TLS Token Binding ID,](https://tools.ietf.org/html/rfc8473) say, which is used by the RP to (for example) bind any of the RP's cookies set on the user's browser, then the MITM is detectable by the RP (of course the RP needs to carefully validate everything on their end of the connection in order to detect such malfeasance). 

> During Registration the MiM replaces the attestationObject, that had been generated by the users authenticator, with the attestationObject, that had been generated by the attackers authenticator using the mentioned device. 

Actually, AFAICT, the MITM (aka MiM) will need to replace the entire returned [PublicKeyCredential](https://w3c.github.io/webauthn/#publickeycredential) object rather than only the [attestation object](https://w3c.github.io/webauthn/#attestation-object) because [PublicKeyCredential](https://w3c.github.io/webauthn/#publickeycredential).[response ](https://w3c.github.io/webauthn/#dom-publickeycredential-response) conveys the [clientDataJSON ](https://w3c.github.io/webauthn/#dom-authenticatorresponse-clientdatajson) separate from the [attestationObject](https://w3c.github.io/webauthn/#dom-authenticatorattestationresponse-attestationobject) and the clientDataJSON is needed to validate the signature within the [attestationObject](https://w3c.github.io/webauthn/#dom-authenticatorattestationresponse-attestationobject) [1].


> The Relying Party can not detect the attack.

Well, it seems, IIUC, that the RP can detect things as discussed above when the attacker is embodied as a discrete MITM system between the user's system and the RP's server, no?

However, if the attacker is embodied as a man-in-the-browser (MITB), then I tend to agree that providing assurances are tough, because the TLS protections are essentially obviated -- but it depends on the attacker getting everything exactly correct, continuously MITB'g subsequent authn ceremonies, and there not being any browser characteristics alterations the RP might detect.  

Probably there's many more fine details to tease apart here, though to what level of detail we ought to go in the spec is a good question. I have some modest comments on the pull request I'll try to write up tomorrow. 

HTH

###
[1] tho the attacker may be able to get by with only replacing the [PublicKeyCredential](https://w3c.github.io/webauthn/#publickeycredential).[response](https://w3c.github.io/webauthn/#dom-publickeycredential-response) value (unless the RP is validating that  `PublicKeyCredential.rawId` is the same as `attestationObject.authData.attestedCredentialData.credentialId`) and/or the RP is doing something with those two values such that not having them be equivalent will break things and throw errors.

**Comment by milesstoetzner** [comment]
> hm, if I understand correctly, there's various nuances to the overall man-in-the-middle (MITM) class of attacks and how webauthn defends against them than the [original post](https://github.com/w3c/webauthn/issues/1088#issue-364977414) (OP) assumes/discusses:
> 
> > Lets assume that there is a man-in-the-middle (MiM) who owns the same authenticator as the user or any authenticator that is accepted by the Relying Party.
> 
> If the above imagines that the attacker places a discrete MITM system between the user's system and the RP's server, it seems to me that it will be detectable by RPs who properly perform verification at the TLS layer and up. Caveat: the attacker must have managed to have a trusted CA mis-issue an impostor TLS cert for the RP (the discrete MITM system will need to terminate the RP <--> ATKR and ATKR <--> USER TLS connections).
> 
> In this situation, without such an impostor cert the user likely will be presented with a "dangerous connection" interstitial page, and if [HSTS policy](https://tools.ietf.org/html/rfc6797) has been declared by the RP (or established via [pre-loading](https://hstspreload.org/)), the user will have no click-through recourse (if HSTS is faithfully implemented by the user agent).
> 
> Even with such an impostor cert, if the user already has interacted with the RP in the past, and established a [TLS Token Binding ID,](https://tools.ietf.org/html/rfc8473) say, which is used by the RP to (for example) bind any of the RP's cookies set on the user's browser, then the MITM is detectable by the RP (of course the RP needs to carefully validate everything on their end of the connection in order to detect such malfeasance).
> 
> > During Registration the MiM replaces the attestationObject, that had been generated by the users authenticator, with the attestationObject, that had been generated by the attackers authenticator using the mentioned device.
> 
> Actually, AFAICT, the MITM (aka MiM) will need to replace the entire returned [PublicKeyCredential](https://w3c.github.io/webauthn/#publickeycredential) object rather than only the [attestation object](https://w3c.github.io/webauthn/#attestation-object) because [PublicKeyCredential](https://w3c.github.io/webauthn/#publickeycredential).[response ](https://w3c.github.io/webauthn/#dom-publickeycredential-response) conveys the [clientDataJSON ](https://w3c.github.io/webauthn/#dom-authenticatorresponse-clientdatajson) separate from the [attestationObject](https://w3c.github.io/webauthn/#dom-authenticatorattestationresponse-attestationobject) and the clientDataJSON is needed to validate the signature within the [attestationObject](https://w3c.github.io/webauthn/#dom-authenticatorattestationresponse-attestationobject) [1].
> 
> > The Relying Party can not detect the attack.
> 
> Well, it seems, IIUC, that the RP can detect things as discussed above when the attacker is embodied as a discrete MITM system between the user's system and the RP's server, no?
> 
> However, if the attacker is embodied as a man-in-the-browser (MITB), then I tend to agree that providing assurances are tough, because the TLS protections are essentially obviated -- but it depends on the attacker getting everything exactly correct, continuously MITB'g subsequent authn ceremonies, and there not being any browser characteristics alterations the RP might detect.
> 
> Probably there's many more fine details to tease apart here, though to what level of detail we ought to go in the spec is a good question. I have some modest comments on the pull request I'll try to write up tomorrow.
> 
> HTH
> 
> [1] tho the attacker may be able to get by with only replacing the [PublicKeyCredential](https://w3c.github.io/webauthn/#publickeycredential).[response](https://w3c.github.io/webauthn/#dom-publickeycredential-response) value (unless the RP is validating that `PublicKeyCredential.rawId` is the same as `attestationObject.authData.attestedCredentialData.credentialId`) and/or the RP is doing something with those two values such that not having them be equivalent will break things and throw errors.

**Comment by milesstoetzner** [comment]
That was just an accident.

**Comment by milesstoetzner** [comment]
I just wanted to point out, that my assumption about an existing MiM is taken from the [specification](https://www.w3.org/TR/webauthn/#sctn-no-attestation-security-attestation) - extended by the fact, that the attacker can own an by the RP accepted Authenticator and ,therefore, is able to create a valid AttestationObject using all kinds of AttestationTypes (not just Self or None).

**Comment by emlun** [comment]
@equalsJeffH Yes, I agree with your assessment. Assuming TLS is used, and correctly, a discrete MitM is an unlikely scenario; what I was considering is mainly the MitB case, by the RP inadvertently including malicious script (whether via XSS or explicitly loading script from another domain) on their page for example. I would like to mention something like Content Security Policy, and perhaps Token Binding, as an example protection instead of just "TLS and related technologies", but I'm not sure which of these technologies are applicable and mature.

Ah, yes, you're right that in the general case the attacker does need to replace most of the `PublicKeyCredential` object. The attacker doesn't need to change the `clientDataJSON`, but would have to be able to control the generated credential ID in order for the signed `attestationObject.authData.attestedCredentialData.credentialId` to agree with the `PublicKeyCredential.rawId`. This can be done with Self and None attestation but not if the attestation object needs to be recognized as a genuine attestation from a trusted authenticator vendor, since that would require using a genuine authenticator device that would generate the credential ID internally.

**Comment by milesstoetzner** [comment]
> The attacker doesn't need to change the `clientDataJSON`, but would have to be able to control the generated credential ID in order for the signed `attestationObject.authData.attestedCredentialData.credentialId` to agree with the `PublicKeyCredential.rawId`.

This only holds true, if the attacker wants to register the same `credentialId` as generated by the user - but he doesn't have to. Since he can replace `PublicKeyCredential.response`, he can also replace `PublicKeyCredential.rawId`.

**Comment by emlun** [comment]
Agreed.

**Comment by equalsJeffH** [comment]
@milesstoetzner commented:
> Since he can replace PublicKeyCredential.response.attestationObject, he can also replace PublicKeyCredential.rawId.

Yes, the attacker can and probably should/would (in order to be successful) -- that's what I was getting at in footnote [1].

@emlun commented:
>  what I was considering is mainly the MitB case, by the RP inadvertently including malicious script (whether via XSS or explicitly loading script from another domain) on their page for example.

Yep. If we're going into details then I'm thinking we'd want to be explicit about the threat model (discrete MITM vs MITB)

>  I would like to mention something like Content Security Policy [**CSP**], and perhaps Token Binding, as an example protection instead of just "TLS and related technologies", 

agreed.

>  I'm not sure which of these technologies are applicable and mature.

CSP can mitigate XSS but one's webapp needs to be structured to take advantage of CSP. [CSP L1 is well-supported, CSP L2 is fairly-well-supported](https://caniuse.com/#search=content%20s). So CSP would seem to be a mitigation against MITB injection.

Token Binding is emergent, and its use is expressly to cyptographically bind protocol artifacts such as cookies or webauthn responses to the TLS layer, thus is a mitigation for discrete MITM's replay of protocol artifacts.

**Comment by emlun** [comment]
Moved to L2 along with #1095.
