### ISSUE TITLE
Relying Party Session

### ISSUE THREAD

**Issue by milesstoetzner** [w3c/webauthn#1111]
Does the specification say something about the session handling and session separation of the Relying Party? I can not find something specific.

Would it be allowed in the concept of WebAuthn to respond to an authentication by sending your `assertionSignature` to the route `/authenticate?challenge=1233455` and not using cookies for a session? Where  `1233455` is the challenge generated for an authentication of a user.

**Comment by milesstoetzner** [comment]
Ok, thanks for the answer. 

Therefore a MitB could intercept a valid response of an authentication and send it in an own connection to the given route in order to impersonate the user.

That is what I was thinking about.

**Comment by milesstoetzner** [comment]
And I have to admit, that I proved, that I am not able to NOT CLOSE my issues by accident ... sry for that.

**Comment by emlun** [comment]
> Therefore a MitB could intercept a valid response of an authentication and send it in an own connection to the given route in order to impersonate the user.

Yes, I guess so. The MitB attacker can't tamper with any of the signed data, but it can indeed steal the `AuthenticatorAssertionResponse` and use it to log in from a different machine - *unless* Token Binding is in use, I think. But then again, it might not be necessary for the MitB to move to a different machine to carry out their attack.

WebAuthn doesn't try very hard to defend against MitB attacks, since a successful MitB attacker could cause all kinds of havoc anyway (say, present one thing to the user while something else is actually being signed). The [`txAuthSimple`][ext-sim] and [`txAuthGeneric`][ext-gen] extensions provide some possible mitigations against that kind of attack.

[ext-sim]: https://w3c.github.io/webauthn/#sctn-simple-txauth-extension
[ext-gen]: https://w3c.github.io/webauthn/#sctn-generic-txauth-extension
