### ISSUE TITLE
TPM attestation format & EdDSA & hash alg

### ISSUE THREAD

**Issue by tanguilp** [w3c/webauthn#1148]
In the "Verification procedure" of "8.3. TPM Attestation Statement Format", it is written:

> Verify that extraData is set to the hash of attToBeSigned using the hash algorithm employed in "alg".

What should the hash algorithm be for the ed25519 and ed448 curves? I've had a hard time trying to figure out what the hash algs are for both, and I'm very unsure about my findings but it seems to me that internally these are respectively sha256 and a flavour of sha3, or none (some ed* libs do not require a digest alg as an input, but the whole message). Besides, if they're indeed different, the "alg" field wouldn't be sufficient to determine the hash alg (value -8, name EdDSA).

**Comment by agl** [comment]
I don't believe any TPM has ever used ed25519 nor ed448. But you're correct that the hash function to use in that case wouldn't be clear. I think the TPM standards would have to clarify that should any TPM want to use those signature schemes.

**Comment by herrjemand** [comment]
@tanguilp @alg TPM2.0 specs does not support EDDSA at that moment. Let's wait for TPM3.0? XD

Regarding the hashing algorithm:
ED25519 uses SHA512 https://tools.ietf.org/html/rfc8032#section-5.1
ED448 uses SHAKE256 https://tools.ietf.org/html/rfc8032#section-5.2.6

**Comment by nadalin** [comment]
@rlin1 Can we close this no action ?

**Comment by herrjemand** [comment]
@nadalin This one is safe to close with no action.

**Comment by rlin1** [comment]
In the field "alg" we expect the COSEAlgorithmIdentifier.
The Edwards-curve related identifier is "EdDSA" (see https://www.iana.org/assignments/cose/cose.xhtml#algorithms).
The related algorithm is described in https://tools.ietf.org/html/rfc8152#page-40.
According to that (referenced) descripton, only the "pure" version of EdDSA is supported: "This is because it is not expected that extremely large
   contents are going to be needed and, based on the arrangement of the
   message structure, the entire message is going to need to be held in
   memory in order to create or verify a signature"

**Comment by rlin1** [comment]
At this time TPMs do not support EdDSA, so in the TPM attestation statement "EdDSA" cannot appear.
Let's wait until the TPM spec includes definitions for EdDSA and then see whether such algorithm includes any explicit hash algorithm, or not.

**Comment by rlin1** [comment]
Will close with no action at this time.
