### ISSUE TITLE
WebAuthn API for Browser (like Chrome) extension

### ISSUE THREAD

**Issue by Kieun** [w3c/webauthn#1158]
Currently, there is no way to use WebAuthn APIs directly within the browser extension (e.g., Chrome extension).
In case of Chrome extension, although the WebAuthn APIs are exposed to the application, the API calls always fail (**NotAllowedError**) since the calling app's origin scheme is not _https_.
We are providing almost similar authentication user experience both for the web and and browser extension cases.
It'd better to discuss how we leverage WebAuthn API for the browser extension.

**Comment by agl** [comment]
This seems like a Chrome bug report? As such, I don't think it applies here.

The reason that extensions in Chrome cannot call Webauthn is because they don't have standard domains, and WebAuthn is based around RP IDs. Chrome does not have any plans to change this at the moment and it's not clear how extensions could be mapped into WebAuthn's RP ID space.

You might want to open a Chrome bug on this, but I don't think it would be considered in the near team.

**Comment by kyranjamie** [comment]
Webauthn support since added in Chromium, see https://bugs.chromium.org/p/chromium/issues/detail?id=824383
