### ISSUE TITLE
double check language regarding requiring authorization gesture

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#1215]
given that we have the notions of [effective user verification requirement for credential creation](https://www.w3.org/TR/webauthn/#effective-user-verification-requirement-for-credential-creation) and [effective user verification requirement for assertion](https://www.w3.org/TR/webauthn/#effective-user-verification-requirement-for-assertion), we ought to grep thru the spec for places where  [authorization gesture ](https://www.w3.org/TR/webauthn/#authorization-gesture) is mentioned and ensure that it is being employed accurately. For example, in section [5.1.4. Use an Existing Credential to Make an Assertion - PublicKeyCredential’s \[\[Get\]\](options) Method](https://www.w3.org/TR/webauthn/#getAssertion), there is this claim:  
> since this specification requires an authorization gesture to create any credentials,

..which I do not believe is true any longer.

**Comment by emlun** [comment]
We've defined the term "authorization gesture" to mean any kind of human confirmation, including a test of user presence [which is still required in authenticatorMakeCredential][amc], so the claim

>since this specification requires an authorization gesture to create any credentials,

is still true.

However we could tie things together better by rephrasing the authenticator operations a bit, since they currently don't reference the "authorization gesture" term at all.

[amc]: https://www.w3.org/TR/webauthn/#op-makecred-step-user-consent
