### ISSUE TITLE
navigator.credentials.get() option to suppress chrome UI popup if allowCredentials is not present in the authenticator

### ISSUE THREAD

**Issue by kmlhossen** [w3c/webauthn#1251]
I was trying WebAuthN in the chrome with mac inbuilt fingerprint scanner (platform authenticator only) and wondering what will be the solution of the following use case for a relying party

Let's say user registered webauthn in device **A** with the relying party **R**.
Authentication flow is like this, the user comes to the relying party **R** input username and clicks next, relying party pulls the previously registered credential Ids for the user to create allowCredentials and query the authenticator for authentication. All goes fine as the built in authenticator has one of those allowCredentials associated private key

But let's say the same user goes to the device **B** not registered before and tries to login with the same relying party **R** by putting username and clicking next. This time again the relying party pulls over the registered credential Ids for the user to create allowCredentials and query the authenticator for authentication. But this time as the device **B** does not have any associated private key it shows an error popup window in chrome.

Is there any way we can pass any option to the navigator.credentials.get call so that if the associated private key is not present for the given allowCredentials we can just stop the webauthn flow by catching some error.

Or is there anyway chrom can detect the error and pass it to the caller so that caller can take action instead of showing error to user by default

This will help to fall back to some other authentication method without showing the error popup window and ask the user later to register device B after successful login with other authentication methods.

**Comment by Kieun** [comment]
The easiest way for this is to store credential ids on the client side such as local storage or cookie if the authenticator is platform authenticator. Even if there are some corner cases when user uses other browsers or privacy mode for the authentication, we can avoid many of such situations.
Regarding the error popup, it seems Chrome's policy.

**Comment by kmlhossen** [comment]
Yes, storing the credential Id in the local storage/cookie and using it as a hint to whether query the inbuilt authenticator or not is an option. But that is still not an ideal experience for the end user.

It will make the registration to a relying party per device per browser. Once registered in a device(having inbuilt authenticator) to a relying party he should be able to use any supported browser.

**Comment by Kieun** [comment]
If you are caring about the UX, the best way is that get hints as much as possible and leverage them to scope down the authentication options. Or, the other way is to let the browser/platform handle such situations smartly. I understand this is not your preferred way.
Let's see how platform/browser vendors think about this kind of RPs' difficulties.

**Comment by emlun** [comment]
Sorry, returning a specific error for this case is unfortunately not an option, because that would enable malicious RPs to use WebAuthn credentials to identify users without consent. See [§13.6. Authentication Ceremony Privacy](https://w3c.github.io/webauthn/#sctn-assertion-privacy). The UI popup is necessary so that the RP cannot use timing information to determine if the browser canceled the ceremony because no credential is available, or if the user canceled the popup asking whether to proceed. The alternative would be to always wait for the timeout before returning a `NotAllowedError`, which would be even worse UX.

This feature request is incompatible with the [de-anonymization prevention measures](https://w3c.github.io/webauthn/#sctn-non-correlatable-credentials) in WebAuthn; I propose closing the issue.

**Comment by npesic** [comment]
The UX is important to the user probably as much as privacy.

Built in authenticator would require user to register a webauthn key for the same site on each device he is using.

Can we have a way to message user that the key is not found because this is a new device, never been used for this site yet, and that registration is needed for a new device to be used.

This is legit use case. Although it look similar as a privacy invasion attempt.

It is reasonable to expect that one user can have two or more devices that he wants to use with one site. There should be a way to build a good UX that will guide user in steps needed to be done, so that he can achieve what he wants.

Does this use case make sense? Please, advise.

**Comment by emlun** [comment]
Yes, the use case and the concerns are legitimate, and UX is indeed important, but we concluded on the 2019-07-11 WG call that we cannot accomodate this request due to the mentioned privacy considerations. We suggest using cookies or similar client-side storage as a way (although imperfect) to determine whether the user is visiting on a new device.
