### ISSUE TITLE
Why does WebAuthn require a challenge when asking the client to register a new credential?

### ISSUE THREAD

**Issue by johnnyodonnell** [w3c/webauthn#1355]
When [registering a new credential](https://w3c.github.io/webauthn/#sctn-registering-a-new-credential), why does the client need to be sent a [challenge](https://w3c.github.io/webauthn/#dom-publickeycredentialcreationoptions-challenge)?

Presumably this is to prevent a replay attack, but wouldn't a replay attack be prevented by TLS already?

**Comment by e3b0c442** [comment]
I suspect for the same reason you almost universally have to enter an OTP code to verify registration of a new TOTP token -- to validate that you actually have the correct key and can make the signature.

**Comment by johnnyodonnell** [comment]
But then why is a challenge needed? Couldn't the client just sign the `clientDataJSON.type` and the `clientDataJSON.origin` and that would prove ownership of the correct key?

**Comment by nickmooney** [comment]
https://www.w3.org/TR/webauthn-2/#sctn-security-considerations-rp

Yes, the challenge is present to prevent replay attacks. There are other controls that could fail outside of TLS to enable a replay attack at various points between the authenticator / client / server.

**Comment by johnnyodonnell** [comment]
@nickmooney do you know which controls fail outside of TLS? I'm aware that it is possible for a man in the middle to execute a replay attack by fooling a user or a user's browser to retry a request. The man in the middle can do that by sending a TCP reset back to the client and by still sending the original request through. Thus, (and I'm still guessing here) the following situation could be possible without the challenge:

1. A user tries registering a new credential.
2. That request is held by a man in the middle and a TCP reset is sent to the user's browser.
3. The user's browser retries the request and successfully registers the new credential.
4. Within a short period of time, the user decides to deregister their credential.
5. Again within a short period of time, the man in the middle releases the original request to the server and thus, the credential is re-registered without the user's knowledge.
6. Sometime later, the man in the middle steals the user's FIDO2 authenticator.
7. The man in the middle can now pose as the user.

Am I on the right track here?

**Comment by marekciupak** [comment]
Do challenge and origin help to protect against attack during registration ceremony in any way if "none" attestation method is used?

I mean, I think the origin and challenge are not signed (during registration with "none" attestation method) in any way and could be easily swapped by javascript (due to xss) or man in the middle (phishing side controlled by an attacker) without swapping the public key or credential id.

Am I not seeing something?

**Comment by Firstyear** [comment]
You may find this talk helpful @marekciupak  :) https://www.youtube.com/watch?v=F4dBEpVjOuI

**Comment by marekciupak** [comment]
The video didn't answer my question.. He said that the challenge and origin are signed by the client, which is not true as far as I understand, and he probably was just not precise and meant "by authenticator". But IMO there are signed only via attestation, and it is surprising to me, because there are different attestation methods (including "none") and attacker could sign the data by his attestation certificate in case of Anonymous CI method, etc. So, IMO you can not trust origin or challenge sent back to the back-end during registration ceremony (unless you trust attestation, but usually it is not used in popular websites such as Google, Facebook, etc.). Maybe it is not a big problem, because there are no good attack vectors against registration. The authentication ceremony is safe as data is always signed by the private key.

I tested it on https://webauthn.io/ (the same way as he tested his case on the video) via js console. I was able to change the challenge in JS console, just before sending it to the authenticatior. Afterwards I changed the response (I updated only the challenge without touching the public key) from the authenticator just before sending it to the backend. So, in the other words, I believe I would be able to use a stale response from the authenticator just by changing the challenge.

**Comment by emlun** [comment]
@marekciupak Correct, if the attestation statement format is `"none"` then the registration response is not signed. Similarly, if the attestation statement format is `"self"` then the registration response is signed by the credential private key - but the corresponding credential public key is conveyed in the same message, so an attacker could easily replace both the public key and the signature (or just replace it with a `"none"` attestation), so the self attestation signature only protects against accidental data corruption but not against intentional manipulation. The challenge does have some value for the other attestation statement formats, though. But in general, WebAuthn credential keys are "trust on first use" - see also [§13.4.4. Attestation Limitations](https://www.w3.org/TR/webauthn-2/#sctn-attestation-limitations).

**Comment by marekciupak** [comment]
@emlun thank you for the clarification!
