### ISSUE TITLE
MDN panels do not appear in editors' draft

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#1414]
pr #1411 landed, but the "MDN Panels" are not appearing in the editors' draft https://w3c.github.io/webauthn/  --- however, they do appear when I build the spec locally :(

**Comment by wseltzer** [comment]
@dontcallmedom do you know what might be going wrong here? Thanks!

**Comment by dontcallmedom** [comment]
I'm not sure if the bikeshed cache local to this repo is still being used to generate the spec, but maybe it is what interfering with the build? 

@sideshowbarker knows this overall system best, in any case

**Comment by sideshowbarker** [comment]
> I'm not sure if the bikeshed cache local to this repo is still being used to generate the spec, but maybe it is what interfering with the build?

Yes, that was the problem. The Travis CI build that publishes the spec to the `gh-pages` branch and thus to https://w3c.github.io/webauthn/ doesn’t use up-to-date data files that Bikeshed normally relies on but instead uses copies that are under version control in the `.spec-data` and `.bikeshed-include` directories of this repo.

Those copies were over 2 years out of date, so I took the liberty of updating them and pushing the update to the master branch. So https://w3c.github.io/webauthn/ now has MDN annotations.

As far as that mechanism to keep copies of the Bikeshed data files under version control in the repo: I don’t understand what the rationale was for it setting up to begin with — so to prevent another problem in the future like the one described in this issue, I’d personally recommend that those copies be removed from the repo and that the `.travis.yml` file in the repo be changed to stop relying on those copies and instead use the data files that Bikeshed would otherwise be using.

But if the editors don’t want to change that setup for the time being, then somebody needs to take responsibility for periodically doing this:
 ```
./update-bikeshed-cache.sh && git add .spec-data .bikeshed-include && git commit .
```
The `README.md` in the repo already provides how-to steps on doing that. And there was one minor problem with a message the `update-bikeshed-cache.sh` script emits, but #1427 has a fix for that.

So, going forward, if the steps currently documented in the `README.md` file are followed, everything that’s already set up for this repo should work as expected — and future problems like the one described in this issue will be avoided.

**Comment by sideshowbarker** [comment]
> The `README.md` in the repo already provides how-to steps on doing that. …
> So, going forward, if the steps currently documented in the `README.md` file are followed

Actually, I misspoke: The how-to steps on updating the repo copies of the data files were not actually documented in the `README.md` file. But #1428 adds them.

**Comment by equalsJeffH** [comment]
@sideshowbarker 
> So https://w3c.github.io/webauthn/ now has MDN annotations.

Yay! thanks!

> As far as that mechanism to keep copies of the Bikeshed data files under version control in the repo: I don’t understand what the rationale was for setting it up to begin with...

I seem to dimly recall that it may have been because as bikeshed evolved (this was a while back) we had some cases where the spec didn't keep up and wouldn't build so we nailed down the bikeshed version.  Otherwise, I dunno.

> I’d personally recommend those copies be removed from the repo and that the .travis.yml file in the repo be changed to stop relying on those copies and instead use the data files that Bikeshed would otherwise be using.

Sure, if that can be set up so it consistently works. 

> The how-to steps on updating the repo copies of the data files were not actually documented in the README.md file. But PR #1428 adds them.

thanks!

**Comment by wseltzer** [comment]
Thanks @sideshowbarker and @equalsJeffH! Shall we close this issue?

**Comment by sideshowbarker** [comment]
Yes — think it’s been resolved
