### ISSUE TITLE
New platform authenticators are making discoverable credentials regardless of residentKey=false passed to Create()

### ISSUE THREAD

**Issue by ve7jtb** [w3c/webauthn#1457]
We have talked about prohibiting this for consistency in Level 2,  but the trend at least for the moment is in the other direction.

See iOS platform authenticator.

**Comment by equalsJeffH** [comment]
see also issue #1459

**Comment by agl** [comment]
I think this issue might be closable now. While the landed PR doesn't solve the underlying problem, I suspect that we have done all that we can in WebAuthn.

**Comment by equalsJeffH** [comment]
I removed the "pr-open" label because PR #1467 was merged (but failed to auto-close this issue).  However, we note that the underlying issue is still there, so we'll leave this open at this time, but maybe we've done all that we're going to do at the WebAuthn layer.

**Comment by equalsJeffH** [comment]
on 2020-09-02 call:  @sbweeden desires this to change, notes that this is an issue for RPs.  @nadalin asked @nicksteele to raise this question/issue in the webauthn-adoption community.

**Comment by akshayku** [comment]
There are other options on the table. 

- RP can do platform based logic.
- RP can ask all platforms to support resident keys.
- RP's can include exclude list all the time. 

We probably will change it to support non-discoverability and not make it a resident key. But we are not in favor or reintroducing "forbidden" option.

**Comment by equalsJeffH** [comment]
on 2020-09-09 call: this is being brought up in the webauthn adoption CG.  We've decided to keep this around to track the issue. not expecting spec changes at this time.

**Comment by arianvp** [comment]
The opposite also seems true.

Google Chrome for Android  will happily created a server-side credential without erroring out, even when setting `requireResidentKey` to `required`.  I would expect it to error out as described in the spec, but it silent generates a server-side credential.

The spec says I can differentiate between these cases using the `credProps` extension in the cases of `discouraged` and `preferred`.

But what do I do with misbehaving platforms that don't error out as the spec mandates?

**Comment by sbweeden** [comment]
I don’t believe Chrome on Android implements WebAuthn L2 yet.

**Comment by arianvp** [comment]
@sbweeden the cited line was part of L1 too though  See step 4 of https://www.w3.org/TR/webauthn/#op-make-cred

> If requireResidentKey is true and the authenticator cannot store a client-side-resident public key credential source, return an error code equivalent to "ConstraintError" and terminate the operation.

**Comment by sbweeden** [comment]
I don’t think that it’s clear whether or not Android stores a client side resident key. What is clear is that Chrome on Android doesn’t support assertion with an empty allowCredentials list. Subtle difference I know but an argument could be made that the create operation is still valid. In any case this is something the Google folks are best positioned to answer.

**Comment by arianvp** [comment]
Hmm; but the spec is pretty clear about how `get` should behave after a `create` with `requireResidentKey=true` is performed.    Chrome for Android not supporting an empty `allowCredentials` list sounds like a clear deviation from both the L1 and L2 spec to me:

From the spec on `requireResidentKey`:

> This member describes the Relying Party's requirements regarding resident credentials. If the parameter is set to true, the authenticator **MUST create a _client-side-resident public key credential source_ when creating a public key credential**

And from the definition of **client-side-resident public key credential source**:

>  Such client-side storage requires a resident credential capable authenticator and has the property that the authenticator **is able to select the credential private key given only an RP ID**, possibly with user assistance (e.g., by providing the user a pick list of credentials scoped to the RP ID)

This reads to me, unambigiously,  as: **if** `create` succeeds with `requireResidentKey = true` then I can rely on  `get` being able to work with `allowCredentials = []` if the same authenticator is inserted.


What I want to know is, an implementor of an RP; how do I detect this edge-case where I _required_ a resident credential during registration; but when the user presents the same hardware token during login, the  resident credential flow doesn't work?

The simple requirement is  "I want people who register with a token to be able to login with that token".  and i don't see a way how I can currently require that; which is not great.

I tried setting `extensions: { credProps: true }`  so that I can look at the `rk` property after credential creation, but that does not seem to be implemented by Chrome yet (at least it didn't work for me).

**Comment by arianvp** [comment]
I found a page that claims that Chrome for Android does indeed not implement residentKeys: https://codelabs.developers.google.com/codelabs/webauthn-reauth/#4

However; that means I would expect `create`  with `requireResidentKeys = true` to fail; as per the Webauthn L1 spec; instead of   `get` to fail when you do not pass any credentials. 

I agree this is something we should clarify with the folks at Google. What is the best course of action here? Shall I open a bug report on chromium and cross-link it here?

**Comment by equalsJeffH** [comment]
> I found a page that claims that Chrome for Android does indeed not implement residentKeys

If one's browser supports direct-text-linking, [the statement in that page @arianvp is referring to is here](https://codelabs.developers.google.com/codelabs/webauthn-reauth/#steps:~:text=However%2C%20the%20latest%20version%20of%20Chrome,not%20support%20the%20resident%20key%20functionality).

We working on addressing this sometime in 2021 (however, no guarantee is implied or should be inferred).

**Comment by arianvp** [comment]
Would it be possible to let chrome for android throw an exception when `requireResidentKey = true` is set in a more short term though?  Currently I need to special case Chrome for Android by user agent matching as it seems to be the only one that doesn't conform to the L1 specification in this specific scenario. And that sounds more like a bug than a missing feature to me... Though I might be interpreting the spec too strictly.

**Comment by jurepurgar** [comment]
> We are working on addressing this sometime in 2021 (however, no guarantee is implied or should be inferred).

@equalsJeffH Does this mean that there is a plan for Chrome on Android to completely support resident keys or just prevent registration if resident key is required? Can we track the progress anywhere?

Login with resident keys was working in Chrome Custom Tabs a some point, but it is not working any more. It seems there is no technical obstacle to support resident keys on Android, is there another reason this is not supported?
