### ISSUE TITLE
How "preferred" is a "preferred" resident key

### ISSUE THREAD

**Issue by christiaanbrand** [w3c/webauthn#1463]
Now that we have the residentKey tri-state {discouraged, preferred, required} implemented, we should define what "level of preferredness" preferred actually means so that users have a consistent experience across client platforms.

There are multiple options:
i) We’ll always create a resident key, even if we have to guide the user in setting up a PIN first.
ii) If internal-UV or a PIN is already configured, we’ll prompt for a PIN / do UV and, if successful, create a resident key.

I'd like to vote that we do (i) where possible, and on devices (such as phones where we can't guide the user through PIN setup today) we do (ii), but with the intent to move to (i) in the long run.

What do folks thinks about this? Can we make a PR to tighten this up in the spec?

**Comment by ve7jtb** [comment]
Platform authenticators on phones always have UV so you must be talking about roaming authenticators.

If there is no pin or uv provisioned then you can make with rk=true and it will work.   That is basically the same as uv preferred logic.   I think the only change with i) is that you want to treat uv as required if the platform can guide the user to set a pin or uv.

If CTAP2 is not supported or it is a U2F key then you have to make a rk=false credential.

Another question to consider. 
If preferred and credential storage is full should the platform try it as rk=true and if it gets a error retry rk=false?.

**Comment by christiaanbrand** [comment]
> Platform authenticators on phones always have UV so you must be talking about roaming authenticators.

Kinda. Phones *can* all do UV, but if UV isn't set up we'll make a non-RK credential.

> If preferred and credential storage is full should the platform try it as rk=true and if it gets a error retry rk=false?.
Indeed.

**Comment by ve7jtb** [comment]
Interesting I was under the impression that you needed some sort of UV on the phone to use the hardware backed keys.  
I guess I have never set up a Android phone without a pin or biometric.

The spec would allow you to make a rk credential in that case on the platform, the problem becomes a UI one because you cant disclose the name/ displayname without UV so would have a hard time with a pick list unless the user sets up a PIN. Unless you special case the display list from inside the authenticator vs the platform.

**Comment by maxhata** [comment]
> ...... but if UV isn't set up we'll make a non-RK credential.

I was also under the impression that FIDO2 authenticator cannot be enabled unless you set up screen lock with UV.

**Comment by agl** [comment]
> If there is no pin or uv provisioned then you can make with rk=true and it will work.

I'm assuming that discoverable credentials are only useful when they can provide two factors in themselves. The non-UV, empty-allow-list flow is already something that Chrome doesn't support. Thus creating a discoverable credential without UV doesn't seem useful on the web.

From that point, the question that Christiaan is raising is how hard we should push to create a discoverable credential. If there's variation on this point between user agents then that's going to be a little weird for RPs so, if we can agree and stick a note in the spec, so much the better.

**Comment by ve7jtb** [comment]
@akshayku should comment.  Microsoft had some use cases uv less resident credentials.  It was talked about as tap and go. 
I don't know how relevant they are to the web.  Classic Edge did support that.

**Comment by sbweeden** [comment]
> i) We’ll always create a resident key, even if we have to guide the user in setting up a PIN first.
> ii) If internal-UV or a PIN is already configured, we’ll prompt for a PIN / do UV and, if successful, create a resident key.

As an RP stakeholder, +1 for option (i)

**Comment by Kieun** [comment]
> I'd like to vote that we do (i) where possible, and on devices (such as phones where we can't guide the user through PIN setup today) we do (ii), but with the intent to move to (i) in the long run.

Is this about Android devices? Old devices can't guide screen lock setup and new devices can do?
AFAIK, Android has a API to prompt a user to setup screen lock.

**Comment by agl** [comment]
> Is this about Android devices?

It's a question about external authentications for now since Android does not yet support discoverable credentials. The behaviour on Android would also be out of the control of the browser since it's not the browser driving PIN set up on Android.

> I'm assuming that discoverable credentials are only useful when they can provide two factors in themselves.

Another factor to consider is that sites switching from the traditional, U2F-style flow, to one based on discoverable credentials, would presumably still be setting uv=discouraged in the `create` call because, for user-agents that are still on WebAuthn level one, they still want the old behaviour. Thus the suggestion (i) in the first message would mean that rk=preferred also overrides the uv specification — which is fine, but also something that I think we should pin down.

**Comment by christiaanbrand** [comment]
I already spoke to Akshay (he can chime in himself too), but he also votes for option (i). 

> Thus the suggestion (i) in the first message would mean that rk=preferred also overrides the uv specification — which is fine, but also something that I think we should pin down.

agl, override it to what exactly?

**Comment by akshayku** [comment]
> Microsoft had some use cases uv less resident credentials. It was talked about as tap and go.
I don't know how relevant they are to the web. Classic Edge did support that.

We create resident credential with `credProtect` level 1 and `uvRequired`. Such a credential can do Tap and Go in non-web scenarios and 2FA scenarios on the web. 

- For Simple roaming authenticators with ClientPIN with/without internal UV. 
    - clientPIN is a requirement to set internal UV.
    - If either form of user verification is setup, platform will use that. 
    - If nothing is setup, Windows guides user to create a clientPIN for external devices if uv option is preferred or required. If UV is discouraged, we don't setup clientPIN. But we still create a resident key.

- Platform Authenticators
    - On platform webauthn
      - If no user verification is setup, I was assuming platform authenticator is not present in that case and IUVPAA will return false. @christiaanbrand, Are you saying that webauthn is always present on Android and in that case, you will be making non-resident keys? 
        - This is different from Windows, where user has to enable Windows Hello explicitly. 

    - Roaming scenario (Phone as roaming authenticator). 
      - For Phone like roaming authenticators, who does not support clientPIN and who can do all internal UV itself, if they have uv configured, we will try to create a resident credential with that internal UV for "Preferred" option. If they don't, we as of today still try to create resident keys. 


Seems like we need to write down all the combinations between ResidentKeyRequirement and UserVerificationRequirement

**Comment by agl** [comment]
> agl, override it to what exactly?

uv=discouraged, rk=preferred would, if discoverable credentials can be created on the selected authenticator, be treated like uv=required, rk=required. That way a site can register either a 2FA credential (if discoverable credentials are available), or a discoverable credential with UV.

For tap-and-go, Akshay wouldn't be setting rk=preferred because that's an rk=required case.
