### ISSUE TITLE
How to use WebAuth with caBLE?

### ISSUE THREAD

**Issue by SilentImp** [w3c/webauthn#1490]
Hi.
Did anyone manage to use caBLE with WebAuth?
Is there any information how to do it?
I am thinking about this use case: https://w3c.github.io/webauthn/#sctn-usecase-authentication
And I see that we have caBLE v2 in Chrome.
But it’s next to zero information about this use case.
![Screen Shot 2020-10-05 at 09 36 17](https://user-images.githubusercontent.com/217308/95055159-302ce400-06f3-11eb-8e1c-de3c977a8793.png)

I am thinking if it is possible at all to use phones fingerprint/faceid sensors for sign in on laptop.
Regards. Anton.

**Comment by nicksteele** [comment]
Hi Anton, I believe CaBLE (v2) is still in active development and I don't know of a Google-made mobile app that supports it as of yet, aside from being only available in Chrome at the moment, it is meant to be used with the WebAuthn API in browsers rather than with the client device's OS. I'm not saying it is _impossible_ but I don't think it would be very useable given the current state of the transport.

**Comment by nuno0529** [comment]
@SilentImp I think you can get somethings by searching relative information on https://groups.google.com/a/fidoalliance.org/g/fido-dev

**Comment by SilentImp** [comment]
Thanks. So for now it's not something ready to play with.
