### ISSUE TITLE
Note to encourage storage of registered credential details

### ISSUE THREAD

**Issue by Firstyear** [w3c/webauthn#1556]
during registration today, there are a number of parameters related to the credential that *could* be stored for future verification and policy assertion, but it has been up to RP implementors to interpret and discover this. A note should exist in registration that encourages the storage of:

* uv bit
* attestation data (if performed) so that the model/transport of the credential is known
* extension data

This allows RP's to then extend the authentication ceremony such that a credential known to set a uv bit in registration with "preferred" can have the next authentication performed with "userVerification required" as it is know it can provide that. Similar, this data can be used for validation of other credential properties that may matter to policy for RP's. 

By having a note encouraging this, this allows RP's to understand that this is how certain policies can be implemented. 

Similar notes should exist around authenticatorAttachement that these are *hints* to the client on how to work with the authenticator and are not the foundation of security policy - it is based on the credential used and the RP's knowledge of that credential from registartion to enforce any policy.

**Comment by lgarron** [comment]
Is it possible to make this easier for RPs to do correctly, by having the API return a single/field object with all the stuff you "should" store?

To some extent, saving the attestation data used to be a sufficiently effective way to store "stuff you might need later". But I imagine that many RPs will not realize they should have stored more info, unless it is the simple path. Given that the extension data is not returned by default (although [we always ask for it](https://github.com/github/webauthn-json)), it seems very easy to overlook. Bundling it with the attestation data/UV bit/anything else important into an "attestation++" object would make this more ergonomic.

**Comment by dwaite** [comment]
The other way of thinking about this is that you have your credential creation request and response, and you are choosing what information _not_ to save.

Sure, the request message you sent or the client credential data in the response might be something you won't use normally at runtime, but if you save them you can re-run your security evaluation on the initial credential registration at any point in the future, such as after a security fix or change to your attestation policy.

Once you decide to pick and choose what data you save, there aren't a lot of values that MUST be saved across all the different kinds of implementations. In fact, I believe a limited functionality implementation only MUST save the public key, although you would probably still _want_ to save the credential handle with it.

Trying to define what information people SHOULD save would likely require defining use cases that go along with that recommendation. We may also wish to extend such recommendations to extensions, and suggest any third party extension also give such guidance.

**Comment by Firstyear** [comment]
I think that having the object with things you should store sounds like the best solution here. This way the RP can store "everything" they *might* need so that if in the future they change internal policy and require extra data, they can do so retroactively without breaking older tokens etc.

**Comment by akshayku** [comment]
Isn't the makecredential response that thing?

**Comment by equalsJeffH** [comment]
sounds to me like something for the webauthn adoption community group to discuss?

**Comment by lgarron** [comment]
> Isn't the makecredential response that thing?

I guess so, but I don't recall seeing any advice suggesting to save it directly.

Also, for some databases it's a lot nicer to save a flat JSON object (i.e. to support the most basic form of indexing for NoSQL). In that case, the "obvious" choice might be to save `response` field directly rather than the entire result, if you don't know to be on the lookout for extension info or potential future fields.

**Comment by MasterKale** [comment]
This is something I'm tackling right now in my library. A user raised an issue requesting additional information out of attestation verification so that they could more closely design their RP around [Yubico's developer guide](https://developers.yubico.com/WebAuthn/WebAuthn_Developer_Guide/Registering_Multiple_Devices.html), which encourages the "credentials" table to store the following information:

![image](https://user-images.githubusercontent.com/5166470/106833621-b0833780-6648-11eb-961e-a7b629471f52.png)

So there's at least something out in the wild taking an opinionated stance on what information out of an attestation is/might be useful for future-proofing an RP as utilization of WebAuthn grows and the spec evolves.

> sounds to me like something for the webauthn adoption community group to discuss?

This guide seems like a reasonable starting point for the WACG to have this conversation considering everything except the last three are things that can be extracted from an attestation and stored fairly easily (`metadata` is how they track things like authenticator attachment, "form factor", OS, etc...). Unless someone beats me to it I can bring it up at our next meeting on 2/8.

**Comment by Firstyear** [comment]
> So there's at least something out in the wild taking an opinionated stance on what information out of an attestation is/might be useful for future-proofing an RP as utilization of WebAuthn grows and the spec evolves.
> 

I think this is a good summary of it. Webauthn does not exist in a vacuum, it will be used in a variety of new and different scenarios and methods. Having the standard correctly show what can and can not be used to develop security and account policy in various ways will help to ensure that implementors are "holding it correctly".

**Comment by Firstyear** [comment]
At this point should I put forward draft wording for review?

**Comment by emlun** [comment]
Sorry for leaving this hanging. Is this now resolved by PR #1773?

**Comment by Firstyear** [comment]
Yes I think so :)
