### ISSUE TITLE
Allow RP to determine correct Platform Authenticator name

### ISSUE THREAD

**Issue by FlxMgdnz** [w3c/webauthn#1563]
When implementing WebAuthn/FIDO2 for larger end-user focused deployments, we're always struggling with the correct naming of the actions that are presented to the users.

Allowing the RP to display the specific platform authenticator name would help UX a lot, e.g., "Use Touch ID" or "Set up Windows Hello". For this to work properly, there needs to be a reliable way for the RP to determine the correct name on the platform. It could be very simple, something like "userVerifyingPlatformAuthenticatorName" always returning a string like "Touch ID", "Face ID", "Windows Hello", defined by the platform.

Revisiting #1304 , we would strongly encourage further developments here.

**Comment by lgarron** [comment]
For what it's worth, we've tried to work around this at GitHub, and... we have no clever ideas. Saying "your device's login screen" or "your built-in authenticator" is somewhat accurate, but the spec doesn't guarantee anything about the how much of the implementation is shared with the device's login auth, and those phrases are not nearly as natural as "use Face ID" or "use Windows Hello".

I know the spec has been designed to be extremely wary of privacy leaks, but some privacy-sensitive decisions present significant barriers to adoption. And e.g. when it comes to leaking user registrations info, I believe that cuation is warranted.

However, revealing the kind of authenticator available (e.g. in an extended version of `isUserVerifyingAuthenticatorAvailable()`) is fairly low-entropy. While it is "yet another fingerprint", it can be designed to leak almost no additional entropy to user agent + [screen size](https://developer.mozilla.org/en-US/docs/Web/API/Screen/width).

From another angle, I understand that some browser may not wish to have sites display the authenticator name if they cannot control the branding used by the site. I think the W3C should decide whether this is a good enough reason, and make it clear if this is the actual overriding concern.

**Comment by dwaite** [comment]
A number of use cases for the RP understanding the current platform authenticator name before authentication overlap heavily with the alternative of supporting non-modal browser/platform UI #1545 .

**Comment by nicksteele** [comment]
There seems to be a lot of issues lately regarding identifying authenticators ahead of time, which is truly a hard issue. The big reason why we don't allow for easy identification of available authenticators is because we, as Lucas mentioned, want to allow users to not be fingerprinted via their authenticator and only be identified when they choose to share that information. It is possible (although not totally reliable) to use other heuristics alongside the `isUserVerifyingAuthenticatorAvailable()` method to try and determine a user's client and client device, but perhaps we could do better on this. 

I would recommend we discuss this in the adoption community group (if you're available to discuss as well @lgarron that would be great) and we can potentially figure out a privacy-preserving solution there for publication within the W3C spec. Maybe the solution is to submit a PR asking for a similar method to `isUserVerifyingAuthenticatorAvailable()` that gives us further hints about the available authenticator. 

Closing this issue and moving it to discussion in [issue #6](https://github.com/webauthn-adoption/practical-webauthn/issues/6) in the community group.
