### ISSUE TITLE
Make signature counters a MAY ?

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#1590]
Signature Counter section says:
> Authenticators SHOULD implement a signature counter feature.

However, we're not aware that anyone has ever gotten any utility from them.  (sez @agl)

in WebAuthn L3 we perhaps ought to update that section to downgrade it to a MAY and/or bluntly add the above statement.

**Comment by akshayku** [comment]
We have in possible replay attacks.

**Comment by rlin1** [comment]
We do as well.

**Comment by maxhata** [comment]
To prevent replay attacks, signature counters SHOULD be implemented.

**Comment by herrjemand** [comment]
Authenticator already can optionally not-implement counter(with a good justification) for L1. There is no excuse for servers to not to support them.

**Comment by kreichgauer** [comment]
The stated purpose of signature counters is to detect cloned authenticators, not to prevent replay attacks. (https://w3c.github.io/webauthn/#sctn-sign-counter)

**Comment by Firstyear** [comment]
If anything the language around counter handling could be tightened up. For example 

> This is a signal that the authenticator may be cloned, i.e. at least two copies of the credential private key may exist and are being used in parallel. Relying Parties should incorporate this information into their risk scoring. Whether the Relying Party updates storedSignCount in this case, or not, or fails the authentication ceremony or not, is Relying Party-specific.

Here, the risk is that people may store the sign count in the situation it has stepped backwards. The greater risk is that when signCount < storedSignCount, if the signCount was tampered with and set to 0, and the RP then persisted that then there is a risk that counter may not be checked again in the future. 

I think if anything, the language in this section could be improved to state that it is *not* recommended to store a sign count when it goes backwards. But the signCount is a useful check.

**Comment by herrjemand** [comment]
@Firstyear Counter must always go UP. Server should reject the assertion if counter has not increased(excluding when counter is always 0)

**Comment by ve7jtb** [comment]
Severs need to support counters for authenticators that implement them.

We may need to clean up the language for the servers so that they don't allow the counter to be reset to 0.  Though I always anticipated that if the counter is 10 and the server gets the next assertion with a counter of 0 that the credential would be invalidated and the new counter not stored.   

The counter may not be a perfect detector of cloning but is the best we have.
The challenge should be used to detect replay not the counter.

**Comment by bdewater** [comment]
As side-channel attacks are discovered it seems "getting utility from counters" is only a matter of time? E.g.
- https://tpm.fail/ recovering private keys from Intel fTPMs and STMicroelectronics TPM chips
- [Google Titan keys can be cloned](https://arstechnica.com/information-technology/2021/01/hackers-can-clone-google-titan-2fa-keys-using-a-side-channel-in-nxp-chips/)

**Comment by Firstyear** [comment]
> @Firstyear Counter must always go UP. Server should reject the assertion if counter has not increased(excluding when counter is always 0)

Yes, when the counter is working correctly. But in a replay attack, or cloned authenticator when it steps backwards, because the webauthn spec uses this statement on the matter:

> Whether the Relying Party updates storedSignCount in this case, or not, or fails the authentication ceremony or not, is Relying Party-specific.

It means people may implement this incorrectly. As a standard, there should be clear, unambiguous language about how an RP should handle this situation, because if there is not, people can and will implement it incorrectly.

**Comment by equalsJeffH** [comment]
on 7-apr-2021 call:
@agl notes that we do not have consensus on this
@nicksteele: the 3 libs he's worked on will raise a flag that the counters do not line up, but will not reject the authn operation
@akshayku: windows  will reject the authn op if counter not incremented
@nicksteele: also, system he's working on uses risk-based assessments of which the signature counter is only one input

bottom line is that rather than change the SHOULD to a MAY, this discussion is more appropriate for those bodies involved in certification of authenticators and fido servers (e.g., FIDO)

**Comment by cyberphone** [comment]
Although supporting de-facto standard payment authorization schemes like EMV/Apple Pay has not been considered by the W3C/FIDO community, signature counters fill a nice role here by adding entropy to such authorizations since these do not use challenge/response protocols. Entropy + Unique request and user data + Locally generated time stamps are thus required in order to handle replays of authorizations in a secure and convenient way. 

**That is, please keep the SHOULD!**

Fun fact: In contrast to authentication, replay in authorization based schemes may actually be a "feature". By enabling _idempotent operation_, retransmissions occurring due to network glitches etc., return the same result data without any internal state changes, potentially adding robustness to payment ecosystems .
