### ISSUE TITLE
"The user handle MUST NOT be empty, though it MAY be null" - but only in responses?

### ISSUE THREAD

**Issue by emlun** [w3c/webauthn#1598]
In [§5.4.3 User Account Parameters for Credential Generation (dictionary PublicKeyCredentialUserEntity)](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#dom-publickeycredentialuserentity-id), the description of the `id` attribute reads:

>[...] The user handle MUST NOT be empty, though it MAY be null.

However the definition of the same attribute marks it `required`, and Chrome 89 returns an error if you attempt to set it to null in a `navigator.credentials.create()` call.

I think this was supposed to mean that the user handle _parameter_ [`publicKey.user.id`](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#dom-publickeycredentialuserentity-id) MUST NOT be empty and MUST NOT be null, but the user handle _return value_ [`PublicKeyCredential.response.userHandle`](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#dom-authenticatorassertionresponse-userhandle) MAY be null (for example when using a U2F authenticator or a non-discoverable credential). Is that right?

**Comment by MasterKale** [comment]
The thought came to me that, during attestation, if `user.id` is null while `authenticatorSelection.residentKey` is set to `"required"`, [`authenticatorMakeCredential`](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#sctn-op-make-cred) may fail in step 7.4.4 when the authenticator attempts to store `credentialSource` in `rp.id, userHandle`:

> 4. If requireResidentKey is true or the authenticator chooses to create a client-side discoverable public key credential source:
>     1. Let credentialId be a new credential id.
>     2. Set credentialSource.id to credentialId.
>     3. Let credentials be this authenticator’s credentials map.
>     4. **Set credentials[(rpEntity.id, userHandle)] to credentialSource.**

Is this a legitimate issue if `user.id` is allowed to remain nullable?

**Comment by equalsJeffH** [comment]
on 21-Apr-2021 call:
for background, see PR #1537 (issue #1536)
@agl notes that next week we can decide what the change is - web authn or chrome
@MasterKale will make a further comment here.

@emlun will summarize the conclusion we reached on the call.

**Comment by emlun** [comment]
2021-04-21 call:

The "though it MAY be null" was added in PR #1537. As we understand the WebIDL, the definition `required BufferSource   id;` is not _nullable_ - so null is indeed not a valid value for the `user.id` parameter, and "though it MAY be null" contradicts this. Also the authenticator model's credential-overwriting behaviour assumes it is non-null (like @MasterKale points out above).

So we could already conclude that "though it MAY be null" should be dropped or clarified.

**Comment by equalsJeffH** [comment]
@emlun wrote:
> >[...] The user handle MUST NOT be empty, though it MAY be null.

> I think this was supposed to mean that the user handle _parameter_ [`publicKey.user.id`](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#dom-publickeycredentialuserentity-id) MUST NOT be empty and MUST NOT be null, but the user handle _return value_ [`PublicKeyCredential.response.userHandle`](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#dom-authenticatorassertionresponse-userhandle) MAY be null (for example when using a U2F authenticator or a non-discoverable credential). Is that right?

I do not think the above was the original intent.   

AFAICT the user handle parameter [`publicKey.user.id`](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#dom-publickeycredentialuserentity-id) _**is** used for only credential creation_, and the "...though it MAY be null" clause is simply incorrect (I do not recall why I/we stated that, doh), because  it is a [BufferSource](https://heycam.github.io/webidl/#BufferSource) type which is a union containing other nullable webIDL types and thus is not itself nullable (If I'm reading  the WebIDL spec correctly).

Perhaps we can resolve this issue by simply deleting the text ", though it MAY be null".

[ WRT the user handle _return value_ [`PublicKeyCredential.response.userHandle`](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#dom-authenticatorassertionresponse-userhandle) possibly being null:  yes, the spec explicitly declares that as a nullable ArrayBuffer. ]
