### ISSUE TITLE
Updating IANA WebAuthn Registries for Level 2

### ISSUE THREAD

**Issue by infinisil** [w3c/webauthn#1694]
The [IANA WebAuthn registries](https://www.iana.org/assignments/webauthn/webauthn.xhtml) are currently still at the state of [WebAuthn Level 1](https://www.w3.org/TR/webauthn-1/). Now that [WebAuthn Level 2](https://www.w3.org/TR/webauthn-2/) is a W3C recommendation, when is the IANA registry going to be updated [accordingly](https://www.w3.org/TR/webauthn-2/#sctn-IANA)?

Ping @selfissued @equalsJeffH

**Comment by equalsJeffH** [comment]
Thanks @selfissued !

Hm, we do not have a milestone for such housekeeping tasks, perhaps we should create a milestone for this task (ie not use the L3-WD-01 milestone) such that this issue is at least "triaged".  or maybe Tony would want to leave it as "untriaged" such that it gets reviewed amongst other untriaged issues during meetings.

**Comment by selfissued** [comment]
I submitted the registration request to IANA.  It was acknowledged as request [IANA #1225800].

**Comment by selfissued** [comment]
And FYI, the corresponding CTAP 2.1 registrations for the values at https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#sctn-IANA have been acknowledged as [IANA #1225801].

**Comment by infinisil** [comment]
I see that the registry has been updated, thanks @selfissued (and IANA)!
