### ISSUE TITLE
Can userHandle be an empty string?

### ISSUE THREAD

**Issue by infinisil** [w3c/webauthn#1722]
The specification on [`userHandle`](https://www.w3.org/TR/webauthn-2/#dom-authenticatorassertionresponse-userhandle) only mentions that it can be null, it doesn't mention whether the empty string is an allowed value:

> `userHandle`, of type [ArrayBuffer](https://heycam.github.io/webidl/#idl-ArrayBuffer), readonly, nullable: This attribute contains the [user handle](https://www.w3.org/TR/webauthn-2/#user-handle) returned from the authenticator, or null if the authenticator did not return a [user handle](https://www.w3.org/TR/webauthn-2/#user-handle). See [§ 6.3.3 The authenticatorGetAssertion Operation](https://www.w3.org/TR/webauthn-2/#sctn-op-get-assertion).

In the reference to [user handle](https://www.w3.org/TR/webauthn-2/#user-handle) there's also no mention regarding empty strings, but there's this:

> The user handle is specified by a [Relying Party](https://www.w3.org/TR/webauthn-2/#relying-party), as the value of [user](https://www.w3.org/TR/webauthn-2/#dom-publickeycredentialcreationoptions-user).[id](https://www.w3.org/TR/webauthn-2/#dom-publickeycredentialuserentity-id)

Where the specification for [id](https://www.w3.org/TR/webauthn-2/#dom-publickeycredentialuserentity-id) mentions:

> The [user handle](https://www.w3.org/TR/webauthn-2/#user-handle) MUST NOT contain personally identifying information about the user, such as a username or e-mail address; see [§ 14.6.1 User Handle Contents](https://www.w3.org/TR/webauthn-2/#sctn-user-handle-privacy) for details. The [user handle](https://www.w3.org/TR/webauthn-2/#user-handle) MUST NOT be empty, though it MAY be null.

This is the only mention in the specification disallowing empty values for user handle, but it's very hard to find, and non-obvious whether it actually applies to user handles (does `The user handle is specified by a Relying Party as the value of user.id` mean that only values of `user.id` are valid as a user handle?).

In practice, Safari indeed returns the empty string as a user handle, see https://bugs.webkit.org/show_bug.cgi?id=239737 and https://github.com/tweag/webauthn/pull/148.

**Comment by lgarron** [comment]
Using `""` has certainly come up before, but it's still unclear how widely an RP can expect that to be supported: https://github.com/w3c/webauthn/issues/1283

**Comment by agl** [comment]
The user handle is set by an RP when creating a discoverable credential so that they can identity that user in future assertion requests with an empty allowList. There was historically ambiguity about whether an empty user handle was valid and implementations differ in whether they support them. Thus empty user handles were disallowed and RPs must not set `user.id` to a non-null, but empty, value when creating credentials. This ensures that RPs work for all authenticators.

In terms of whether the [returned user handle](https://www.w3.org/TR/webauthn-2/#dom-authenticatorassertionresponse-userhandle) in an assertion can be empty: I think it validly _can_ be empty if the authenticator returned an empty value. For a given RP, if they never created credentials with empty user handles, then they should never see empty values however.

Looking at your Safari bug: indeed, Safari returns an empty user handle in an assertion even with U2F authenticators. U2F authenticators obviously never return any user handles so Safari is mapping that to the empty string rather than null. I think that's wrong per [the spec](https://www.w3.org/TR/webauthn-2/#dom-authenticatorassertionresponse-userhandle).

**Comment by emlun** [comment]
WG 2022-05-18 call: Seems there's nothing more to discuss here, closing.
