### ISSUE TITLE
Drop generic client extension processing?

### ISSUE THREAD

**Issue by emlun** [w3c/webauthn#1730]
This discussion came up in PR #1703. Currently, [§9. WebAuthn Extensions](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#sctn-extensions) states:

>[...]
>Clients wishing to support the widest possible range of extensions MAY choose to pass through any extensions that they do not recognize to authenticators, generating the [authenticator extension input](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#authenticator-extension-input) by simply encoding the [client extension input](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#client-extension-input) in CBOR. [...]

and as such for the spec to be internally consistent, it would be expected that all other parts of the spec should be compatible with this provision.

#1703 proposes adding utilities for decoding [`PublicKeyCredentialCreationOptions`](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#dictdef-publickeycredentialcreationoptions) and [`PublicKeyCredentialRequestOptions`](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#dictdef-publickeycredentialrequestoptions) objects from JSON, so RPs don't need to reach deep into the data structures to convert binary values from textual representations before passing them into `navigator.credentials.create()` and `.get()`.

Unfortunately, this seems to be [incompatible with the generic extension pass-through provision](https://github.com/w3c/webauthn/pull/1703#discussion_r845941977), since for unknown extensions there's no way for the client to know which extension input values need to be converted to `BufferSource` values, and JSON has no standardized way to flag binary values. In practice all clients represented in the working group have chosen to not implement generic extension pass-through, so we're opening for discussion:

**Should we keep the generic extension pass-through, or drop it in L3?**

**Comment by MasterKale** [comment]
The py_webauthn project recently received a PR to add in [support for the `credProtect` extension](https://github.com/duo-labs/py_webauthn/pull/128). I initially declined to land it, but after @emlun's comments in #1703 that _technically_ there's nothing preventing us from passing through unrecognized extensions, I reconsidered and currently plan on allowing it at some point.

I still think I'd selfishly want the WebAuthn spec to only think about extensions it specifically chooses to define. It seems too burdensome, from a spec maintenance perspective, to define a small handful of extensions and then simultaneously mandate that future WebAuthn functionality proposals consider _all_ possible extensions and be blocked when they don't. How are we expected to track when new extensions come out, if they don't get funneled through this repo? I suppose that's why we have the IANA registry, but [looking at the current list](https://www.iana.org/assignments/webauthn/webauthn.xhtml) of defined WebAuthn extensions there are many still in there that I thought were dropped from L2.

I think this issue is a good one, guidance one way or another would be good for us to specify.

**Comment by Firstyear** [comment]
I've had a different experience as part of webauthn-rs, where I haven't found any instances of the extensions being supported from https://www.w3.org/TR/webauthn-3/#sctn-defined-extensions other than crepProps (which is a joke anyway since it's not signed and is open to manipulation).

So I think dropping it is fair game, because at least that lets the RP know "they didn't respond at all because they don't support it". rather than the confusing situation we have now.

**Comment by sbweeden** [comment]
> crepProps (which is a joke anyway since it's not signed and is open to manipulation).

FWIW [credProps](https://www.w3.org/TR/webauthn-3/#sctn-authenticator-credential-properties-extension) is a client registration extension, generated by the client *after* the ceremony with the authenticator, and therefore cannot be signed. It is not meant to be proof of anything. It is designed to be a signal to RPs of what the client actually ended up using in its registration ceremony with the authenticator and is specifically designed to help in cases when [residentKey](https://www.w3.org/TR/webauthn-3/#dom-authenticatorselectioncriteria-residentkey) is set to preferred. It was envisioned this would help the RP decide what use cases the credential might be used for in future (username-less flow or 2FA only) and allow the RP to offer guidance to the user on same.

**Comment by Firstyear** [comment]
Except because it's not signed you can't use it to trust that an rk was created because the client can lie and tamper with that meaning you can't use it to assert that a usernameless or 2fa only flow can be used .... 

If it's not meant to be proof of anything, why does it exist, and use language that makes it sound like a proof? It's fully misleading and RP's will absolutely incorrectly rely on this value.

**Comment by emlun** [comment]
Closed by #1737.

**Comment by emlun** [comment]
> Except because [`credProps`] is not signed you can't use it to trust that an rk was created because the client can lie and tamper with that meaning you can't use it to assert that a usernameless or 2fa only flow can be used ....
> 
> If it's not meant to be proof of anything, why does it exist, and use language that makes it sound like a proof? It's fully misleading and RP's will absolutely incorrectly rely on this value.

It exists in part because CTAP2 doesn't have a way to signal whether the created credential is discoverable or not, so the best effort we can manage for those existing authenticators is to have the client report what parameter it sent to the authenticator. If the client lies about the `credProps` output, it will only harm the user that the client is supposed to be working for, which is why it is deemed acceptable that the output is unsigned.

**Comment by joshzhao** [comment]
> Is generic extension pass-through getting much usage, if any? Could be worth dropping. Alternatively, I believe the solution you outlined in the [#1703](https://github.com/w3c/webauthn/pull/1703) discussion is a fair workaround to consider.

When all the client browsers are dropping these unknown extensions, it is unlikely that such lesser-known extensions will get any usage. That's precisely why we need to have pass-through of extensions meant for endpoints on intermediaries so as to facilitate experimentations with extensions of the protocol.
