### ISSUE TITLE
Seperate defined extensions by client and authenticator extensions.

### ISSUE THREAD

**Issue by Firstyear** [w3c/webauthn#1760]
Section 10, has a list of defined extensions. To aid clarity for RP's who wish to know which are client or authenticator, this could be re-arranged so that there is a client and authenticator subsection. An example of why this is an improvement is that currently it is "a detail" of the extension to if it is client or authenticator, and it's easy to overlook leading to implementor confusion (e.g. why is credProps not appearing in my authenticator extensions output.)

**Comment by Kieun** [comment]
See related issue. #1258

**Comment by emlun** [comment]
This seems like a fair change. [§9. WebAuthn Extensions](https://w3c.github.io/webauthn/#sctn-extensions) does set up the difference as one of the defining properties of an extension:

>Every extension is a **client extension**, meaning that the extension involves communication with and processing by the client.
>[...]
>An extension can also be an **authenticator extension**, meaning that the extension involves communication with and processing by the authenticator.

It's not a dichotomy of separate categories, rather a subcategory and its supercategory, but it still seems fair to place the authenticator extensions separate from those that are purely client extensions. Especially since only authenticator extensions are signed.

**Comment by Firstyear** [comment]
Today I learnt that they are a *subcategory*. I had never realised that before this point ..... :| 

Still, separating them should be pretty easy I think. I'll put in a PR. :)

**Comment by emlun** [comment]
This issue re-appeared when #1732 was merged.
