### ISSUE TITLE
Is there a way to store user secret key in the authenticator with/without an extension?

### ISSUE THREAD

**Issue by KuznetsovNikita** [w3c/webauthn#1818]
The webAuthn will be very useful if developers could have an option to store and get user secret key, from my perspective.

As I understand the developers have a few options:

1) [`user.id` aka `userHandle`](https://w3c.github.io/webauthn/#user-handle) with is supported for most of the authenticator.

2) The ["small blob" extension](https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#sctn-credBlob-extension) with is not supported well in nowadays.

3) The ["large blob" extension](https://www.w3.org/TR/webauthn-2/#sctn-large-blob-extension) with is an experimental feature in nowadays. 

As I understand the value for `user.id` aka `userHandle` is stored in the authenticator, but means non sensitive data and used for technical reason.  

Why I should not store user secret in the `user.id` aka `userHandle`? 
Is it possible to get a list of `user.ids` from authenticator programmatically?
Is it possible some how hack and get this value from authenticator? 
Is the hack required physical contact with authenticator or could it be done programmatically? 

Thank you in advance!

**Comment by timcappalli** [comment]
Hi! Please use [FIDO-DEV](https://groups.google.com/a/fidoalliance.org/g/fido-dev?pli=1) for implementation questions/discussions.

![Screenshot_20221022-072220.png](https://user-images.githubusercontent.com/6476604/197344345-cce70c1e-0209-41ff-8dcd-61fb9157453b.png)

**Comment by emlun** [comment]
On the WebAuthn layer, the small and large blob extensions are indeed the only way to store a chosen value. As you note you could technically abuse `user.id` for this as well, but that is strongly discouraged because authenticators and client platforms make assumptions about what it's used for and do not treat it as sensitive.

If a random but deterministically derived value is sufficient - for example, to use as key derivation material rather than a finished key - there is the [`prf` extension](https://w3c.github.io/webauthn/#prf-extension), though I don't think there are any client implementations available yet.

**Comment by emlun** [comment]
Closing this, please let us know if there's discussion left to have here.
