### ISSUE TITLE
Provide a way for an RP to set an intention to offer more user friendly UX

### ISSUE THREAD

**Issue by Kieun** [w3c/webauthn#1823]
## Description
Depending on the RP's user scenario, RP might leverage Webauthn credentials for sign-in (bootstrap or re-authentication), step-up authentication, transaction confirmation or even others.
Because there is no way for an RP to customize UI (especially, Webauthn modal title and its contents), most of current browsers and platforms implementations exposes **Signin** phrase even if the explicit use case is not the **Signin**.

If there is any parameters to set an intension or a text to indicate the context, the UX would be more user friendly.

If it is hard to handle internationalization on the platform side, we can define a list of "intentions" in the spec, and the RP sets the most appropriate intention from the list and set it within the get options.
Then, browsers and platforms exposes an **appropriate phrase** rather than just **Signin**.

Similarly, when creating a Webauthn credential, we could provide similar features to indicate the list of intension (use cases) within the create options.

But, I'm thinking that providing such feature for get options is more critical.

**Comment by enricobottazzi** [comment]
I totally support this! I think that the scope of webauthn can be way larger if this UX feature is implemented. I suggest looking into this article related [EIP 712 in crypto wallets](https://medium.com/metamask/eip712-is-coming-what-to-expect-and-how-to-use-it-bb92fd1a7a26) to kick off the discussion.

The origin of this Improvement Proposal was to create a friendly and secure UX for user to sign arbitrary data.

**Comment by timcappalli** [comment]
> I think that the scope of webauthn can be way larger

There is no current intention to expand the scope of WebAuthn. WebAuthn is designed to allow a website to sign a user in using a strong, phishing resistant public key credential, and it does that very well. Signing arbitrary data could actually harm some of the security and privacy properties of the FIDO2/WebAuthn stack.

**Comment by nicksteele** [comment]
During this week's call @emlun called out the possibility of assigning an enum that could have different prompt phrases for the RP to use. While this is probably not the optimal solution here (could produce CTAP related obstacles) I would like to leave this ticket open for a bit to discuss possible solutions for this UX issue.

**Comment by emlun** [comment]
@agl noted on the call that Chrome leans more toward making the wording more generic rather than introducing a new parameter, for reasons including those @nicksteele mentioned.

**Comment by Firstyear** [comment]
> @agl noted on the call that Chrome leans more toward making the wording more generic rather than introducing a new parameter, for reasons including those @nicksteele mentioned.

They have started to add generic wording but it's also confusing in some cases. For example, chrome says "use a passkey on a different device" even if you might be using a yubikey (which some people insist is not a passkey). 

Is it possible we could at least offer some standardised wording so that the various vendors could adopt that makes it clearer across platforms? Even for me who develops a webauthn library this text prompt confused me. 

I think something like "Use a passkey or security key" or "Use a passkey", or even "use a passkey on a different device or a security key". 

<img width="537" alt="Screen Shot 2022-12-14 at 14 46 37" src="https://user-images.githubusercontent.com/271005/207993271-46f913cc-fe31-4fd5-b9c0-2fd1880e9eee.png">

**Comment by dwaite** [comment]
> For example, chrome says "use a passkey on a different device" even if you might be using a yubikey (which some people insist is not a passkey).

Passkeys are not authenticators, they are the discoverable webauthn credentials. 

This wording is perhaps a bit technically incorrect because there is no encouraged common backup-capable and non-backup-capable term (instead it is just passkeys and single-device passkeys).

**Comment by Firstyear** [comment]
> This wording is perhaps a bit technically incorrect because there is no encouraged common backup-capable and non-backup-capable term (instead it is just passkeys and single-device passkeys).

And yet, even with your definition then this prompt on chrome is still wrong because I can use a security key here in this prompt area. 

I think the lack of concrete definitions here is a problem, and one where we as a wg could actually take some time to define RP and human friendly terms so that browsers and RP's can use them in their dialogs to create consistent ui/ux

**Comment by nicksteele** [comment]
While we as a working group could definitely work to improve definitions of what a passkey is, what a security key is, etc, in the spec, we have no organization sway over how platform vendors go about designing their UI/IX experience, which goes back to the issues I mentioned above.

**Comment by Kieun** [comment]
@nicksteele I'm thinking that this issue needs to be open to hear further opinion from the RPs

**Comment by timcappalli** [comment]
@Kieun I don't think the spec repo is the right place to solicit RP feedback. This should be done via the FIDO Alliance DWGs or the WebAuthn Community Adoption Group.

**Comment by Kieun** [comment]
I would like to keep this issue open since nothing is resolved and I'm asking for adding some features to indicate RP's intention to the API signature
