### ISSUE TITLE
Being able to access the same public key credentials across different domains

### ISSUE THREAD

**Issue by enricobottazzi** [w3c/webauthn#1827]
## Being able to access the same public key credentials across different domains

Hi everyone, 

the thing that fascinated me the most since I approached Webauthn was the possibility of creating a unified login experience across the internet. The way I designed the webauth experience implies the registration of a domain name together with the public key credential on a public blockchain during the registration. The user can now use the same domain name to authenticate across different websites. The signature verification will be performed against the public key associated with that domain registered on-chain.

Looking into the specs I realized that a public key credential is strictly bound to a https domain via `RP ID` and it seems that the APIs don't expose any way to remove this requirement or extend the RP IDs that can consume a unique public key credential. 

Why did you set this strict requirement as part of the standard? Wouldn't the possibility of reusing the same credential across different websites significantly increase the passwordless user experience?

**Comment by enricobottazzi** [comment]
I understand the concern and I agree with the security issues here. 

Wouldn't the website-specific challenge created during the login ceremony mitigate this risk? a MITM able to capture the signed message generated by the user during the login on `www.good-website.com` wouldn't be able to reuse it to login inside `www.bad-website.com` as the challenge to be signed is different.

Also, given the state of the art of the standard, do you see any way to achieve a "unified login" user experience while preserving the security of the user?

**Comment by herrjemand** [comment]
The credential is locked to the RPID id. RP can manipulate it within the scope of one eTLD example.com, login.example.com, very.long.sub.domain.example.com.

The RPID is fundamental part of FIDO/Webauthn security. The private key is stored as a pair of CredID and RPID hash on the authenticator.

> Wouldn't the website-specific challenge created during the login ceremony mitigate this risk? a MITM able to capture the signed message generated by the user during the login on www.good-website.com wouldn't be able to reuse it to login inside www.bad-website.com as the challenge to be signed is different.

Yes, challenge is part of MITM. Origin/RPID are defending against phishing.

> Also, given the state of the art of the standard, do you see any way to achieve a "unified login" user experience while preserving the security of the user?

FIDO/WebAuthn solves authentication problem. For inter-domain authorization there are OIDC, and if you really have to SAML.

Additionally you can do credential.get through iFrame, so login via iFrame.

**Comment by enricobottazzi** [comment]
Thanks @herrjemand,

> The credential is locked to the RPID id. RP can manipulate it within the scope of one eTLD example.com, login.example.com, very.long.sub.domain.example.com.

Is this performed automatically behind the scene or is there specific parameters that need to be set to allow sub-domain public key credentials persistence?

> FIDO/WebAuthn solves authentication problem. For inter-domain authorization there are OIDC, and if you really have to SAML. Additionally you can do credential.get through iFrame, so login via iFrame.

Thanks, I think I'd opt for iFrame to develop an initial Proof of Concept. Would a browser extension be considered a persistent RPID? 

Btw, thanks for the super fast reply. Such support is not common, and it's an amazing incentive for devs to use this standard.

**Comment by emlun** [comment]
> Why did you set this strict requirement as part of the standard?

It's a critical part of what makes WebAuthn strongly resistant against phishing attacks. Without it, an imposter site could easily trick the user into giving up authentication credentials for any site where they have a WebAuthn credential.

It's also a privacy feature. If you use the same identity everywhere, it's very easy to track you. WebAuthn does not want to make that easier, in fact the standard goes out of its way to prevent leaking information that could de-anonymize users without their consent.

**Comment by enricobottazzi** [comment]
Update on the iframe: I added the iframe as mentioned inside the [standard's iframe guidance](https://www.w3.org/TR/webauthn-2/#sctn-iframe-guidance).

```
      <iframe
        src="https://interplanetary-username-service.vercel.app/"
        width={1000}
        height={500}
        sandbox="allow-scripts allow-forms allow-modals"
        allow="publickey-credentials-get *"
        title="Custom title"
      ></iframe>
```

When trying to perform the `credential.get()` from inside the iframe I get the following error 

```
FAIL DOMException: The current origin is an opaque origin and hence not allowed to access 'PublicKeyCredential' objects.
```

The origin of the call is localhost in this case. Do you have any idea what the problem is?

**Comment by Firstyear** [comment]
@enricobottazzi This is an issue tracker for the specification, not for general developer issues with deploying webauth in production codebases. You should probably move this to a more appropriate forum (https://www.w3.org/community/webauthn-adoption/ )

**Comment by vans163** [comment]
Stumbled onto this problem just now and wondering the same thing. For an organization its useful to be able to have a single key/identity given to a participant in that organization to give access to endpoints, similar to single sign on solutions offered by apple or google.

1. IFrame does not work across combinations of Safari/Apple devices.

2. Easy to track, already we are tracked from just the way we type our sentences. "Easy to track"
So not easy to track should not be considered good security due to obfuscation.  Already the website will
have our IP address we connected from, and metadata on us, also if we use a email during registration or
a name, we probably have to give credit card information on the website etc. Its moot.

There should be an option to generate new keypair OR use the same identity. And it would be up to the
client. Too much is lost by generating a new one each time in terms of security from the organization, and in terms 
of carrying your reputation over. 

3. Phishing attacks point is moot. An impersonation website got you to sign a message, but that message does not have to be arbitrary, for example as mentioned it could include the domain/domains/identity of who the signature is for. Thus a token signed on imposer.com would not be validated on realsite.com. (Obviously the client side inserts the extra data into the blob to be signed)
To elaborate. 

Case A Identity based (non-domain usecase)
realsite.com - Identity ed25519:7emAPGY2AhFz4DpCr7mQonyztttCNDZX3dEgBZnGZKE8
imposter.com - Identity ed22219:EnPujttyRRVhRmmErWNNTw8QoBGgXVmWkFAvnXN882pN

I connect to imposter.com and then ask for its identity + present a challenge. imposter.com signed my challenger and proves they are 7emAPGY2AhFz4DpCr7mQonyztttCNDZX3dEgBZnGZKE8. I then proceed to auth with imposter.com identity embedded into my credential, 7emAPGY2AhFz4DpCr7mQonyztttCNDZX3dEgBZnGZKE8. I sign and give it to imposter.com

imposter.com is now HAHAHAH what a sucker, il login to realsite.com now. imposter.com goes to realsite with the credential and realsite.com says, SORRY this credential was signed for 7emAPGY2AhFz4DpCr7mQonyztttCNDZX3dEgBZnGZKE8 but we are EnPujttyRRVhRmmErWNNTw8QoBGgXVmWkFAvnXN882pN, please sign a new credential specifically for us.

Case B Domain based. Same thing as above but replace the identity with the domain in the URL bar.

**Comment by timcappalli** [comment]
Discussion from the 2022-12-14 meeting:

We are beginning to explore ways to address use cases such as multiple country TLDs (mycompany.de, mycompany.co.uk, etc), mergers and acquisition scenarios, as well non-web scenarios like mobile apps. Both of these require some new thinking about the RP ID. We plan to create a new issue with some thoughts on this topic over the next few months.

**Comment by igorlogvin** [comment]
Hi all! Please, is there any progress on this issue?
