### ISSUE TITLE
Always PRF enabled:false

### ISSUE THREAD

**Issue by kksingla** [w3c/webauthn#1857]
## Problem Statement

Encrypting data using WebAuthn PRF extension, following this [blog](https://blog.millerti.me/2023/01/22/encrypting-data-in-the-browser-using-webauthn/).

Adding Snippet below:
```
async function handleRegister() {
    try {
      regCredentialResult = await window.navigator.credentials.create(cred);
      if (regCredentialResult.response != null) {
        alert("Register Success");
        console.log(regCredentialResult.getClientExtensionResults());
      } else {
        console.log("Reg: null");
      }
    } catch (e) {
      console.log(e);
    }
  }
```
Also, tried multiple settings with virtual authenticator env but always getting the PRF `enabled:false`.

<img width="391" alt="image" src="https://user-images.githubusercontent.com/18482328/220586595-f1720936-3c96-4152-a362-98a0ea3c4fe4.png">

**Comment by arianvp** [comment]
Are you on Chrome Canary? I think the feature is only available on that version of the browser.

Also I don't know if they added it to the virtual authenticator yet.

**Comment by agl** [comment]
I think this is a bug report about a specific browser? Such things should be raised with the browser rather than this, the specification group. But the screenshot looks like Chrome or Edge. In that case, the PRF extension has not been enabled by default yet and requires chrome://flags/#enable-experimental-web-platform-features to be toggled.

Support for PRF is not enabled in the virtual authenticator but can be explicitly requested via the WebDriver interface by specifying that the authenticator should support the `prf` extension.

**Comment by neocybereth** [comment]
is this PRF extension in production chrome now?

**Comment by emlun** [comment]
It's been enabled by default in Chrome for [a little over a year at this point](https://issues.chromium.org/issues/40140659#comment23).

**Comment by tmarkovski** [comment]
As of Chrome Version 128.0.6613.120 (Official Build) (arm64) for MacOS, the PRF extension still returns `enabled: false`.
<img width="219" alt="image" src="https://github.com/user-attachments/assets/aca92d09-9be2-4f4e-a48e-683f4b30947a">

**Comment by MasterKale** [comment]
Hey all, as a reminder browser-specific issues like this one have a better chance of being fixed if you report it in a respective bug tracker instead of here in the WebAuthn spec repo:

- Chrome: https://bugs.chromium.org/p/chromium/issues/wizard
- Firefox: https://bugzilla.mozilla.org/home
- WebKit: https://webkit.org/reporting-bugs/
