### ISSUE TITLE
Return public key in attestedCredentialData on authenticatorGetAssertion

### ISSUE THREAD

**Issue by hariria** [w3c/webauthn#1928]
## Proposed Change

I was curious why the [`attestedCredentialData`](https://www.w3.org/TR/webauthn-2/#attestedcredentialdata) in the [`authenticatorGetAssertion`](https://www.w3.org/TR/webauthn-2/#authenticatorgetassertion) never included the public key of the credential. 

It includes the credential ID, but not the public key, which is arguably much more important for verifying the signature. Is there some way to perhaps force bit `6` of the [`flags`](https://www.w3.org/TR/webauthn-2/#flags) to be true so as to require the public key to be returned in the [Attested credential data](https://www.w3.org/TR/webauthn-2/#attested-credential-data)?

**Comment by timcappalli** [comment]
The server stores the public key (along with the credential ID) after a registration ceremony. There is no need to include it an authentication ceremony as the server has everything it needs to validate the signature.

**Comment by emlun** [comment]
In fact it would be very bad to include the public key along with the assertion signature, because that would create an opportunity for confusing an RP with a valid signature by a different key than the one originally associated with the credential ID. The RP really should retrieve the public key from its own storage, to ensure that the mapping between credential ID and public key remains correct.

**Comment by emlun** [comment]
The WG believes we've answered the question, and there seems to be nothing more to discuss here. Please let us know if there is more to discuss.
