### ISSUE TITLE
Code Injection vulnerability from client side

### ISSUE THREAD

**Issue by AdityaMitra5102** [w3c/webauthn#1965]
## Vulnerability (Code Injection on client side)

Web Authentication might be vulnerable to Self-XSS attacks that allows the adversarial actor to manipulate and use the Public Key Credentials Request Options and get them signed from the authenticators of a legitimate user without physically accessing their device. This can be achieved with a sophisticated attack which comes a Self XSS on the side of the adversarial actor and a trojan running on the side of the legitimate user. This allows the adversarial actor to take over the accounts of the legitimate user remotely. 

Report with working steps to reproduce attached.
[WebAuthn.pdf](https://github.com/w3c/webauthn/files/12640140/WebAuthn.pdf)

+@Anisha100

**Comment by arianvp** [comment]
Could you share the contents of the PDF in the ticket in plain text? I'm a little bit wary downloading random PDFs from the internet.

**Comment by AdityaMitra5102** [comment]
Yeah sure. It was because I used multiple screenshots so I had uploaded it in pdf format.


Web authentication, in the end is a JavaScript API and still follows all the rules of JavaScript. This includes features like Function Overriding. This implies, if we push a custom implementation of the navigator.credentials.get() as a XSS (Cross Site Scripting), it can override the native implementation of the same function and the WebAuthn calls will not function as it is supposed to. This can be verified by simply entering the following code into the console window before making a WebAuthn call:
```
class cred
{
	static get(options)
	{
		console.log("Get Called");
	}
}
class navigator
{
}
navigator.credentials=cred;
```
 
![image](https://github.com/w3c/webauthn/assets/44285351/0e72a26f-0ca4-4f3d-9510-a8e3bbd7210c)

The adversarial actor can perform a Self-XSS on his own system to modify how WebAuthn works for him. He can then capture the ‘options’ and send the same to the legitimate user to sign. One major issue that might arise here is that even if the client is on a phished webpage, the RP ID verification fails. This is because the challenge arises from the legitimate RP Server and must be signed by the keys enrolled against that RP Server only. 
This is overcome by not directing the legitimate user to his web browser. A trojan on the legitimate user’s system might be able to access the Authenticator while impersonating the RP Server without verification. The trojan uses the python implementation of the FIDO2 library. This choice can be justified with a better look at the client.py file in the FIDO2 library.
 
![image](https://github.com/w3c/webauthn/assets/44285351/48ac6e1c-a7ce-4f82-839e-b056b0f5629e)

The _verify_rp_id() function cryptographically verifies the RP ID against the origin from which the function is called. However, the origin can be specified as a string for the library, as seen in the __init__ constructor.
Hence, the attack model might be, the adversarial actor runs a Self-XSS to extract the ‘options’ sent by the RP Server. These options and the origin are now sent to Trojan running on the user’s system. The trojan invokes the authenticator and might require user verification with Fingerprint or a Pin. The legitimate user is assumed to touch his fingerprint sensor or enter the pin as a part of a sophisticated social engineering attack. The signed challenge, in the form of the PublicKeyCredential is sent back to the adversarial actor, who then returns the same to the custom implementation of navigator.credentials.get(). It is then returned to the RP Server from the system of the adversarial actor. Thus, the RP Server authenticates the adversarial actor as a legitimate user.
It is to be noted that the custom implementation of navigator.credentials.get() needs to convert the ArrayBuffers in the ‘options’ to arrays and then to JSON so that it can be sent to the applications running on the machine of the adversarial actor. It also needs to encode the response back to the desired formats.
Attack scenario
For the attack scenario, the adversarial actor has a cloud server that is used only to exchange the data between the system of the adversarial actor and the trojan. Any other messaging client could also be used instead of this cloud server. The adversarial actor further runs an application on his machine. The application first copies the script to be injected into the clipboard so that the adversarial actor can paste it in his browser console. The application then captures the ‘options’ from the malicious navigator.credentials.get() implementation and encodes it into Base64 and then sends it to the cloud server. The trojan running on the system of the legitimate user requests this Base64 data from the cloud server. It decodes the Base64 into proper WebAuthn format, performs the challenge signing and then encodes the results back into Base64 and sends it back to the cloud server. The cloud server returns the response back to the adversarial actor’s system. The application decodes the Base64 and returns it to the malicious implementation of navigator.credentials.get(). The implementation then decodes it back to ArrayBuffers and returns it to the RP Server.
The codes used for the following is available here:
•	Cloud side:
o	[https://adityamitra5102.github.io/fidovulntest/cloud/flaskapp.py](https://adityamitra5102.github.io/fidovulntest/cloud/flaskapp.py) This application is served by Apache Webserver in the cloud.
o	[https://adityamitra5102.github.io/fidovulntest/cloud/requirements.txt](https://adityamitra5102.github.io/fidovulntest/cloud/requirements.txt) This is the dependencies for the application.
•	Adversarial actor side:
o	[https://adityamitra5102.github.io/fidovulntest/attacker/flaskapp.py](https://adityamitra5102.github.io/fidovulntest/attacker/flaskapp.py) This application runs on the machine of adversarial actor so that the malicious implementation can communicate to localhost:5000.
o	[https://adityamitra5102.github.io/fidovulntest/attacker/inject.js](https://adityamitra5102.github.io/fidovulntest/attacker/inject.js) This is the Self-XSS code to be pasted in the browser console before WebAuthn call.
o	[https://adityamitra5102.github.io/fidovulntest/attacker/requirements.txt](https://adityamitra5102.github.io/fidovulntest/attacker/requirements.txt) This is the dependencies for the adversarial side application.
•	Trojan
o	[https://adityamitra5102.github.io/fidovulntest/malware/malware.py](https://adityamitra5102.github.io/fidovulntest/malware/malware.py) This is the basic implementation of the Trojan.
o	[https://adityamitra5102.github.io/fidovulntest/malware/requirements.txt](https://adityamitra5102.github.io/fidovulntest/malware/requirements.txt) This is the dependencies for the implementation of the Trojan.
The repository containing the code is not made public for obvious reasons. But the codes can be accessed from the above links.
The attack scenario was tested, and the adversarial actor was able to take over the Google account of the legitimate user in the process. The Google account was secured with Passkeys with Windows Hello.
![image](https://github.com/w3c/webauthn/assets/44285351/297003f5-a8b7-4a96-8c15-ead14c2f5d8d)

 
Full video of the case study is available here (unlisted video): [https://youtu.be/Lh45VzZqQ60](https://youtu.be/Lh45VzZqQ60)

**Comment by ve7jtb** [comment]
While the implementation of this attack may be new, the attack itself has been understood for over 5 years.

When webUSB initially was launched on Chrome, fido was not blocked and an attacker could trick a user into allowing webUSB for any seemingly legitimate reason and get direct access to an authenticator to perform a man-in-the-middle attack.    WebUSP blocked taking to Fido authenticators and platforms like Windows blocked non-privileged applications from talking directly to authenticators as well.   I will admit that the blocking of direct application access (eg malware) to authenticators varies a lot between platforms and interfaces.

At the root of this is that if malware has the ability to a talk directly to the authenticator providing RPID and client data, or can at a minimum specify the RPID and challenge (token binding was a mitigation for this in some cases but is not implemented by Fido clients any more due to lack of browser support) 

Properly implemented authenticators must implement UP in a way that cannot be remotely triggered by malware.  
If you have found authenticators that can have UP triggered remotely by malware that is a significant problem for Fido certification.

Preventing social engineering when the malware has control is hard.   At that point likely the malware could just exfiltrate the session cookie after any sort of successful login unless it is bound to the TLS session, or proxy commands via the user agent.

Hybrid authenticators at least provide an external UX for displaying the RPID forcing the attacker to trick the user into thinking they are logging into the real RP.   As some users would notice that having a random gaming site ask for a bank credential is unusual.

So yes if malware can talk directly to an authenticator or impersonate a browser privilege when talking to an OS webAuthn API that makes an active man-in-the-middle attack possible if the user can be socially engineered into providing UV and or UP.

**Comment by AdityaMitra5102** [comment]
I absolutely agree and I have a proposed mitigation strategy that can be added into the suggested implementation guidelines. The mitigation strategy might be able to prevent such attacks:

A JavaScript vulnerability allows an adversary to perform Self-XSS to override the navigator.credentials.get() function and to use a custom implementation of the same. The custom implementation allowed the adversary to export the ‘options’ and send them to the legitimate user over a Trojan, get it signed and then return the same to the RP Server. This allowed the adversary to takeover the accounts of legitimate users.
While this is not particularly a vulnerability of Web Authentication, it arises from JavaScript itself. This would mean, most browsers are affected by the same.
The suggested mitigation might not be absolute, and it is a suggestion to improve the implementations of WebAuthn. There might be ways to bypass this mitigation but that involve more sophisticated attack setup than the current attack scenario. However, to the best of our knowledge, this might be capable of mitigating the risk in most scenarios.
An example of a WebAuthn implementation that is vulnerable might be:
![image](https://github.com/w3c/webauthn/assets/44285351/b15595fc-39da-4737-acac-74e0d8a34c46)

Here, as we can see in line 19, the program calls navigator.credentials.get() function. This function can be overridden using a Self-XSS attack. 
For example, if the following code is entered into the browser console, the custom implementation of navigator.credentials.get() is called instead of the original:
![image](https://github.com/w3c/webauthn/assets/44285351/d2dd29ee-dd10-4902-808d-26965b5d8ebc)

However, it is known that the script in head tag of the page executes first before anything else. And non-async functions in the head tag will always execute before any other onload function is called or before the Self-XSS is performed in the console. 
This feature would be advantageous to deal with the vulnerability. In the recommended implementation of WebAuthn, we would suggest the developer to ‘backup’ the actual navigator.credentials.get() function with a name that might not be known to the adversarial actor. This name might also be dynamic or randomized. This name of the backup can also be obfuscated so that the adversary may not know it. This can be done with, for example a line of code like:
const randomnameattackerwontknow=navigator.credentials.get.bind(navigator.credentials);
Subsequently in the actual body of the webpage, the function ‘randomnameattackerwontknow()’ needs to be called instead of ‘navigator.credentials.get()’.
For example, the modified version of the WebAuthn implementation might be:
![image](https://github.com/w3c/webauthn/assets/44285351/082169ad-5400-4de4-ac5d-82f4629ad2fd)

This modified implementation is resistant to the Self-XSS attack that was discussed earlier. This is because the XSS attack will override the navigator.credentials.get() function. However, a pointer to the original function already stays with the browser which cannot be overridden if the name is obfuscated. This might be a probable mitigation of the problem.
This mitigation just provides a better practice for WebAuthn implementation and has been tested to be secure against overriding the native function with a Self-XSS.

**Comment by serianox** [comment]
If the user is already tricked into self-XSS, the attacker could just directly extract the session data? At this point, hardening WebAuthn against self-XSS is a plaster on a wooden leg, no?

**Comment by AdityaMitra5102** [comment]
I feel you misunderstood the attack procedure. The user is not tricked into Self-XSS. The attacker performs a Self-XSS on himself so that he can recover the challenge and RP ID from the browser. This is then sent to a trojan running in the background in the user's machine which just prompts the user for UP or UV. As the user gives the same, the signed challenge and authenticator data is sent back to the attacker via the trojan. Here, the user is not entering any code on the browser console.

**Comment by ve7jtb** [comment]
Preventing extensions from intercepting WebAuthn calls is not going to win points from people like 1Password and Dashlane who have to use that method on desktops.

If the attacker controls the user agent completely there are lots of ways to get a valid challenge from a RP.  I have grease monkey scripts that do that for debugging.  

Stoping Trojans from performing WebAuthn on the users computer without being detected is where resources should be applied.  We have known this for a long time and make slow progress as it is hard and platforms don't see it being exploited in practice. 

I have often heard the argument that once you have malware with that level of access on a users computer all guarantees around authentication security are gone anyway.

**Comment by AdityaMitra5102** [comment]
This prompt appears when a WebAuthn call is made from a Python application, which is shown in the second line of the prompt.
![image](https://github.com/w3c/webauthn/assets/44285351/b208cbef-6cbe-4328-a075-51a80d698fbe)

However, this is prompt when WebAuthn is called from a legitimate browser. It shows the call was made from "msedge.exe"
![image](https://github.com/w3c/webauthn/assets/44285351/d433104c-7a03-432b-b81a-f8a3efd8809c)

Now it is clear that the webauthn.dll driver in windows already knows which application is making the webauthn call. I would suggest passing the same onto the authenticator by adding it to the publicKeyCredentials object. The authenticator might reflect the same on the ClientDataJSON, whose hash is signed by the authenticator. Hence, in this way, the RP can know what application was used to perform the WebAuthn call. Then, the RP server can decide whether to allow the user or not.

**Comment by ve7jtb** [comment]
Now you are getting g into the specifics of the win32 "security model".  That is probably out of scope for WebAuthn.  On platforms that have authenticated apps like android those apps can only use RPID that they prove they control preventing them from man in the middling other RPID. 

Microsoft should comment on why they have chosen the approach they have taken. 

At this point there is no perfect platform unfortunately.

**Comment by emlun** [comment]
I would also like to add that the proposed mitigation of "backing up" the original value of `navigator.credentials.get` does little to nothing to prevent an attacker from modifying the script running in a browser on their own machine. Such an attacker could just as well intercept the delivery of the script file itself and make any modifications they wish, or indeed they don't even need to run the web app in a full browser. You could just as well simulate the same authentication process against the raw backend API using cURL, Telnet, Python or any other combination of network and scripting tools.

This mitigation _could_ help against malicious script injections overwriting `navigator.credentials.get` on the victim's machine, but for that there are better countermeasures such as the [`Content-Security-Policy` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy).

**Comment by arianvp** [comment]
> Preventing extensions from intercepting WebAuthn calls is not going to win points from people like 1Password and Dashlane who have to use that method on desktops.

I'm wondering if there would be a "better" way for 3rd party extensions hooking into Webauthn than overriding `navigator.credentials.get` though.  Where the browser dispatches `Listcredentials` to an extension and only if the extension says "Yes I have this credential" does it allow the exten

One data point: I had to uninstall 1Password extension as it now intercepts all my webauthn calls and I need 2 clicks to use my Apple Passkey instead of one and it's working on my nerves.

**Comment by bowtiejicode** [comment]
Kudos, I've thought of a similar attack vector last month. The only difference is that the web application is vulnerable to XSS which an attacker can craft a malicious payload that calls navigator.credentials.get and send the response back to attacker server. My case scenario is that there is no malware on the victim's machine.

My mitigation is therefore tie the webauthn challenge to a browser cookie (protected with HttpOnly).

Here is the flow
![image](https://github.com/w3c/webauthn/assets/47883976/3d4e611b-5bc5-42ec-b7cc-4ef633b09f2c)

**Comment by Firstyear** [comment]
I agree with @arianvp here - as fun as it is to have nav.cred.get overriden, there should be mechanisms in browsers to allow PW managers to more seamlessly and cleanly hook webauthn requests. The benefit here then is that nav.cred.get can be protected from overloading, which prevents these attack patterns that have been described here.

**Comment by micolous** [comment]
> Now it is clear that the webauthn.dll driver in windows already knows which application is making the webauthn call. 

This is not _always_ true.

The Windows Webauthn API _also_ works over RDP[^1] – so when you connect to a terminal server (or other RDP host), it can [tunnel the Webauthn API calls over a RDP virtual channel][0].

When this happens, Windows' Webauthn consent prompts are still presented on the client, because this has the USB, smartcard and/or BLE interface(s) physically adjacent to the user's authenticator, and [Windows still restricts direct hardware interface with authenticators][2]. Because the _client_ has no way to know/trust which binary on the server called the Webauthn API (it could be a malicious RDP server), it instead the consent dialog shows the properties of `mstsc.exe`, which is signed by Microsoft.

`webauthn.dll` exposes this functionality to `mstsc` via [the `IWTSPlugin` COM interface][3]; which other Windows applications (ie: remote desktop clients) could _also_ use.

If an attacker has a way to convince a signed application to call the Webauthn API on its behalf (such as connecting to a malicious RDP server), then the consent UI will show requests as being "from" legitimate applications. In your screenshot, you made a request from Python: and _every_ Python application/script would be presented as being made by a binary signed by the Python Software Foundation in the same way.

> I would suggest passing the same onto the authenticator by adding it to the publicKeyCredentials object. The authenticator might reflect the same on the ClientDataJSON, whose hash is signed by the authenticator. Hence, in this way, the RP can know what application was used to perform the WebAuthn call. Then, the RP server can decide whether to allow the user or not.

What you're proposing is similar to [Web Environment Integrity API][1]. This would have privacy implications, as this is browser fingerprinting.

I don't understand how "knowing which application performed the request" prevents any sort of attack: on Windows, it's also possible for a program running as Administrator to directly communicate with authenticators on outside this API, and construct whatever Client Data JSON you like and have the authenticator sign it (by design).

Running as a non-Administrator, you could also bring your own caBLE implementation, because Windows 11 only recently got platform support for that, and browsers still need to ship a caBLE implementation on Windows 10. Microsoft might start filtering the BLE advertisements on Windows 11 needed to make caBLE work in future, but again... Windows 11 only.

These are all very Windows-specific things anyhow, and _only_ Windows locks down authenticator communication.

But otherwise, that attack scenario isn't particularly new – Webauthn relies on the client's platform not being compromised to mitigate many security issues.

[0]: https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpewa/68f2df2e-7c40-4a93-9bb0-517e4283a991
[1]: https://en.wikipedia.org/wiki/Web_Environment_Integrity
[2]: https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/webauthn-apis#what-does-this-mean
[3]: https://learn.microsoft.com/en-us/windows/win32/api/tsvirtualchannels/nn-tsvirtualchannels-iwtsplugin

[^1]: This is only available in Microsoft's Remote Desktop Client on Windows 10 and later, connecting to systems with Windows 10 and later. It is not available in the macOS version of Microsoft's RDP client, and I'm not aware of any third-party clients implementing it.

**Comment by irew** [comment]
Just a note from Dashlane: we have no option but to monkey patch the APIs, as our service is run entirely via a browser extension (at least on Chromium browsers). Also having built out a passkey experience via this route, we do want to have control of the UX on desktop, as we are able to provide a consistent UX for info autofill and passkeys which is what users of the product are used to.

Agree some API for this could be sensible, however, if it requires the user to hunt around settings pages to "enable" it, this would be a step backwards. In general user's tend to lose their way inside any browser/platform settings screens, when some toggle to enable the password manager is buried there.

**Comment by arianvp** [comment]
I've opened a new issue for the PW manager usecase to keep this issue on topic: https://github.com/w3c/webauthn/issues/1976

**Comment by emlun** [comment]
If I understand the described attack correctly:

1. The attacker performs a **script injection attack on themself** in order to extract the `PublicKeyCredentialRequestOptions` parameters,
2. The attacker sends these `PublicKeyCredentialRequestOptions` parameters to a trojan running on the victim's machine,
3. The victim **interacts with the trojan** in order to produce an assertion response,
4. The trojan sends the assertion response back to the attacker, and
5. The attacker assembles the `PublicKeyCredential` result and presents this to the Relying Party, thus successfully impersonating the victim.

Then this is not a vulnerability in the WebAuthn API, because the attack in fact works by _circumventing_ the web platform on the side of the victim, thus bypassing the protections specified in WebAuthn. As also [noted](https://github.com/w3c/webauthn/issues/1965#issuecomment-1723019532), it's not even necessary for the attacker to involve the web platform at all on their side either.

I conclude that this attack is off topic for the WebAuthn spec.

This is not to say that the described attack wouldn't _work_ - assuming the attacker can successfully plant the trojan and get the victim to interact with it - but it's nothing we can fix in the WebAuthn spec. The security guarantees depend on the user interacting with a [conforming user agent](https://w3c.github.io/webauthn/#conforming-user-agent), which a malicious trojan is clearly not.

**Comment by emlun** [comment]
However, I noticed just now that in [§2. Conformance](https://w3c.github.io/webauthn/#sctn-conformance) we claim (emphasis added):

>This specification defines three conformance classes. Each of these classes is specified so that **conforming members of the class are secure against non-conforming or hostile members of the other classes**.

I'm not sure how true that statement is, unless it's meant to be understood in some very specific, narrowly scoped way. For example, a non-conforming client can direct its user to use a conforming authenticator to authenticate to a conforming RP on behalf of a malicious actor. Maybe this statement needs to be revised or clarified?

**Comment by nicksteele** [comment]
Discussed on the WG call today, the attacker-in-the-browser scenario is not within our threat model
