### ISSUE TITLE
[Superset] Updating credential metadata and requesting deletion of stale credentials

### ISSUE THREAD

**Issue by timcappalli** [w3c/webauthn#1967]
This issue is to consolidate a bunch of issues from over the years around deletion of stale credentials, updating properties of existing credentials, etc and provide a single issue to continue discussion. There was general consensus at TPAC 2023 that something like this is needed.

## Existing Issues

All of these issues have now been closed. **Please continue discussion here.**

### #1456: Personal information updates & webauthn
Ability to update things like `name` and `displayName` without creating a new credential.

### #1779: Facility for an RP to indicate a change of displayName to a discoverable credential
Similar to 1456, but specific to displayName

### #1560: Cleanup when creating discoverable credentials with attestations
Essentially allow for clean up of stale credentials. For example, a credential that was deleted RP-side, or a credential that doesn't meet RP requirements.

## High Level Requirements

Trends observed in these issues:

* Desire to signal to a client/authenticator that a specific credential is no longer valid and can be deleted
* Desire to signal to a client/authenticator that `name` and/or `displayName` has changed

**Comment by MasterKale** [comment]
> * Desire to signal to a client/authenticator that a specific credential is no longer valid and can be deleted
> * Desire to signal to a client/authenticator that `name` and/or `displayName` has changed

_Yes please._ The first one especially is highly desirable because passkey self-service must happen in two places, once on the RP's side and then a follow-up action within the provider's interface, and it's _very_ easy for the two to fall out of sync.

And I see adding the ability to update a credential's username and display name as highly desirable because it makes WebAuthn adaptable to real people problems. People change their legal names, online handles, email addresses, and other things that get used as usernames for a multitude of reasons, and right now the story for getting passkeys to respect this is limited to, "have the RP make a `.create()` call with the new name but same RP ID and user ID, and then hope the user uses the same authenticator as before so the old credential and its outdated metadata get overwritten." 

There's too much ambiguity in this current process that users can end up with two credentials, one with their old handle and a second one with their updated handle, thus exacerbating the RP's problems. I'd love for us to spend some more time on this in upcoming meetings to try and discover a better solution.

**Comment by emlun** [comment]
In the interest of having something concrete to discuss, here's another attempt (somewhat inspired by [my previous one](https://github.com/w3c/webauthn/issues/1560#issuecomment-799755300), but rather different). How about a new `updateCredentials` client extension?

```
extensions: {
  updateCredentials: {
    user: {
      id: new Uint8Array([1, 2, 3, 4]),  // User handle of the user account whose credentials to update/garbage-collect
      name: "example",                   // New value for user.name
      displayName: "Example User",       // New value for user.displayName
    },
    validCredentials: [
      // List of all of credentials valid for this account
      // Credentials with these IDs have their user.name and user.displayName updated
      // Credentials with above user handle and none of these IDs are deleted
      { type: "public-key", id: new Uint8Array([96, 231, 209, 27, /* ... */ ])},
      { type: "public-key", id: new Uint8Array([165, 225, 44, 123, /* ... */ ])},
      { type: "public-key", id: new Uint8Array([112, 235, 14, 6, /* ... */ ])},
      /* ... */
    ],
  },
},
```

As noted in the inline comments, the idea is:

- We address credentials to be updated by the combination of (user handle, credential ID).
- The RP lists all credentials that **should remain** after cleanup.
- Authenticators delete any credentials that have the given `user.id` but whose credential ID is not listed in `validCredentials`.
- Authenticators update the `user.name` and `user.displayName` each credential to the given values.
- No extension output, no feedback returned to the RP.

The main idea is that this way the RP doesn't need to track state changes over time, rather it only needs to report the current state.

Thoughts?

**Comment by emlun** [comment]
I'll start: You probably don't want to expose all this information before the user is authenticated. This also doesn't work at all when the user isn't yet identified (empty `allowCredentials`, username-less/passkey authentication). This makes it rather useless as an assertion extension, as that would require a second assertion ceremony. And since the RP isn't supposed to need to track state over time, presumably the RP should just always send the extension? So always two assertion ceremonies? That won't work.

So it needs to be something you can call after successful authentication. Maybe a static function on `PublicKeyCredential`?

Or maybe the extension outputs a callback that the RP can invoke after retrieving the right state for the user?

```js
const credential = await navigator.credentials.get({
  publicKey: {
    // ...
    extensions: {
      updateCredentials: true,  // Request that extension outputs include the callback
    },
  },
});

// Finish authentication on backend
const userSession = await finishAuthentication(credential);

credential.getClientExtensionResults().updateCredentials(userSession.updateCredentials);
```

**Comment by nsatragno** [comment]
I don't think we want to tie the update to an assertion, whether through an extension or a method on the returned `credential`. We should support an RP triggering updates & deletions without requiring a user to complete an assertion ceremony for each authenticator they own, e.g. from a settings page.

I prefer the static function approach. Especially if we can update other credential types on the same call. A possible API could be,

```javascript
navigator.credentials.update([
  { type: "public-key", id: ..., displayName: ..., etc ])}  // missing attributes are ignored
]);

navigator.credentials.delete([
  { type: "public-key", id: ...])}
]);
```

These would not be guaranteed to do anything. The browser would execute these actions opportunistically. For example, if a user just used a security key to sign in and the RP calls `delete`, the browser might send a ctap credential management request to the security key. Local platform authenticators would likely always be able to perform these. The counterpoint is that if the authenticator is not available, it's probably okay to not bother the user finding & activating it to make an update.

In my mind, an RP would call the same `delete` function in two different contexts: their "manage passkeys" settings page, and after a failed sign in attempt with a previously deleted, now unrecognized passkey.

`update` could similarly happen at both of those stages. However, currently the user's `name` and `displayName` are not part of the assertion, so the RP would have to call `update` after every sign in which seems suboptimal.

--

There are pros and cons to making this an action users have to consent to (and therefore, that we can inform the website that an update took place) vs a silent update. I think I prefer making these updates silently, so that RPs can build whatever experience they want around it, and we don't need to bother users twice. Showing UI for an update would also not be that dissimilar to calling `create` to override an existing passkey. But I would love to hear what RPs think!

**Comment by Firstyear** [comment]
> There are pros and cons to making this an action users have to consent to (and therefore, that we can inform the website that an update took place) vs a silent update. I think I prefer making these updates silently, so that RPs can build whatever experience they want around it, and we don't need to bother users twice. Showing UI for an update would also not be that dissimilar to calling `create` to override an existing passkey. But I would love to hear what RPs think!

I think `delete` here is a bit of a tricky one. For example, a resident key could be stored on a yubikey and *not* attached to the machine when the RP triggers the delete. This would lead to the `delete` call failing, and leaving the rk on the device. Similar, a lot of devices in circulation don't support ctap2.1pre or ctap2.1 anyway, so this delete action may not even work. When this `delete` then fails what does the RP do? Do we delete the credential anyway and then the user has to cleanup in their pwmanager / key manager? Do we insist on the device being attached so we can proceed? I think it's going to be hard to structure a UI/UX here. If we contrast to passwords today, when you change/delete a password in a password manager, the user is expected to cleanup after themself in the pw manager, so I don't know if we should try and do something different here. 

I think `update` however *could* be useful. My concern though is that by having `update` available, rp's will rely on it to be present and will start to store PII in the ID field of the rk expecting they can update it. Contrast to what it *should* be which is an unchanging, permanent, unique id like a uuid. I think update should *only* be able to update the displayName if implemented. 

Where `update` would be useful is for users when they want to change their displayName in the credential since rk's allow the RP displayName to de-sync from the stored displayName in the credential, so having a way to update this would be useful. I'm not sure how an RP would structure this workflow and communicate that to a user though. From a UI/UX perspective a flow to get a user to see that the displayName state is stored in two places, communicating that, and what they need to do would be extremely challenging. 

We're already seeing a ton of issues in adoption of passkeys in general with confusion about how to enable them, how they work, and the ui/ux to even use them to do a login. I think throwing in more elements here could just further damage the situation. 

So from the view of an RP and an RP library, my overall assessment is that while these functions have interesting properties, I likely would not implement them or use them because they risk confusing users. This is similar to my assessment of functions like isUVPAA and isPasskeyAvailable, where these functions only add extra complexity to interactions and workflows, leading to user confusion and rejection of webauth. 


As a more general meta commentary, there are two aspects to standards - the standard as written and envisaged by it's authors, and the standard as actually used. I think that webauthn has a huge surface area in the standard, and really most RP's will only use a fraction of that. So far that surface area at a high level is:

* Create new credentials (nav.cred.create)
* Perform authentication (nav.cred.get)
* Attest hardware security keys (attestation=direct in nav.cred.get).
* to/from base64 for create/get requests.

Outside of those use cases, we have a lot of "fluff" in the spec that the majority of RP's won't ever deploy or use. And the small percentage that do deploy and rely on those fluffy components will run into issues. So we need to ask ourselves is `update` and `delete` just adding more fluff? Or is it going to extend and become something critical that RP's are crying out for?

**Comment by nsatragno** [comment]
> When this delete then fails what does the RP do? Do we delete the credential anyway and then the user has to cleanup in their pwmanager / key manager?

The credentials should always be deleted (or rendered inoperable) on the server side. The way I envision it, deleting the credential on the authenticator is a nice-to-have. If the user tries to use that credential to sign in later, the RP can then and there attempt deleting it again, where the deletion is a lot more likely to succeed.

**Comment by emlun** [comment]
> When this `delete` then fails what does the RP do? Do we delete the credential anyway and then the user has to cleanup in their pwmanager / key manager?

> The credentials should always be deleted (or rendered inoperable) on the server side. The way I envision it, deleting the credential on the authenticator is a nice-to-have.

This is why I proposed a state transfer approach instead of an action-oriented approach - the former eliminates the problem by letting the authenticator(s), instead of the RP, figure out what needs to change to reflect the most recent state. If the user unplugs their USB security key before clicking "delete" in the RP UI, that doesn't matter because the RP can just send the current state at the next opportunity (be it login, a credential management operation or whatever).

**Comment by Firstyear** [comment]
I think you both have missed my point - the UI/UX around trying to coordinate a delete function as an RP will be extremely tricky to communicate to a user, and tough for an RP to coordinate and drive. Regardless of any technical ideas, I think this risks being added to the spec and not used by RP's.

**Comment by arnar** [comment]
We've had multiple requests for this from RPs, and some consider it blocking to implement discoverable flows as they correctly point out that account selectors will forever have stale info in them for many users. So I think this is a real issue and a solution here would be useful. (we can ask some of the RPs to chime in here if needed)

We think the state transfer approach is better for the general update - as that can be made repeatedly for cheap and thus help propagate updates to authenticators/providers that aren't always available, depending on what client the user is on. However, that only works if the user is authenticated already, so an action-type report for when a credential is rejected and no user is signed in seems useful as well.

We also agree trying to make WebAuthn a full CRUD-like API is not workable, nor desired. Rather, an opportunistic API for RPs to convey information back to authenticators and credential providers on a best-effort basis seems both useful and doable. For the lack of a better word we've been thinking about as _reports_ RPs make to the client, knowing that sometimes they may go nowhere.

The Wiki doesn't support PRs, but we'd like to propose adding the following explainer for an extensible navigator.credentials.report API that supports the above.

***

## WebAuthn Report API explainer

### Objective

Allow WebAuthn relying parties to report information about existing credentials back to credential storage providers, so that incorrect or revoked credentials can be updated or removed from provider and system UI.

### Background and motivation

Discoverable credentials, such as passkeys, can be requested with `navigator.credentials.get` with an empty `allowList`. In this case, if a user has any credentials for that relying party, they are presented with some UI to select which credential to use. If the user selects a credential, the resulting assertion carries the `user.id` value set at registration, allowing the relying party to resolve to an account without any further information.

This allows flows where the user is not required to enter a username, they simply select a credential. When used with conditional mediation, this further allows a smoother transition from traditional username entry, by allowing users that have passkeys to "fill" the username field using the passkey, and usually thereby omitting any further entry such as passwords or 2nd-factor authentication.

In such UI, passkeys are represented by the `user.name` and/or the `user.displayName` values that the relying party specified at registration. The user sees the entries as if they are _accounts_, however the entries correspond to individual credentials.

This pattern poses two main problems, given the current available APIs.

1. If a relying party stops accepting a credential, e.g. as a result of revoking it from an account or by completely deleting an account, the credential is still presented by clients during discoverable flows. 
2. Even if relying parties allow a user to change their username or display name on the account, such changes are not reflected in the display of credentials during discoverable flows.

The first case in particular is not only tied to explicit revocation or account deletion as requested by users. RPs may have policies that require them to revoke credentials after periods of inactivity. A common problem is also that the same user ends up with multiple accounts on a single RP unintentionally and may have a hard time keeping track of which accounts they want to use. Here the solution of account deletion or consolidation misses the mark if it cannot be represented in credential selection UI.

### Solution

A new API, `navigator.credentials.report`, allows relying parties to report such state updates back to user agents, who can forward these to the underlying credential providers. The API is opportunistic as there is no guarantee that the correct credential provider is reachable on the current client.

The API can take a number of report types, and RPs may combine multiple reports in a single call. The set of report types is meant to be extendable in the future.

A report type is a key in a JSON structure, where the value of that entry sets additional parameters specific to the report type.

Each report type lists example scenarios in which it makes sense to send it, and possible credential provider actions. Note that any credential provider action is optional and at the discretion of each provider implementation.

#### `unknownCredentialId`

This report names a credential ID and indicates that the relying party would reject an assertion with that credential because the credential ID is unknown to the RP.

```javascript
{
  unknownCredentialId: "vI0qOggiE3OT01ZRWBYz5l4MEgU0c7PmAA" // b64-url cred ID
}
```

_Usage scenario:_ Immediately following a response from `.get()` where the credential ID was not recognized. Appropriate to report even if the user was not authenticated.

_Example provider action:_ The credential may be marked for omission from future credential selection UI. If it was recently created and overwrote an existing credential, the previous one might be restored.

This situation may arise, for example, because the credential was revoked, or because the RP performed a create operation but failed to successfully store the public key on its backend.

#### `currentCredentials`

This report names a `user.id` value and all accepted credential IDs, and/or updated values for `user.name` and/or `user.displayName` associated with that account.

```javascript
{
  currentCredentials: {
    userId: "M2YPl-KGnA8",
    allAcceptedCredentialIds: [
      "vI0qOggiE3OT01ZRWBYz5l4MEgU0c7PmAA",
      ...
    ],
    user: {  // See https://www.w3.org/TR/webauthn-3/#dictdef-publickeycredentialuserentityjson (minus user.id)
      name: "a.new.email.address@example.com",
      displayName: "J. Doe"
    }
  }
}
```

_Usage scenario:_ Immediately after an accepted `.get()` response, or at any time the user is authenticated and the set of accepted credentials, username or displayName have changed.

This report should only be made if the user has been fully authenticated.

It is not possible to update the `user.id` value. Either `allAcceptedCredentalIds` or `user` can be omitted, but not both.

_Example provider action:_ If `allAcceptedCredentialIds` is present, mark any non-appearing credential for the same RP ID and `user.id` value for omission in future account selectors. If the user value is present, update the credential store to use the supplied values in future UI representing this credential.

Note that it's at the provider’s discretion how to handle conflicts between manually edited usernames/displayNames and the RP-provided reports.

### Examples

A simple way for a relying party to report updates without tracking any additional state is to send a `currentCredentials` report after every successful sign-in (note that this can be done even if WebAuthn wasn't used to sign in).

```javascript
navigator.credentials.report({publicKey: {
  currentCredentials: {
    userId: "M2YPl-KGnA8", // same as user.id at creation time
    user: {
      name: "currentemail@relying-party.com",
      userDisplayName: "J. Doe"
    },
    allAcceptedCredentalIds: [
      // IDs of all accepted credentials
      "vI0qOggiE3OT01ZRWBYz5l4MEgU0c7PmAA",
      "Bq43BPs"
    ]
  }
});
```

If a relying party receives an assertion with a credential that it does not recognize, it can report this back to the client. Note that it is safe to do this even if no user is signed in, as long as the credential id was already observed from this client.

```javascript
navigator.credentials.report({publicKey: {
  unknownCredentialId: "vI0qOggiE3OT01ZRWBYz5l4MEgU0c7PmAA"
}});
```

If the user revokes or deletes a credential, e.g. in an account settings UI on the relying party's website, the relying party can opportunistically report this at that time with the `unknownCredentialId` type. However this will only have effect if the user agent is able to route the report to the same credential provider that created this credential. It may be better to send a `currentCredentials` report instead, with a complete list of valid credential IDs. In this case the `user` attributes can be omitted to signal they should not be updated.

Similarly, if a user changes their user- or display names while signed in, e.g. in an account settings UI, this can be reported to the current user agent without listing accepted credential ids:

```javascript
navigator.credentials.report({publicKey: {
  currentCredentials: {
    userId: "M2YPl-KGnA8", // same as user.id at creation time
    user: {
      name: "currentemail@relying-party.com",
      userDisplayName: "J. Doe"
    }
  }
});
```

In that case no credentials will be marked for removal. There is no _harm_ in also reporting accepted credential IDs, and indeed that report may reach credential providers that have outdated credentials and haven't received previous reports. But the choice is there if e.g. loading the list of accepted credentials would require additional (re-)authentication of the user, or other reasons that data isn't easily available on the server.

**Comment by Firstyear** [comment]
> Maybe a crazy take on the other direction, but I think would make things simpler: if passkeys are designed to identify a single person (maybe using multiple devices in sync), why not just remove the `name` and `displayName` from the protocol?

Then just don't use residentKeys/discoverableCredentials. This whole issue is avoided if you do that.

**Comment by jgimenez** [comment]
> Then just don't use residentKeys/discoverableCredentials. This whole issue is avoided if you do that.

Not really, they're still useful to present credentials for a given RP. In 99% of cases you will have 1 credential, in the other cases a label can come in handy.

**Comment by serianox** [comment]
As some pointed out, it is impossible nor desirable for a RP to delete remotely stale credentials:
- security key may not be attached,
- probably some privacy/DOS issues?

I think the only way to delete stale credentials is a _user side garbage collection_ - the client could list all the credentials/RP and use a well-known endpoint to check if the credential still exists or can be deleted.

**Comment by arianvp** [comment]
A  `https://${origin}/.well-known/webauthn-credential/ping`  URL would be useful. But now suddenly we'd be in the business of standardising on a `RP<->Client` protocol which we've refrained from thus-far completely. I'd be a big step in my opinion.

**Comment by nsatragno** [comment]
>  Let the RP set allowCredentials and then the client only displays the intersection of allowCredentials and the credentials that are actually stored in the browser.

OT, but if you want to build a username first into password + autofill UI flow today you can do it. See `credentialIdFilter` in https://w3c.github.io/webauthn/#sctn-discover-from-external-source, conditional UI supports passing an allow list to filter the credentials. They still have to be discoverable because they need a label to be put in autofill, and non discoverable credentials may forgo storing a name / display name.

**Comment by arianvp** [comment]
> OT, but if you want to build a username first into password + autofill UI flow today you can do it. See credentialIdFilter in https://w3c.github.io/webauthn/#sctn-discover-from-external-source, conditional UI supports passing an allow list to filter the credentials. They still have to be discoverable because they need a label to be put in autofill, and non discoverable credentials may forgo storing a name / display name.

This seems badly implemented across browsers. E.g. Safari doesn't seem to support this.  It seems to work on Chrome though.

**Comment by timcappalli** [comment]
These scenarios are planned to be addressed by: https://github.com/w3c/webauthn/wiki/Explainer:-WebAuthn-Report-API-explainer
