### ISSUE TITLE
Virtual Authenticator API does not expose a way to set backup-eligible or backup-status flags

### ISSUE THREAD

**Issue by MasterKale** [w3c/webauthn#1987]
## Proposed Change

The current state of the Virtual Authenticators API does not allow users of the API any way to influence the `be` and `bs` flags in authenticator data. This makes it difficult to use this API for E2E tests that want to test "synced passkey" scenarios.

We should update this API to add in new parameters to the [Add Virtual Authenticator](https://w3c.github.io/webauthn/#sctn-automation-add-virtual-authenticator) API call payload that can make it possible to set `be` and `bs`, a la the current `isUserConsenting` and `isUserVerified` parameters.

**Comment by emlun** [comment]
I think the [Add Credential](https://w3c.github.io/webauthn/#sctn-automation-add-credential) API call would be the be more appropriate place for these, but I agree otherwise.

I also don't think we need to define any new operations to enable changing `bs` between assertions - since _Add Credential_ includes all credential state (including the private key and signature counter), the caller can "update" `bs` by first calling [Remove Credential](https://w3c.github.io/webauthn/#sctn-automation-remove-credential) and then calling _Add Credential_ with the new `bs` value.

**Comment by MasterKale** [comment]
> I think the [Add Credential](https://w3c.github.io/webauthn/#sctn-automation-add-credential) API call would be the be more appropriate place for these, but I agree otherwise.

I honestly agree with you, as `be` and `bs` are definitely credential properties vs authenticator properties. However the current means of manipulating flags in `authData` are centralized in the Add Virtual Authenticator API call as `isUserConsenting` and `isUserVerified` so that's why I suggested the authenticator API instead...

Actually no, now I agree 100%, the means of specifying `be` and `bs` for a credential **should** be on Add Credential.

> ...the caller can "update" bs by first calling [Remove Credential](https://w3c.github.io/webauthn/#sctn-automation-remove-credential) and then calling Add Credential with the new bs value.

I think I can get behind this, but we _do_ have precedent for an "update" API [Set User Verified](https://w3c.github.io/webauthn/#sctn-automation-set-user-verified). Maybe we can add a similar "Set Backup Status" API for individual credentials.

**Comment by agl** [comment]
@nsatragno

**Comment by nsatragno** [comment]
If we put only the option on `AddCredential`, then how would you test your website's behaviour on credential creation?

Here's a proposal:
* Have `backup-eligibility` and `default-backup-state` be a setting on `AddVirtualAuthenticator`. This lets you test what happens for various values when creating a credential.
* Add `backup-eligibility` and `backup-state` to `AddCredential`, which lets you test assertions.
* Add a `Set Backup State` method to avoid having to recreate a credential.
  I'm not a fan of the remove-and-add proposal because if we add more state to the credentials, then the developer has to make sure they update all the places where they do this if they want to get the exact same credential when they update their e2e testing browser. Or worse: if your webdriver version drifts from your browser version, it might be impossible to recreate the same credential, since the old webdrive might not know about new state.

**Comment by fwadnjar** [comment]
1987[1987]()

**Comment by fwadnjar** [comment]
1987

**Comment by fwadnjar** [comment]
webauthn@noreply.github.com

**Comment by james-d-elliott** [comment]
It may also be advisable considering this is intended for E2E tests to be able to change the BE flag AFTER the credential is created. I think being able to test the fact a change to the BE flag results in an error in integration and that the error looks appropriate is desirable.

**Comment by MasterKale** [comment]
This is still on my radar, I just couldn't get a draft up in time for tomorrow's WAWG meeting. I'll aim for next week's meeting instead.
