### ISSUE TITLE
Cambios por abuso

### ISSUE THREAD

**Issue by JuanMahnjn** [w3c/webauthn#2006]
## Proposed Change

Describe your proposed change. If you have suggested text, please file a corresponding Pull Request.

**Comment by emlun** [comment]
If you'd like to report an issue, please include a description of the problem or question in the issue body.

**Comment by JuanMahnjn** [comment]
Están manipulando internamente mi celular.
Quiciera llevar acabo una investigación legal ante la ley. Si me pudieran apoyar enviándome a detalle de la dirección IP y las llaves de acceso que se presentó en mi móvil mediante mi IMEI, correo electrónico, y apps.

Ya que desafortunadamente aquí en México se necesita saber casi casi cuando y porque estornudo.

Les agradezco bastante el apoyo.

Juan Manuel Hernández Jiménez
5573752898 / 5519194806
juanhnjn@gmail.com
juanmahnjn@gmail.com
juan_mick@hotmail.com

**Comment by emlun** [comment]
> Están manipulando internamente mi celular. Quiciera llevar acabo una investigación legal ante la ley. Si me pudieran apoyar enviándome a detalle de la dirección IP y las llaves de acceso que se presentó en mi móvil mediante mi IMEI, correo electrónico, y apps.
> 
> Ya que desafortunadamente aquí en México se necesita saber casi casi cuando y porque estornudo.
> 
> Les agradezco bastante el apoyo.
> 
> [...]

This does not appear to be related to the WebAuthn specification. This working group does not operate any of the services you mention and cannot help you find the information you seek. We wish you the best of luck in resolving the issue.

I will delete your comment in order to limit exposure of your contact details, but unfortunately it will remain in the W3C mail list archives.

---

(Traducido por el Traductor de Google)

Esto no parece estar relacionado con la especificación WebAuthn. Este grupo de trabajo no opera ninguno de los servicios que usted menciona y no puede ayudarlo a encontrar la información que busca. Le deseamos la mejor de las suertes para resolver el problema.

Eliminaré su comentario para limitar la exposición de sus datos de contacto, pero desafortunadamente permanecerá en los archivos de la lista de correo del W3C.
