### ISSUE TITLE
Privacy across Account IDs

### ISSUE THREAD

**Issue by yaronf** [w3c/webauthn#204]
4.5: `excludeList` allows an RP to tie different identities, i.e. to check if Alice and Bob are both used as identities on the same authenticator. This is because each of the `CredentialDescription` structures can contain a different id value, whereas if we only wanted to prevent multiple credentials for the same account, we would simply use the id value of the Account structure. Is this an attack we are willing to live with? Why not require (or allow) user consent for this step, e.g. "RP X wants to see other identities you have with it, do you allow that?"

@vijaybh: One issue is that there are authenticators which have no local storage, but encode the entire credential and all its metadata into the credential ID. So for these authenticators, a credential ID is required. However, **the authenticator could ignore any excludeList entries that are not for the same account ID**.

**Comment by vijaybh** [comment]
Doesn't that just create another attack where the bad guy can find out which credential IDs map to which account IDs?

I think you express a valid concern BTW, just trying to figure out if there is any way to solve it without just displacing the problem.

**Comment by yaronf** [comment]
I agree this is a problem, I just think it's less important, because it only applies to users who use multiple authenticators (multiple mobile devices?) to authenticate to the same account. And as far as I know, this is less common than having multiple accounts for the same user with the same device.

**Comment by equalsJeffH** [comment]
see also #184

**Comment by equalsJeffH** [comment]
see also issue 
#140

**Comment by equalsJeffH** [comment]
see also #743

**Comment by equalsJeffH** [comment]
A portion of this issue was fairly recently addressed by PR #651 which formalized the language for matching the items in the [`excludeCredentialDescriptorList`](https://w3c.github.io/webauthn/#op-make-cred) such that an RP can only probe for existing credentials that are mapped to itself. 

This seems to me to address a portion of @yaronf's suggestion of:
> the authenticator could ignore any excludeList entries that are not for the same account ID.

..in that we no longer have a notion of "account ID" and mapping to RP ID (and cred type) narrows what the RP can probe for, and is the best the spec presently can accomplish (i.e., without further changes).

Yes?


That said,  it does seem there is presently an issue of sorts at credential creation time, [as noted by](https://github.com/w3c/webauthn/issues/204#issue-177561011) @yaronf, in that a malicious RP can populate the  [`excludeCredentials`](https://w3c.github.io/webauthn/#dom-makepublickeycredentialoptions-excludecredentials) list with credential IDs it either knows or guesses in order to see if they exist on the user's presently-available authenticator(s). 

Given the way the webauthn protocol works **[1]**, it seems to me (at this time anyway), that @yaronf's suggestion of requiring or recommending that authenticators (and/or client platforms) prompt the user for consent when an RP stipulates a non-empty [`excludeCredentials`](https://w3c.github.io/webauthn/#dom-makepublickeycredentialoptions-excludecredentials) list. If the user does not consent, then a credential is not created. We would need to stipulate timing-related language similar to that now stipulated for the [authentication ceremony case](https://w3c.github.io/webauthn/#sec-assertion-privacy). 

An issue with this is that a user will not be able to a prior discern when an RP is "legitimately" attempting to allow the registration of only one credential with whichever of its accounts this user is mapped to, and when the RP is probing the user's authenticator(s) for existing credentials mapped to it (the RP), for whatever arbitrary purposes. 

So I am not sure what sort of prompt/question the authenticator or client platform ought to pose to the user in such a situation, i.e., what we ought to suggest in the spec.  Perhaps @yaronf's [proposed language](https://github.com/w3c/webauthn/issues/204#issue-177561011) is fairly close?  What if we suggest:
> [RP ID] wishes to detect whether there are other credentials registered with it on this authenticator. Do you wish to proceed?

Am I missing something in all this?  WDYT?

====
**[1]** with the RP initiating the actual credential creation operation through its client-side JS calling into [`navigator.cedentials.create({publickey})`](https://w3c.github.io/webappsec-credential-management/#dom-credentialscontainer-create) (with an [`excludeCredentials`](https://w3c.github.io/webauthn/#dom-makepublickeycredentialoptions-excludecredentials) list) thus invoking [`[[Create]]`](https://w3c.github.io/webauthn/#createCredential), which in turn invokes an authenticator's [authenticatorMakeCredential operation](https://w3c.github.io/webauthn/#op-make-cred) (passing in the `excludeCredentialDescriptorList`).

**Comment by equalsJeffH** [comment]
Ok, it seems I was missing something, given @emlun's [detailed analysis above](https://github.com/w3c/webauthn/pull/687#issuecomment-359087435), _I **am** missing something_ :)

Given said analysis, it seems this issue #204 is addressed and we can close it with no action -- WDYT?

**Comment by emlun** [comment]
I agree we should be able to close the `excludeCredentials` issue. It should be fixed by #687, although as @equalsJeffH [points out](https://github.com/w3c/webauthn/pull/687#issuecomment-359051421) we should also mention `makeCredential` in the Privacy Considerations subsection.

On the topic of prompting for consent, both authenticator operations specify that consent MUST always be obtained (via either a test of user presence test or user verification), see [authenticatorMakeCredential][amc] step 6 and [authenticatorGetAssertion] step 7.

[amc]: https://w3c.github.io/webauthn/#op-make-cred
[aga]: https://w3c.github.io/webauthn/#op-get-assertion

**Comment by equalsJeffH** [comment]
@emlun 
> we should also mention makeCredential in the Privacy Considerations subsection

Oh yeah huh, thx for catching that. I'll endeavor to address it.  So not closing this just yet.

**Comment by selfissued** [comment]
Where do we stand on finishing this?

**Comment by equalsJeffH** [comment]
it is in my queue...

**Comment by equalsJeffH** [comment]
see PR #777
