### ISSUE TITLE
Make PublicKeyCredentialRequestOptions.rpId a DOMString

### ISSUE THREAD

**Issue by zacknewman** [w3c/webauthn#2066]
Both [`PublicKeyCredentialRpEntity.id`](https://www.w3.org/TR/webauthn-3/#dom-publickeycredentialrpentity-id) and [`PublicKeyCredentialRequestOptions.rpId`](https://www.w3.org/TR/webauthn-3/#dom-publickeycredentialrequestoptions-rpid) represent the same thing (i.e., [RP ID](https://www.w3.org/TR/webauthn-3/#rp-id)); however the former is modeled as a [`DOMString`](https://webidl.spec.whatwg.org/#idl-DOMString) while the latter is modeled as a [`USVString`](https://webidl.spec.whatwg.org/#idl-USVString). These should be the same type. Specifically `PublicKeyCredentialRequestOptions.rpId` should be a `DOMString` as well or `PublicKeyCredentialRpEntity.id` should be a `USVString`. Should be noted that [`PublicKeyCredentialRequestOptionsJSON.rpId`](https://www.w3.org/TR/webauthn-3/#dom-publickeycredentialrequestoptionsjson-rpid)  is already a `DOMString`.

**Comment by emlun** [comment]
Thanks for pointing this out!

2024-05-15 WG call: Agreed we should change `PublicKeyCredentialRpEntity.id` to `USVString`. Strictly speaking this is a breaking change (changing a type bound in covariant position to be more restrictive), but in practice this shouldn't be able to break any applications since those then credentials wouldn't have worked in `get()` anyway.

@jschanck Seeing as Firefox is the browser that makes the most actual use of WebIDL - would changing [`PublicKeyCredentialRpEntity.id`](https://www.w3.org/TR/webauthn-3/#dom-publickeycredentialrpentity-id) to `USVString` be a problem for Firefox?

**Comment by jschanck** [comment]
No, that wouldn't be a problem.
