### ISSUE TITLE
Define `TypeError` behavior during `.get()`

### ISSUE THREAD

**Issue by MasterKale** [w3c/webauthn#2094]
## Proposed Change

@nsatragno called out a couple weeks back that it's odd there's no definition of a `TypeError` being raised from a call to `.get()` when the `options` value is invalid:

https://github.com/w3c/webauthn/pull/2047#discussion_r1655429301

We should address this after merging #2047.

**Comment by emlun** [comment]
I reckon this is inherited from the JavaScript-to-WebIDL language bindings? See for example the conversion routine for dictionary types (which include [`PublicKeyCredentialCreationOptions`](https://w3c.github.io/webauthn/#dictionary-makecredentialoptions) and [`PublicKeyCredentialRequestOptions`](https://w3c.github.io/webauthn/#dictionary-assertion-options)):

>**3.2.17. Dictionary types**
>[...]
>A JavaScript value _jsDict_ is [converted](https://webidl.spec.whatwg.org/#dfn-convert-ecmascript-to-idl-value) to an IDL [dictionary type](https://webidl.spec.whatwg.org/#idl-dictionary) value by running the following algorithm (where _D_ is the [dictionary type](https://webidl.spec.whatwg.org/#idl-dictionary)):
>
>1. If [Type](https://tc39.es/ecma262/#sec-ecmascript-data-types-and-values)(_jsDict_) is not Undefined, Null or Object, then [throw](https://webidl.spec.whatwg.org/#javascript-throw) a [`TypeError`](https://tc39.es/ecma262/multipage/fundamental-objects.html#sec-native-error-types-used-in-this-standard-typeerror).
>[...]
>4.1.3.1. Let _idlMemberValue_ be the result of [converting](https://webidl.spec.whatwg.org/#dfn-convert-ecmascript-to-idl-value) _jsMemberValue_ to an IDL value whose type is the type _member_ is declared to be of.
> [...]
>4.1.5. Otherwise, if _jsMemberValue_ is **undefined** and _member_ is [required](https://webidl.spec.whatwg.org/#required-dictionary-member), then throw a [`TypeError`](https://webidl.spec.whatwg.org/#exceptiondef-typeerror).

We don't explicitly state in the WebAuthn spec that this conversion must occur, but it clearly must since the API is defined in WebIDL and the actual implementation is exposed in JavaScript. See also:

>[§3.2. JavaScript type mapping](https://webidl.spec.whatwg.org/#js-type-mapping)
>[...]
>[...] For each IDL type, it is described how JavaScript values are converted to an IDL value when passed to a [platform object](https://webidl.spec.whatwg.org/#dfn-platform-object) expecting that type, [...]

>[§2.12. Objects implementing interfaces](https://webidl.spec.whatwg.org/#idl-objects)
>[...]
>**Platform objects** are objects that implement an [interface](https://webidl.spec.whatwg.org/#dfn-interface).

...which would for example include the [`PublicKeyCredential`](https://w3c.github.io/webauthn/#iface-pkcredential) interface.

I'm in favour of #2047 mentioning that `TypeError` is one of the errors RPs may expect, but I don't think WebAuthn needs to explicitly define how these particular `TypeError`s should be thrown - I figure that should be handled by WebIDL already.

**Comment by MasterKale** [comment]
#2047 has been merged so I'm closing this as done
