### ISSUE TITLE
CollectedClientData fields are not ordered correctly and crossOrigin should be required

### ISSUE THREAD

**Issue by zacknewman** [w3c/webauthn#2101]
The [WebIDL for `CollectedClientData`](https://www.w3.org/TR/webauthn-3/#dictdef-collectedclientdata) currently lists `topOrigin` _before_ `crossOrigin`; however [serialization](https://www.w3.org/TR/webauthn-3/#dictdef-collectedclientdata) is defined such that `crossOrigin` is written first.

One could argue that the order of the IDL does not matter; however the note above it makes a point to call out the order:

>Note: The [CollectedClientData](https://www.w3.org/TR/webauthn-3/#dictdef-collectedclientdata) may be extended in the future. Therefore it’s critical when parsing to be tolerant of unknown keys and of any reordering of the keys. See also [§ 5.8.1.2 Limited Verification Algorithm](https://www.w3.org/TR/webauthn-3/#clientdatajson-verification).

Regardless, serialization and [the limited verification algorithm](https://www.w3.org/TR/webauthn-3/#clientdatajson-verification) require `crossOrigin` to exist; so shouldn't the IDL be updated to reflect that? I'm sure if this were updated, bugs like [this Firefox one](https://bugzilla.mozilla.org/show_bug.cgi?id=1888851) would not have happened.

**Comment by emlun** [comment]
I agree it makes sense for `crossOrigin` to be defined before `topOrigin`. Fixed in PR #2114.

> Regardless, serialization and [the limited verification algorithm](https://www.w3.org/TR/webauthn-3/#clientdatajson-verification) require `crossOrigin` to exist; so shouldn't the IDL be updated to reflect that?

It doesn't appear to be explicitly documented (#1276), but as hinted in #1631, I'm quite sure it's not `required` because RPs cannot rely on it being present in case the client is an L1 implementation.

**Comment by emlun** [comment]
> This means backward compatibility was violated regardless.

Not really, but I guess it depends on the definition of backwards compatibility. The way we think of it in this case is that the Web IDL should reflect the realities of the interface presented to RPs, and it therefore must also cover past versions of the spec.

The limited serialization algorithm is required for L2 clients, but obviously not for L1 clients since it didn't exist in L1. But RPs are not required to use the limited verification algorithm, and if an RP wants to remain compatible with L1 clients then it of course cannot impose L2 requirements on L1 clients. Even if an RP is not willing to support L1 clients, there is no guarantee that the client is an L2 client. The reality will always be that `CollectedClientData.crossOrigin` might be undefined, so we should advertise that to the RP in the Web IDL.

It is unfortunate that - as you've noticed - this interface presented to RPs is not identical to the interface to be implemented by clients, but there's nothing we can do about that now for the differences between L1 and L2.

On that train of thought, though... maybe we could in L3 add a version number to the client data, which would prevent future ambiguities like this between spec versions. I'll bring that topic up with the working group.
