### ISSUE TITLE
Add `publicKey` and `publicKeyAlgorithm` to `AuthenticatorAssertionResponseJSON`

### ISSUE THREAD

**Issue by zacknewman** [w3c/webauthn#2105]
[`publicKey`](https://www.w3.org/TR/webauthn-3/#dom-authenticatorattestationresponsejson-publickey) and [`publicKeyAlgorithm`](https://www.w3.org/TR/webauthn-3/#dom-authenticatorattestationresponsejson-publickeyalgorithm) were added to [`AuthenticatorAttestationResponseJSON`](https://www.w3.org/TR/webauthn-3/#dictdef-authenticatorattestationresponsejson) in order to [easily access credential data](https://www.w3.org/TR/webauthn-3/#sctn-public-key-easy). Attestation can also occur during authentication and is why [`AuthenticatorAssertionResponseJSON`](https://www.w3.org/TR/webauthn-3/#dictdef-authenticatorassertionresponsejson) has a field for [`attestationObject`](https://www.w3.org/TR/webauthn-3/#dom-authenticatorassertionresponsejson-attestationobject). Does it not make sense to also add `publicKey` and `publicKeyAlgorithm`—`publicKeyAlgorithm` would _not_ be required like it is for `AuthenticatorAttestationResponseJSON`—to `AuthenticatorAssertionResponseJSON` as well?

**Comment by emlun** [comment]
Assertion-time attestation, and thus the `attestationObject` and related fields of [`AuthenticatorAssertionResponse`](https://w3c.github.io/webauthn/#iface-authenticatorassertionresponse) and its JSON counterpart, were removed in PR #1997.

For proposals on spec revisions, please refer to the [editor's draft](https://w3c.github.io/webauthn/) rather than the versioned snapshots.

**Comment by emlun** [comment]
No worries! Spec work can be confusing at the best of times.
