### ISSUE TITLE
Remove `RegistrationResponseJSON.id` and `AuthenticationResponseJSON.id`

### ISSUE THREAD

**Issue by zacknewman** [w3c/webauthn#2119]
First, [`RegistrationResponseJSON.id`](https://w3c.github.io/webauthn/#dom-registrationresponsejson-id) and [`AuthenticationResponseJSON.id`](https://w3c.github.io/webauthn/#dom-authenticationresponsejson-id) are modeled as `Base64URLString`s, but [`Credential.id`](https://w3c.github.io/webappsec-credential-management/#dom-credential-id) is already a `USVString` so it's a little bit weird to change the type to a `Base64URLString` since from my understanding only `ArrayBuffer`s should need to have their types changed (emphasis added):

> [`toJSON()`](https://w3c.github.io/webauthn/#dom-publickeycredential-tojson)
>
> This operation returns [`RegistrationResponseJSON`](https://w3c.github.io/webauthn/#dictdef-registrationresponsejson) or [`AuthenticationResponseJSON`](https://w3c.github.io/webauthn/#dictdef-authenticationresponsejson), which are [JSON type](https://webidl.spec.whatwg.org/#dfn-json-types) representations mirroring [`PublicKeyCredential`](https://w3c.github.io/webauthn/#publickeycredential), suitable for submission to a [Relying Party](https://w3c.github.io/webauthn/#relying-party) server as an `application/json` payload. The [client](https://w3c.github.io/webauthn/#client) is in charge of [serializing values to JSON types as usual](https://webidl.spec.whatwg.org/#idl-tojson-operation), but MUST take additional steps to first encode any [_`ArrayBuffer`_](https://webidl.spec.whatwg.org/#idl-ArrayBuffer) values to [`DOMString`](https://webidl.spec.whatwg.org/#idl-DOMString) values using [base64url encoding](https://w3c.github.io/webauthn/#base64url-encoding).

Are user agents expected to encode `id` again so that an RP receives a Credential ID that has been encoded twice or are user agents expected to know that the `USVString` is already a `Base64URLString` and send it as is? If the latter, it seems less confusing to just leave the type as a `USVString`.

Anyway, one issue I have as an RP library writer is deciding which Credential ID to use. Since my library is focused on _strict_ conformance, I require all instances of Credential IDs to match instead of arbitrarily selecting one to use when they don't align. The more places Credential IDs exist the more likely there is disagreement. What is the motivation behind providing both `id` and `rawId`? They will be exactly the same, so why not remove one? I know at least one application that provides different values for `id` and `rawId` almost certainly by accident: one is double encoded as base64URL.

**Comment by emlun** [comment]
Looks like `rawId` first appeared in commit https://github.com/w3c/webauthn/pull/384/commits/ab8d74e50493fbe9e49ebb439a2d29337d63cdf1 of PR #384. I don't see any rationale for it in that thread, but this same discussion was brought up in issue #412 which was closed without action as the proposed changes were breaking changes.

> Are user agents expected to encode `id` again so that an RP receives a Credential ID that has been encoded twice or are user agents expected to know that the `USVString` is already a `Base64URLString` and send it as is? If the latter, it seems less confusing to just leave the type as a `USVString`.

User agents are expected to _not_ re-encode `id`, so yes, `id` and `rawId` are essentially aliases in the `*ResponseJSON` context. Fair point about the `Base64URLString` type perhaps making it seem like it would be doubly-encoded, but on the other hand it _is_ a base64 encoded value. @MasterKale any thoughts on that?


> one issue I have as an RP library writer is deciding which Credential ID to use.

I agree that libraries should not tolerate a mismatch between `id` and `rawId`. The server-side library I've worked on, [java-webauthn-server](https://github.com/Yubico/java-webauthn-server/), essentially treats the two as aliases, requires at least one of them to be present and [rejects mismatches if both are present](https://github.com/Yubico/java-webauthn-server/blob/240b8d937e5aeb6d861625dada77035b49b839bf/webauthn-server-core/src/main/java/com/yubico/webauthn/data/PublicKeyCredential.java#L95-L101). That library predates these `*ResponseJSON` types, but the idea is the same.

**Comment by MasterKale** [comment]
> > Are user agents expected to encode `id` again so that an RP receives a Credential ID that has been encoded twice or are user agents expected to know that the `USVString` is already a `Base64URLString` and send it as is? If the latter, it seems less confusing to just leave the type as a `USVString`.
> 
> User agents are expected to _not_ re-encode `id`, so yes, `id` and `rawId` are essentially aliases in the `*ResponseJSON` context. Fair point about the `Base64URLString` type perhaps making it seem like it would be doubly-encoded, but on the other hand it _is_ a base64 encoded value. @MasterKale any thoughts on that?

Sorry for creating confusion with this. User agents **are not** expected to encode `id` again. Thinking back I probably used `Base64URLString` for `id` as well because "it's a base64url-encoded string." I agree it would make sense for it to share the type of `Credential.id`, though.

@emlun can I simply change `RegistrationResponseJSON.id` and `AuthenticationResponseJSON.id` to `USVString` without breaking anything?

**Comment by emlun** [comment]
@MasterKale It could in theory break existing implementations of the WebIDL, but the feature hasn't been in a mature spec release yet, so I say go for it. Usages by RPs are unlikely to break since the actual types are the same.

We should stick with `DOMString` wherever we can, though, as recommended by the [Web IDL spec][1]:

>Specifications should only use `USVString` for APIs that perform text processing and need a string of scalar values to operate on. Most APIs that use strings should instead be using `DOMString`, which does not make any interpretations of the code units in the string. When in doubt, use `DOMString`.

[1]: https://webidl.spec.whatwg.org/#idl-USVString

**Comment by MasterKale** [comment]
> Fair point. Though perhaps it's debatable which is worse under the principle of least surprise: `*ResponseJSON` _duplicating_ `id` as `rawId`, or `*ResponseJSON` _missing_ the `rawId` attribute from the `*Response` types they're supposed to be mirroring?
> 
> I think I agree that correctness should override that concern, though: removing `*ResponseJSON.rawId` is better because it eliminates a possible source of inconsistency.
> 
> @MasterKale What do you think?

It has always been weird to me that `id` and `rawId` are always the same value. FIDO conformance requires RPs (and libraries that aim to become conformant) to check that both are present and equal to each other, but beyond that there is no practical reason to keep both values around.

_However_, both values exist in `PublicKeyCredential` and afaik we're not considering trying to remove the redundancy here. I suggest it would become confusing for a JSON-serialized representation of a `PublicKeyCredential` to **omit** any value because there's nothing about the serialization process that suggests, "this value will be serialized and also optimized of redundancies."

The goal of the serialization methods was to reduce the complexity of transforming a response to `.create()` or `.get()` to help get it from the front end to the back end. It was never intended to address any of the issues higher up the type hierarchy about redundant values. I don't think it would help the adoption of the JSON serialization methods either if they became perceived as somehow "flawed" because people looked at the output and think, "this is missing `rawId`...what else might it not be serializing?"
