### ISSUE TITLE
Deprecate rp.name

### ISSUE THREAD

**Issue by nsatragno** [w3c/webauthn#2121]
## Proposed Change

Remove, deprecate, or ignore `PublicKeyCredentialRPEntity.name`. It's not used by any credential provider that I know about.

This might be tricky because it's inherited from `PublicKeyCredentialEntity.name`.

**Comment by emlun** [comment]
Summary of the discussion on the 2024-08-14 WG call:

- https://github.com/w3c/webauthn/pull/2093#issuecomment-2282813017 currently doesn't have a field for updating `rp.name`, and it seems inconsistent to allow updating some `otherUI` fields but not others.
- No known client implementation actually uses `rp.name` in any meaningful way.
- `rp.name` is arguably the "most phishable part" of WebAuthn, as unlike `rp.id` it's not subject to any security checks.
- For these reasons, we don't really want to include an update signal for `rp.name`.
- Another way to resolve the inconsistency is to deprecate/remove `rp.name` instead.

**Comment by emlun** [comment]
As also mentioned in the discussion, we probably can't actually _remove_ `rp.name`, or make it optional, since it's required in L1 and L2. Both of those changes would create a trap where RPs don't include `rp.name`, since it's not required, but when that code happens to run in an L1 or L2 client it would raise a `TypeError` since the attribute is required in that version.

Instead, there was consensus on the call in favour of simply changing the definition and description of `rp.name` to "unused and meaningless, but still required for backwards compatibility, so just set it to empty string".

**Comment by pascoej** [comment]
The iCloud Keychain credential provider does use user.name and displays it instead of user.displayName for credentials. I don't think displayName is ever used though.

**Comment by nicksteele** [comment]
General sentiment from the 2024-9-11 call seemed to be in favor of deprecation

**Comment by emlun** [comment]
2024-09-11 WG call: Hearing consensus in favour of deprecating `rp.name`. @emlun to write a PR.

@zacknewman has a fair point that empty string may not be an entirely safe fallback value. We don't know of any clients that actually enforce the nickname profile, but still.

**Comment by timcappalli** [comment]
2024-09-18 call: instead of deprecating or making optional, add some text stating many clients will not display the value and to pass either the RP ID again, or an empty string. Also update passkeys.dev guidance.
