### ISSUE TITLE
Enforce strict same-origin policy on rpId

### ISSUE THREAD

**Issue by AngeloKai** [w3c/webauthn#241]
Hi everyone! I am a new PM at Edge. I work with Rob and @vijaybh 

The current spec sets the rpId to the caller’s origin by default and enables callers to explicitly set rpId to a broader scope no larger than the eTLD+1. In most cases, subdomains of the same eTLD+1 are indeed operated and controlled by the same entity. Thus credentials can be shared across subdomains. However, in certain cases, such as hosting sites, the subdomains may be operated by different entities and credentials generated by different domains shouldn’t be shared. Strict same origin policy should be enforced here so that credentials generated by one domain can only be used by that domain. 

Although adoption may be slightly hindered because some RP want to deploy across origins, we could always open up the policy if needed. It is a convenience rather than necessity. If we give callers the privilege to specify RP ID, we cannot take back the privilege later. 

Therefore, I proposed that we remove rpId from the IDL of ScopedCredentialOptions.

**Comment by equalsJeffH** [comment]
Hi Angelo, 

We have discussed/debated this design point several times already and have landed on the present spec language. 

Rather than regurgitate the arguments in-total, please allow me to point you to relevant portions of the immediately prior occurrence:

Re: wrt deprecating eTLD+1 (was: Can we remove the PSL dependency?)  @balfanz 
https://lists.w3.org/Archives/Public/public-webauthn/2016Aug/0045.html

RE: Can we remove the PSL dependency?    @vijaybh 
https://lists.w3.org/Archives/Public/public-webauthn/2016Jul/0331.html

W3C TAG: Review Web Authentication spec 
https://github.com/w3ctag/spec-reviews/issues/97#issuecomment-175766580  @balfanz 

Many of us feel that scoping webauthn credentials strictly to same web origins will unduly hinder deployability (e.g. see @balfanz's detailed comment immediately above).

**Comment by equalsJeffH** [comment]
see also this new comment (https://github.com/w3ctag/spec-reviews/issues/97#issuecomment-257799820) on "W3C TAG: Review Web Authentication spec" that is explicitly about this issue and the TAG is ok with use of eTLD+1 as it is presently specified.

**Comment by equalsJeffH** [comment]
may we close this issue?

**Comment by AngeloKai** [comment]
I am taking some time to discuss this issue with other Microsoft colleagues. I will get back to you as soon as I can. @equalsJeffH

**Comment by AngeloKai** [comment]
@equalsJeffH I have discussed with my colleagues. For site adoption purpose, let's keep the change. Please close the issue.
