### ISSUE TITLE
It would be nice if the definition of "Scoped Credential" said something about what `identifier` and `type` are

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webauthn#248]
https://w3c.github.io/webauthn/#scoped-credential doesn't really say anything about what the members of the pair are, just what the scoped credential identifies...

**Comment by equalsJeffH** [comment]
good point. also, we need to refine our notion of scoped credential type, see #116

**Comment by nadalin** [comment]
@equalsJeffH If no longer valid please close

**Comment by AngeloKai** [comment]
From reading the current text, it seems really clear. The text is here: https://w3c.github.io/webauthn/#iface-pkcredential: 

[[type]]
The PublicKeyCredential interface object's [[type]] internal slot's value is the string "public-key".
Note: This is reflected via the type attribute getter inherited from Credential.

type, of type DOMString, readonly 
This attribute’s getter returns the value of the object’s interface object's [[type]] slot, which specifies the kind of credential represented by this object.

[[type]] 
The Credential interface object has an internal slot named [[type]], which unsurprisingly contains a string representing the type of the credential. The slot’s value is the empty string unless otherwise specified.
Note: The [[type]] slot’s value will be the same for all credentials implementing a particular interface, which means that developers can rely on obj.type returning a string that unambigiously represents the specific kind of Credential they’re dealing with.

[[discovery]]
The PublicKeyCredential interface object's [[discovery]] internal slot's value is "remote".
[[identifier]] 
This internal slot contains an identifier for the credential, chosen by the platform with help from the authenticator. This identifier is used to look up credentials for use, and is therefore expected to be globally unique with high probability across all credentials of the same type, across all authenticators. This API does not constrain the format or length of this identifier, except that it must be sufficient for the platform to uniquely select a key. For example, an authenticator without on-board storage may create identifiers containing a credential private key wrapped with a symmetric key that is burned into the authenticator.

**Comment by equalsJeffH** [comment]
agreed this is now clear and we can close this.
