### ISSUE TITLE
There is no "current settings object" in algorithm steps that are executing in parallel

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webauthn#254]
https://w3c.github.io/webauthn/#dom-webauthentication-makecredential step 3 is using "current settings object's origin" in an algorithm step that is running async and hence no concept of "current settings object".  Note that async steps may also be running on separate execution threads, where settings objects, and origins, aren't even accessible.   Whatever work is done with settings objects and origins needs to be done before going async.

**Comment by bzbarsky** [comment]
This applies to https://w3c.github.io/webauthn/#getAssertion step 3 too.

**Comment by equalsJeffH** [comment]
(finally) assigned myself to this one since I've been planning to work on this - in part because our (inappropriate) use of `current settings object` is my doing :)

I attempted to also assign @jyasskin, but he is not showing up in the pick list for assignees.

**Comment by equalsJeffH** [comment]
part of the issue may also be that you are not (yet) officially a webauthn wg participant? c.f.: https://www.w3.org/2000/09/dbwg/details?group=87227&public=1

**Comment by vijaybh** [comment]
Fixed by #371

**Comment by equalsJeffH** [comment]
re-opening since the alignment-with-credman work we did in PR #384 and subsequently has violated @bzbarsky's assertion in the orig post (OP) above that "Whatever work is done with settings objects and origins needs to be done before going async."

credman's [Create a `Credential`](https://w3c.github.io/webappsec-credential-management/#algorithm-create) and [Request a `Credential`](https://w3c.github.io/webappsec-credential-management/#algorithm-request) algorithms "go async" (i.e., invoke [=in parallel=]) before calling into webauthn's [Create a new credential](https://w3c.github.io/webauthn/#createCredential) and [Use an existing credential to make an assertion](https://w3c.github.io/webauthn/#getAssertion) algorithms (respectively)

Do we indeed have an issue here?  

/cc @bzbarsky @domenic @jyasskin @mikewest

**Comment by bzbarsky** [comment]
Yes, you need to grab any information like that before going parallel, in general.

**Comment by equalsJeffH** [comment]
this issue is in general relevant to issue #472

**Comment by equalsJeffH** [comment]
see also new relevant section in HTML spec: https://html.spec.whatwg.org/multipage/webappapis.html#event-loop-for-spec-authors

**Comment by nadalin** [comment]
Maybe move this to WD07

**Comment by equalsJeffH** [comment]
moved to WD-07

**Comment by equalsJeffH** [comment]
I believe this will be fixed by pr #498

**Comment by equalsJeffH** [comment]
actually, PR #498 just "improves" on this issue (ie it resolves it in the context of the #createCredential section) because the #getAssertion section still has this issue, and it will be updated in a yet-to-be-created PR, and issue #254 will be fully fixed by the latter PR.
