### ISSUE TITLE
Need to clearly define what it means to SHA-256 hash the "host" output of the document.domain setter

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webauthn#258]
The output is a Unicode string.  SHA-256 takes bytes as input.  The exact conversion of Unicode to bytes here needs to be defined.

This can be sort of guessed at, because I _think_ the actual string involved will always be in the ASCII range.  But I'm not 100% sure, and it would be best to eliminate the guessing.

**Comment by equalsJeffH** [comment]
given that the "host" output of the document.domain setter has been processed by https://url.spec.whatwg.org/#concept-host-parser and the unicode flag is unset (because it is not explicitly set in the document.domain setter (yes?)) the "host" output is a _asciiDomain_  AFAICT

see also the discussion with @annevk in #178

**Comment by bzbarsky** [comment]
Right, but the point is that it's still a Unicode string that happens to only contain characters in the ASCII range.  So you have to define how to convert it to bytes that are then hashed.  Is it UTF-8 encoded?  UTF-16 encoded?  UTF-32 encoded?  Something else?

**Comment by annevk** [comment]
Yeah, you probably want to invoke "UTF-8 encode" as defined at https://encoding.spec.whatwg.org/#utf-8-encode.

**Comment by jcjones** [comment]
Not actually closed by #307. Reopening.

**Comment by vijaybh** [comment]
Fixed by #371
