### ISSUE TITLE
Exception handling in cryptoParameters processing needs to be clarified

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webauthn#264]
The "normalizing an algorithm" steps called by https://w3c.github.io/webauthn/#dom-webauthentication-makecredential can throw exceptions of various sorts.  It _sounds_ like these exceptions do not cause `makeCredential` to throw the corresponding exception; instead the next entry in the list is considered.  But what happens to the exception?  Is it simply caught?   Is it reported (e.g. to the window's error event listeners and to the developer console)?  Something else?

This needs to be specified, since the exception is not just propagating out.

**Comment by equalsJeffH** [comment]
Can you point to examples of how to address this concern?  At first glance, given https://heycam.github.io/webidl/#es-handling-exceptions, webauthn can only state in prose whether exceptions are caught or passed to the caller -- yes?

**Comment by bzbarsky** [comment]
Yes, prose is the only way to do this at the moment.  Ccing @domenic in case there's something I'm not aware of, either in existence or planned.

**Comment by AngeloKai** [comment]
If the normalization process creates an issue, the exception should lead to the promise rejected. If the algorithm cannot be normalized, the underlying crypto work cannot be done and no key can be returned.  @equalsJeffH What do you think?

**Comment by vijaybh** [comment]
@AngeloKai are you suggesting that the promise should be rejected if all the algorithms fail normalization, or if any one fails? The former may be okay, but the latter seems dangerous - over time there will be new algorithms, and old UAs that do not understand the new things (and therefore fail to normalize them). Similar issues with some algorithms being unavailable in certain geographies or configurations.

**Comment by vijaybh** [comment]
Fixed by #347, which changed the pertinent text to:

Let normalizedAlgorithm be the result of normalizing an algorithm [WebCryptoAPI], with alg set to current.algorithm and op set to "generateKey". If an error occurs during this procedure, then continue.

**Comment by bzbarsky** [comment]
@vijaybh So is the behavior that if normalizing fails you ignore that and press on somehow?

**Comment by vijaybh** [comment]
Yes. To be more complete, the intention is:
- Algorithms need not be specified by the RP, if it is happy to deal with the default settings of clients and maybe break in unusual cases. So if no crypto parameters are specified, things should still just work.
- However, if an RP specifies algorithms, then it clearly cares about which algorithms it gets. In this case the client should try not to return something that does not fit the RP's specified parameters.

So, when processing algorithms in the case that the RP has actually specified some:
- If normalizing an algorithm fails, just ignore it and go to the next one. There will be new algorithms over time so it is not that unlikely there will be an algorithm the client does not understand.
- If none of the algorithms could be normalized, then we have zero intersection between what the RP wants and the client can do. In this case we should fail. Otherwise, the client should just use one of the algorithms it understands.

Of course we still have issue #267 to clean up this text, but I'm sure the wording can be improved further. Any suggestions or pointers would be welcome.
