### ISSUE TITLE
excludeList/allowList can be defaulted to a zero-length sequence in IDL instead of prose

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webauthn#268]
Instead of having https://w3c.github.io/webauthn/#dom-webauthentication-makecredential step 6 say

> If excludeList is undefined, set it to the empty list.

it would probably be better to have the IDL for the `ScopedCredentialOptions` dictionary say:

    sequence<ScopedCredentialDescriptor>  excludeList = [];

so you don't have to worry about this situation in prose at all.

**Comment by bzbarsky** [comment]
This applies to the allowList member of AssertionOptions too.

**Comment by equalsJeffH** [comment]
**reopening because:** `excludeList` aka `excludeCredentials` (along with `allowList` aka `allowCredentials`) was defined as defaulting to a zero-length sequence in commit https://github.com/w3c/webauthn/commit/8963f2144585bc435e0b4d22b4cbf2ab2d391f2d, but the ` = []` was dropped from `excludeCredentials` in some recent commit.  We need to fix it.

**Comment by equalsJeffH** [comment]
I queued the fix for this in PR #495
