### ISSUE TITLE
Why are various predefined extensions defined as extensions, and not just parts of the spec?

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webauthn#295]
Is this because they are allowed to not be supported?

**Comment by equalsJeffH** [comment]
yes.  [ e.g., see https://lists.w3.org/Archives/Public/public-webauthn/2016Sep/0110.html ]

**Comment by selfissued** [comment]
As we discussed in the F2F, it's a business decision which extensions to support.  They're extensions because supporting them is optional.

FYI, https://github.com/w3c/webauthn/pull/386 should make it a lot clearer how to define and register new extensions.  It makes it clear that the initially defined ones are not somehow "special".

**Comment by equalsJeffH** [comment]
Overall, a +1 to @selfissued's (mike jones) explanation, although to be fair, there are arguments that some of the "extensions" should not be "extensions" and should be incorporated directly into the spec. Rolf @rlin1 made this point in the last F2F.

**Comment by selfissued** [comment]
I believe that this issue asked a question that has been answered and proposes no changes to the specification.  I am therefore closing it on this basis.  New issues can be filed that do propose specific changes, if desired.
