### ISSUE TITLE
Propose procedure for adding to attestation/extension registry

### ISSUE THREAD

**Issue by gmandyam** [w3c/webauthn#303]
Need to determine what such procedures are and where they will be documented.  The Webauthn WG homepage could be a candidate for where the documentation could live:  https://www.w3.org/Webauthn/.

Regarding the actual text, would recommend something similar to https://www.w3.org/TR/mse-byte-stream-format-registry/#entry-requirements, with some changes:

For a proposed attestation format or extension to be added to the registry, the proposer must follow these guidelines:
a) The proposed attestation format or extension must have a unique type identifier.  
b) The proposer must provide a link to a publicly-available specification that describes the attestation format or extension.
c)  The proposer must announce the proposed attestation format or extension on public-webauthn@w3.org.

A designated set of experts (assigned by the W3C) will review the proposal and make a final determination on inclusion in the registry.  The decision on whether to include the proposal in the registry along with a justification will be provided on webauthn@w3.org no later than 60 days after the proposal announcement.

**Comment by equalsJeffH** [comment]
Overall this seems fine as a starting point to me, thanks for writing it up.  I only have some detail-level polishing thoughts at this time (will write them down anon). thx.

**Comment by selfissued** [comment]
The registration procedures were refined in https://github.com/w3c/webauthn/pull/386.

**Comment by gmandyam** [comment]
@selfissued 

The proposed text was meant to outline how expert review would proceed in the W3C context.  Can the IESG delegate expert review to W3C?

**Comment by selfissued** [comment]
The designated experts for the IANA review can be appointed in consultation with the W3C.  I'll talk with Kathleen Moriarty, the security area director who I expect will sponsor the draft, next week during the IETF meeting about making this happen.

**Comment by nadalin** [comment]
@selfissued what is the status of this and the IETF ?

**Comment by nadalin** [comment]
@selfissued Has this been done, if so please close

**Comment by equalsJeffH** [comment]
[draft-hodges-webauthn-registries](https://tools.ietf.org/html/draft-hodges-webauthn-registries) defines two to-be-created IANA registries:
1. [WebAuthn Attestation Statement Format Identifier Registry](https://tools.ietf.org/html/draft-hodges-webauthn-registries#section-2)
2. [WebAuthn Extension Identifier Registry
](https://tools.ietf.org/html/draft-hodges-webauthn-registries#section-3)

[WRT](https://en.wiktionary.org/wiki/with_respect_to#English) the selection and appointment of Designated Experts, [draft-hodges-webauthn-registries-01](https://tools.ietf.org/html/draft-hodges-webauthn-registries-01) says in both of the above-cited sections:

> [identifiers] are registered on the advice of a Designated Expert (appointed by the IESG **_or their delegate_**) ...  [emphasis added]

..so the details of appointing the DEs can be negotiated with the IETF Area Directors (who make up the [IESG](https://www.ietf.org/about/groups/iesg/)) by WebAuthn WG folk in company with W3C Team folk. I think [draft-hodges-webauthn-registries](https://tools.ietf.org/html/draft-hodges-webauthn-registries) is as specific as it needs to be about this. Perhaps @selfissued has some news on this (see also his above https://github.com/w3c/webauthn/issues/303#issuecomment-288259448) from the recent IETF-101 London.

WRT:
> For a proposed attestation format or extension to be added to the registry, the proposer must follow these guidelines: [...]

..from the [original post (OP)](https://github.com/w3c/webauthn/issues/303#issue-192987442) above, [draft-hodges-webauthn-registries-01](https://tools.ietf.org/html/draft-hodges-webauthn-registries-01) says in both of the above-cited sections:
> The Expert(s) will establish procedures for requesting registrations, and make them available from the registry page.

The only aspect of the guidelines proposed by @gmandyam in the [OP](https://github.com/w3c/webauthn/issues/303#issue-192987442)  that are not already addressed in [draft-hodges-webauthn-registries-01](https://tools.ietf.org/html/draft-hodges-webauthn-registries-01) is this one:
> c) The proposer must announce the proposed attestation format or extension on public-webauthn@w3.org.

..which we can have the DEs address in the registration request procedures they will post on the registry page.  We _may_ be able to put that requirement (c) directly into  [draft-hodges-webauthn-registries](https://tools.ietf.org/html/draft-hodges-webauthn-registries), tho I am unsure how palatable that will be for IESG reviewers. 

Other than that minor item, I think this issue is addressed.

**Comment by selfissued** [comment]
Once the registry is establish, I propose that we ask the IESG to appoint @equalsJeffH and @selfissued as the designated experts, as both are familiar with registry mechanics in general and the specifics of these particular registries and their relationship to the WebAuthn spec.  On that basis and Jeff's analysis above, I believe that this issue is ready to close, so as not to continue taking up working group time.
