### ISSUE TITLE
Can we get rid of the "Web" prefix for WebAuthnAttestation, etc?

### ISSUE THREAD

**Issue by kpaulh** [w3c/webauthn#310]
With respect to "WebAuthentication", "WebAuthnAttestation", "WebAuthnAssertion", etc. (not the overall name WebAuth). It seems to be unusual for Web APIs in general.

**Comment by equalsJeffH** [comment]
related to #288

**Comment by zcorpan** [comment]
How is this editorial? Renaming interfaces is a normative change.

**Comment by equalsJeffH** [comment]
Well, we are considering it "editorial" at this time, amongst the spec editors, because the spec is only a working draft, and such a change is presently trivial to accomplish for us (e.g., it can presently be accomplished with `sed`).   We understand that from other perspectives, such as implementors, issues that we've labeled "editorial" may not necessarily be viewed as such.

**Comment by equalsJeffH** [comment]
fixed by pr #317 https://github.com/w3c/webauthn/commit/6267cc1e81ae9999f11d75f37b4f9a3b558ce6dc
