### ISSUE TITLE
Consider removing the "n" in "WebAuthnAttestation", etc

### ISSUE THREAD

**Issue by kpaulh** [w3c/webauthn#311]
Reason being that it's easy for developers to overlook and could be a general annoyance. The distinction between (authn) and (authz) is important, but wouldn't referencing the spec provide that clarification?

**Comment by equalsJeffH** [comment]
I disagree -- people/developers/archtects/everyone confuse "authentication" and "authorization", and regard "auth" as either or both, often regardless of context.  Note also that the official short name of both the working group and the spec is "WebAuthn".   To me, the main issue is whether we spell out "authentication" in the webauthn api names or not, and to me that is mostly a matter of taste.

**Comment by equalsJeffH** [comment]
see #288

**Comment by nadalin** [comment]
I agree with Jeff

**Comment by arshadnoor** [comment]
And, what about the confusion that's going to result from the fact that the "Authentication" protocol enables "transaction confirmation" aka "transaction authorization"?  How does the specification anticipate addressing that?  You do realize that attorneys are going to want clarification on whether "transaction confirmation" === "authorization".

**Comment by nadalin** [comment]
This API is strictly about Web Authentication the implementations may or may not implement transaction confirmation, so that is out of scope

**Comment by zcorpan** [comment]
I would suggest resolving this by removing "Web" from all API names and spelling out "Authentication" everywhere. 🙂

**Comment by arshadnoor** [comment]
> This API is strictly about Web Authentication the implementations may or may not implement transaction confirmation, so that is out of scope

It seems to me that this is starting go down the well-trodden path of PKI.  

The authentication part of the spec is "mandatory", but even though [transaction authorization](https://www.w3.org/TR/2016/WD-webauthn-20160531/#extension-txauth) is part of the same spec, it is optional?  So, between Authenticators that can choose to implement what they want, servers that can choose to implement what they want and platforms/browsers in-between that can choose to implement what they want, WebAuthn Relying Parties are going to be in the same pickle that PKI RPs are in - different parts of the ecosystem that will **not** interoperate unless you buy/choose everything from the same or an extremely limited set of manufacturers.  So, what would be the point of the standard?  We had RFC 5280 as a standard for two decades; do you see many people using TLS ClientAuth - just _ClientAuth_ and not any of the extensions - to solve authentication problems?  (Arguing that hundreds of millions of Client digital certificates have been issued worldwide is not the right answer).

It would seem to me that we should learn from past PKI mistakes and correct course for the future.  For nearly three years, I had argued for keeping **all** extensions **out** of the [FIDO] spec; since that is not to be, I will now argue that defined extensions be made mandatory so RPs will  have the assurance that all parts of the ecosystem will work together regardless of whose component they choose.  Anything less will only lead RPs down the PKI garden-path again.

**Comment by equalsJeffH** [comment]
Hi @arshadnoor  -- your points are tangential to this particular issue and are more appropriate for #290

**Comment by arshadnoor** [comment]
Will take it there for future comments, equalsJeffH.

**Comment by equalsJeffH** [comment]
See PR #317

**Comment by equalsJeffH** [comment]
fixed by pr #317 https://github.com/w3c/webauthn/commit/6267cc1e81ae9999f11d75f37b4f9a3b558ce6dc (per @zcorpan 's suggestion https://github.com/w3c/webauthn/issues/311#issuecomment-269247084 above)
