### ISSUE TITLE
Explain how Token Binding IDs get associated with an HTML context.

### ISSUE THREAD

**Issue by jyasskin** [w3c/webauthn#360]
This is probably a change for HTML or https://tools.ietf.org/html/draft-ietf-tokbind-protocol, but it's not clear to me how a [Token Binding ID](https://tools.ietf.org/html/draft-ietf-tokbind-protocol-13#section-3.2) becomes available for an origin or `Document` or settings object.

**Comment by equalsJeffH** [comment]
Well, it is not a change appropriate for [draft-ietf-tokbind-protocol](https://tools.ietf.org/html/draft-ietf-tokbind-protocol), since that spec does not delve into user agent implementation particulars (tho it does mention this use case in [section 5](https://tools.ietf.org/html/draft-ietf-tokbind-protocol-13#section-5) 2nd paragraph). We might also reference [draft-ietf-tokbind-https](https://tools.ietf.org/html/draft-ietf-tokbind-https), but it does not answer this user agent-specific question, so may not be appropriate for this spec to reference(?). 

In nosing around, it seems to me that, yes, we should perhaps add something to the HTML spec, and given that an [environment settings object](https://html.spec.whatwg.org/multipage/webappapis.html#environment-settings-object) has an [HTTPS state value](https://fetch.spec.whatwg.org/#concept-https-state-value), perhaps we should propose adding an HTTPSProperties interface of which an attribute is the Token Binding ID (if any) for the underlying TLS connection?

**Comment by jyasskin** [comment]
Yes, collecting the Token Binding ID during https://fetch.spec.whatwg.org/#http-network-fetch and adding it to the response object and thence to the settings object sounds reasonable. I'll file a bug against Fetch and CC you. Anne may want you to write the actual change.

**Comment by jyasskin** [comment]
Ah, and https://github.com/whatwg/fetch/pull/325 is already taking care of this.

**Comment by equalsJeffH** [comment]
@jyasskin speaks truth in https://github.com/w3c/webauthn/issues/360#issuecomment-286560204 -- will do

**Comment by equalsJeffH** [comment]
wrt https://github.com/w3c/webauthn/issues/360#issuecomment-286560204
unfortunately, those aspects of whatwg/fetch#715 (formerly whatwg/fetch#325) appear to have been lost, see also: https://github.com/whatwg/fetch/pull/715#pullrequestreview-140826499

**Comment by selfissued** [comment]
Who can take ownership of the Fetch additions and get them to complete?
