### ISSUE TITLE
UVM Extension Editorial Change

### ISSUE THREAD

**Issue by apowers313** [w3c/webauthn#368]
The [UVM Extension](https://w3c.github.io/webauthn/#uvm-extension) text currently includes the following:

> **Authenticator processing**
The authenticator augments the authenticator data with a user verification index indicating the method used by the user to authorize the operation, as defined below. This extension can be added to attestation objects and assertions.

Note the mention of `user verification index`, which was probably copied from the UVI extension. I'm not sure if the fix is as simple as changing `index` to `mode` or if the whole section should be re-written.

**Comment by selfissued** [comment]
Note that PR #389 changed "mode" to "method", fixing issue #411 .  I understand that this doesn't address the confusion between "index" and "method".  The owner of this extension ( @rlin1 ?) should review the text and propose a fix.

**Comment by equalsJeffH** [comment]
good catch @apowers313, thx.

I propose this fix:
The [=authenticator=] sets the [=authenticator extension output=] to be a `uvmFormat` structure indicating (any or all of) the user verification method employed for the [=authorization gesture=], the [=authenticator=]'s key protection type and/or matcher protection type.

[ I am now guessing that @rlin1 had named this extension "user verification mode" (rather than UV "method") because it can convey more information that just the UV Method employed. ]

**Comment by selfissued** [comment]
Sounds fine to me

**Comment by nadalin** [comment]
@selfissued @rlin1 please create a PR and merge

**Comment by rlin1** [comment]
see https://github.com/w3c/webauthn/pull/675

**Comment by equalsJeffH** [comment]
this was fixed by PR #675 as noted by @rlin1 https://github.com/w3c/webauthn/issues/368#issuecomment-343253059. Closing.
