### ISSUE TITLE
Justify differences in TPM Attestation Verification procedures in WebAuthn versus TCG specifications

### ISSUE THREAD

**Issue by gmandyam** [w3c/webauthn#372]
As per reference [TPMv2-Part1], Section 31.2, a 'Standard Attestation Structure' is defined.  Several of the defined fields are not reflected in verification procedures (e.g. QualifiedSigner, clockInfo, firmwareVersion) in Sec. 7.3 of Webauthn (WD-04).  The text should at least highlight why a verifier can ignore these fields, and whether an attestation without these fields should be considered invalid.

**Comment by nadalin** [comment]
@selfissued Maybe reference the TCG Specifications, see @akshayku for details

**Comment by selfissued** [comment]
@akshayku Where do we stand on finishing this?  This is in the CR milestone.

**Comment by akshayku** [comment]
@selfissued I will definitely try to do it this week.

**Comment by akshayku** [comment]
Finally I got to look at this issue and the reason why those fields are missing is because those fields are not really actionable in itself. We are ignoring all these fields. 

QualifiedSigner and clockInfo don't really have to be checked and normal consumption of these attestation in the fields usually ignore it. Similarly firmware version is something that we cannot give guidance on which one to use and which one to not. 

At best, these fields are signals to risk engine and RP MAY choose to look at these in some risk engine situation but there is no actionable verification steps that we can specify here.

**Comment by selfissued** [comment]
Thanks for doing this analysis, @akshayku .  Can you please write a PR that puts this analysis in a note in an appropriate place in the spec so that this rationale is made available to readers and implementers of the specification?  That should let us close this issue out.  Thanks.

**Comment by akshayku** [comment]
Opened #791

**Comment by gmandyam** [comment]
I believe https://github.com/w3c/webauthn/pull/791 is very helpful and clarifies the TPM verification procedures.  I am in favor of merging the PR and closing this issue.
