### ISSUE TITLE
restrict WebAuthentication API to only top level browsing context

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#374]
as @AngeloKai noted in https://github.com/w3c/webauthn/issues/271#issuecomment-271049709 the [Credential Management API](https://w3c.github.io/webappsec-credential-management/) is restricted to only [top level browsing contexts](http://www.w3.org/TR/html5/browsers.html#top-level-browsing-context) (as well as secure contexts). This is arguably applicable to WebAuthn API.

**Comment by AngeloKai** [comment]
I chatted briefly with @bifurcation about this in our last F2F. The challenge will be Google is using iframe to enable certain login scenario. @mikewest how would that be addressed?

**Comment by mikewest** [comment]
> The challenge will be Google is using iframe to enable certain login scenario.

I'm not familiar enough with Google's U2F usage to comment on how/why `<iframe>` is used; @balfanz will certainly have more context there.

Are the frames same-origin? Same-eTLD+1?

> How would that be addressed?

We locked the credential management API to top-level contexts because we have no idea how to inform a user about the origin of frames. That is, it's difficult to explain to users what's going on when `doubleclick.net` asks for credentials (or asks to store credentials) from inside `example.com`. They see `example.com` in the address bar, that's the origin with which they're creating a trust relationship, but they're handing credentials to someone else. *shrug* It isn't at all a deep, philosophical opposition to the idea, but a practical "We don't know how to do this" feature we punted to The Distant Future(tm).

The Web Payments group has made different choices with their API, rendering UI that attributes the request to the top-level origin (with the justification that the top-level origin is what the user trusts, and that it's delegating the permission to the framed document via a content attribute on the frame element). I'm not sure that's a reasonable model for this API, but perhaps it is?

/cc @zkoch, @battre as an FYI.

**Comment by battre** [comment]
I think that, for the same reasons, in today's U2F implementation that is used at Google, the registration and attestation can only be triggered by the mainframe as well.

**Comment by selfissued** [comment]
This restriction may be one we want to make but it will be a breaking change for some use cases whenever we do it.  If we're going to do this, we almost certainly therefore want to do it before the Implementer's Draft.

**Comment by jyasskin** [comment]
@clelland is working on [Feature Policy](https://wicg.github.io/feature-policy/) to give the top-level frame the ability to selectively grant APIs to its children. If you restrict WebAuthn to the top-level frame now, that lets you migrate to the more explicitly-permissive world in the future, whereas if you leave it totally open, backward compatibility will make it hard to establish the more restrictive default when Feature Policy is more widely supported.

It's likely also safe to allow same-origin iframes access now.

**Comment by mikewest** [comment]
> @clelland is working on Feature Policy to give the top-level frame the ability to selectively grant APIs to its children. If you restrict WebAuthn to the top-level frame now, that lets you migrate to the more explicitly-permissive world in the future, whereas if you leave it totally open, backward compatibility will make it hard to establish the more restrictive default when Feature Policy is more widely supported.

I'd still like to understand what UI folks would be interested in presenting?

> It's likely also safe to allow same-origin iframes access now.

I agree. There's no UI question if the origins are identical. We could probably extend this to eTLD+1 by rendering the registerable domain in the UI.

Would that be enough for y'all?

**Comment by equalsJeffH** [comment]
Given that as of merging of PR #384 webauthn depends upon credman -- [which is (presently) restricted to top-level browsing contexts](https://w3c.github.io/webappsec-credential-management/#security-origin-confusion) -- shall we close this issue?

**Comment by AngeloKai** [comment]
@equalsJeffH I agree now that webauthn depends upon credman, which is restricted to top-level browsing context, webauthn should be restricted in the same way. However, this restriction appears to be an accidental by-product of the merge rather than a deliberate product. I'd feel much more comfortable closing this issue after we talked it through on the WG call and everyone is on the same page. 

When we discussed the issue, we should keep the other issue regarding migration of keys in mind: https://github.com/w3c/webauthn/issues/458. At the moment, corp acquiring another company can still get their keys through iframe. The restriction will keep this possibility out. Since I posted the issue, I also heard of conversations from IDPs which whitelists a set of domains which can iframe into the IDP sites. This would be concerning for these IDPs. 

Based on the above conversations, it appears more conversation may still happen even after we restrict webauthn to top browsing context, including limiting the API to Feature Policy, granting access to same-origin iframe access, etc. If so, we can close this issue and open up another one to track the conversations about exception to the restrictions.

**Comment by equalsJeffH** [comment]
@AngeloKai thanks for your thoughts and the reference to relevant issue #458 

> If we do decide on the [top-level browsing context] restriction approach...

Well, my point is that this _is_ already "decided" in the sense that [credman](https://w3c.github.io/webappsec-credential-management/) is (presently) restricted to top-level browsing contexts ([see the security considerations here](https://w3c.github.io/webappsec-credential-management/#security-origin-confusion)), so as a practical matter, I suggest further discussion of "relaxing" the "top-level browsing context restriction" and potential restriction relaxations  (in the context of both [credman](https://w3c.github.io/webappsec-credential-management/) and webauthn) ought to be done over in the credman issue in w3c/webappsec-credential-management#3

**Comment by AngeloKai** [comment]
@equalsJeffH Agreed that the spec currently is doing this. It's just that I am not sure everyone in the WG, including the two other browser folks, actually know that the spec currently says this. @nadalin perhaps this is something we should bring up at the next WG call. 

In the meantime, I am fine with closing this issue and move on to discussion in the credman spec repo. Should we also open another issue in this spec repo that corresponds to the credman issue? My concern is that decisions-making in the credman repo ends up impacting the WebAuthn spec without the folks here knowing about it. I guess there's a discussion about how this workflow should work to be had. Perhaps moving the credman spec to this WG? I am not familiar with W3C process to figure out how much complexity doing this way will be.

**Comment by AngeloKai** [comment]
@mikewest to the thread

**Comment by AngeloKai** [comment]
I am moving the issue back to WD-07 because of the priority:implementation tag. I am not sure everyone in the WG is aware of the fact that our APIs are restricted to top level domain now.

**Comment by nadalin** [comment]
@equalsJeffH so do we close this with no action and punt over to credman ?

**Comment by equalsJeffH** [comment]
The relevant credman issue is https://github.com/w3c/webappsec-credential-management/issues/3 and discussion has resumed therein.

**Comment by nadalin** [comment]
@equalsJeffH So we keep open but don't act on this

**Comment by AngeloKai** [comment]
@nadalin The CredMan issue discussion has resumed. AFAIK the reason why top level browsing context constraint was added to credman is because CredMan api can exercise silent auth. Considering we don't currently allow silent auth, their attitude is the constraint be removed for webauthn. At least in the Edge implementation, we show the origin of the site in the prompt. By showing the origin, we are giving extra security protection toward the user. I sent @mikewest and @battre a mail containing the UI of the prompt. 

We will likely reach the solution that **webauthn will allow all browsing context and add text that suggests UAs should emphasize the origin of the script in prompt**. Once we reach the solution, we will add text back to the webauthn spec, describing the relaxed constraint and the suggestions to the UAs.

**Comment by leshi** [comment]
@jyasskin, brining you into this.

**Comment by equalsJeffH** [comment]
decision at meeting 11-Oct is to continue discusing this with credman in context of https://github.com/w3c/webappsec-credential-management/issues/3 -- punt to CR milestone for now --  while understanding it may get punted further as appropriate.

**Comment by AngeloKai** [comment]
I recently came across a time-friendly proposal for enabling iframe. We may follow similar approach like https://www.w3.org/TR/payment-request/#paymentrequest-and-iframe-elements. All we need from the implementers is just add a new attribute to iframe and we should be set. We can mark it as non-normative to give time for browser vendors to complete the feature. Once everyone implements it (say in PR time), we can the feature a normative requirement. 

@jcjones @leshi what do you think? Adding @mikewest and @battre to be considered by credman.

**Comment by clelland** [comment]
@AngeloKai -- I've been trying hard to dissuade people from adding additional attributes to `<iframe>` for every new feature, in favor of using the single `"allow"` attribute being defined by [Feature Policy](https://wicg.github.io/feature-policy/).

I'm hoping to give spec authors a consistent, uniform means of controlling access to features in frames, and to give web developers assurances that they don't have to worry about potential subtle differences in how and when features are enabled in different contexts.

**Comment by mikewest** [comment]
I agree with @clelland that adding an attribute to `iframe` is a bad idea.

As I've mentioned a few times, I'm fine with weakening the language in the current credential management spec to allow for the possibility of returning credentials from frames. As I've also mentioned, I see that as more of a UX challenge than a technical one. I have no idea how Chrome would present a credential request from `B.com` inside `A.com`; it's different in kind from payment information, and it's not at all clear to me that the payment solution (mark the UI as though it was coming from the top-level origin) works for credentials.

I'm willing to let that decision be made on a case-by-case basis, though I think it's important that vendors agree on what they're willing to allow.

From @AngeloKai's comments, it sounds like Microsoft thinks this is important. @jcjones, does Mozilla? @leshi / @battre: Does Google?

**Comment by nadalin** [comment]
@selfissued Look into using Feature Policy to allow WebAuthn to use iFrame

**Comment by equalsJeffH** [comment]
NOTE: this issue was _at least_ "improved" by this recent merged-in change to [CredMan](https://w3c.github.io/webappsec-credential-management/):  

  PR w3c/webappsec-credential-management#114 
  "[Remove the blanket restriction against nested usage](https://github.com/w3c/webappsec-credential-management/pull/114)".  

We _could_ declare that this "[sameOriginWithAncestors](https://w3c.github.io/webappsec-credential-management/#same-origin-with-its-ancestors)" approach "fixes" this issue if we feel that RPs do not need the functionality of being able to declare "top-level only" or not, and having [sameOriginWithAncestors](https://w3c.github.io/webappsec-credential-management/#same-origin-with-its-ancestors) as the default functionality is sufficient. 

WDYT?

**Comment by jcjones** [comment]
I thinks will be closed by https://github.com/w3c/webauthn/pull/702 when it has notes discussed in 29 Nov meeting.

**Comment by AngeloKai** [comment]
Agreed. Closing the issue.
