### ISSUE TITLE
[PR 384] Does requireUserMediation() make sense after merge

### ISSUE THREAD

**Issue by leshi** [w3c/webauthn#402]
Once we merge, WebAuthn will inherit `requireUserMediation()` from CredMan.  What does this mean?  How would developers use it?  What would the effect be?  Let's make sure we understand this.

It seems that we would want requireUserMediation() to always be `true` and change it on a per-call basis.  Does that mean that `requireUserMediation()` does different things for different type of credentials?

**Comment by jyasskin** [comment]
Developers won't use `requireUserMediation()` to interact with their public-key credential-sources since #384 doesn't define `[[CollectFromCredentialStore]]`, which is the only way https://w3c.github.io/webappsec-credential-management/#algorithm-request takes advantage of the [`requires user mediation flag`](https://w3c.github.io/webappsec-credential-management/#origin-requires-user-mediation-flag) to skip user mediation.

If a touchless WebAuthn device is ever added, this group would have to decide how it interacts with the `requires user mediation flag`, but that's an issue for a future version of this spec.

**Comment by AngeloKai** [comment]
Adding the milestone tag to the issue. It seems like the circumstances have changed since the last conversation on this one. The CredMan spec changed their API surface. Maybe something was decided during a WG call. If so, should we close the issue? @jyasskin

**Comment by equalsJeffH** [comment]
added [stat:Discuss] label :)

**Comment by AngeloKai** [comment]
Closing the issue and moving the discussion to https://github.com/w3c/webauthn/issues/402 given that requireUserMediation no longer exists.
