### ISSUE TITLE
Rename ScopedCredential to PublicKeyCredential

### ISSUE THREAD

**Issue by jyasskin** [w3c/webauthn#406]
"Scoped" doesn't identify what's unique about WebAuthn credentials, and on the calls, folks seem to be happy with "public key" instead.

For the key in [CredentialRequestOptions](https://w3c.github.io/webappsec-credential-management/#dictdef-credentialrequestoptions), I suggest "publicKey" following the convention for properties in https://w3ctag.github.io/design-principles/#casing-rules.

**Comment by equalsJeffH** [comment]
shucks @jyasskin this was next on my list to submit :)

One of the side effects of integrating with [Credential Management](https://w3c.github.io/webappsec-credential-management) (CredMan) is that we have to acknowledge that there are other types of "scoped credentials" (e.g.: password, federated), and thus the "ScopedCredential" name is not particular to WebAuthn. 
	
In CredMan, the "scoped-to-an-RP" notion is termed "[origin bound](https://w3c.github.io/webappsec-credential-management/#credential-origin-bound)":

>Some Credential objects are origin bound: these contain an internal 
  slot named [[origin]], which stores the origin for which the Credential
  is valid.

..and both "password" and "federated" credentials are also origin bound. 

Keeping with the cred type naming theme in CredMan, perhaps we should rename "ScopedCredential" to "PublicKeyCredential" ?  And have it's value of [[type]] be set to "publickey" ?

Would this be too generic name-wise? I'm not sure wrt to PublicKeyCredentials -- are there types of "public keys" whose generation and signature algorithms /would not/ fit into our algorithmic model?  I.e., are there types of "asymmetric keys and their algorithms" that we may wish to utilize in the future, yet need to be differentiated from "conventional" RSA and ECC, and would it be reasonable to have a type name for them that is different than "publickey" ?  

One possible case are the keys and algs used in so-called "selective disclosure systems" (u-prove and idemix). Perhaps it would be ok to term these as "selectiveDisclosureCreds" if we ever have to cross that bridge...?

**Comment by mikewest** [comment]
If Microsoft is aiming to lock something down in WD-05 that they want to ship, then I'd suggest that this issue is actually somewhat important. It would be unfortunate if Edge shipped `ScopedCredential` and everyone else shipped `PublicKeyCredential` (or whatever).

I do not have strong opinions about the naming, but I do have the strong opinion that we should have the same name across user agents. Given that, is CR an appropriate milestone? Will Edge commit to aligning to any naming changes between now and then? :)

FWIW, I _think_ naming changes are pretty trivial in terms of their impact on browser code (in Blink, we'd rename some `.idl`, `.h`, and `.cpp` files, and do some global search-and-replacing), but I've heard on previous calls that these might not be as trivial as I imagine in other browsers. Hammering this out sooner rather than later seems prudent.

/cc @AngeloKai

**Comment by equalsJeffH** [comment]
OK, see PR #432
