### ISSUE TITLE
RawId vs Id is confusing

### ISSUE THREAD

**Issue by leshi** [w3c/webauthn#412]
Having two credential ID values is confusing.  Do we really need two?

If we only keep one, we are stuck (as a result of the merge) with the String one.  This feels odd as I *think* you don't get a String type when you upload a file, and you don't get a String type when you operate on stuff in webcrypto, and the camera APIs don't return String type, and webbluetooth doesn't operate on Strings...

Also, what the meaning of 'id' seems to be completely different between different Credential types.  That also seems super confusing.

**Comment by jyasskin** [comment]
In https://github.com/w3c/webauthn/pull/384#discussion_r111504620, @mikewest and I were discussing a technical problem where Javascript can use `rawId` to modify the underlying `ArrayBuffer`, at which point the value of `id` becomes ambiguous. Is it the base64url encoding of the original value or the modified value, or does it depend on when the first use of `id` was?

Most options here are bad because we want to guarantee that `foo.rawId`===`foo.rawId` (is the same object each time, not just the same value) and similarly for `.id`. The simplest thing that preserves both values is, when the `ScopedCredential` is created, to store an `ArrayBuffer` for `rawId` and immediately base64url encode it into a DOMString for `id` and also store that. But it'd be even better to be able to remove either `rawId` or `id` to avoid storing the data twice.

**Comment by mikewest** [comment]
We talked about this a little bit before the merge, and I agree that having two attributes is a bit confusing. I can see two ways of resolving that confusion:

1.  We change `Credential::id` to be something like:

    ```
    typedef (ArrayBuffer or DOMString) CredentialIdentifier;
    partial interface Credential {
        CredentialIdentifier id;
    };
    ```

    And then let credential types pick one or the other as they like, enabling `ScopedCredential` to return an `ArrayBuffer` as its `id` and drop `rawId` entirely.

2.  We drop `rawId`, leaving only the `DOMString` serialization of the identifier.

Naïvely, I'd prefer 2: My understanding of the use case for `id` is that it serves as something like the index into a database on the server, and needs to be somehow serialized for transport in any event. Giving developers a canonical serialization seems like a reasonable thing to do, guiding them down a sane path for implementation.

That said, the spec is pretty light on examples around what client-side code should be doing with any of the credential's properties ("Send new credential info to server for verification and registration"). If it really is more useful to have an `ArrayBuffer` (or a view into the same), I'm sure we can work something out.

**Comment by nadalin** [comment]
@leshi All the proposal require breaking changes, so my suggestion is unless there is a non breaking proposal we close this

**Comment by equalsJeffH** [comment]
absent a non-breaking proposal we are just going to close this.
