### ISSUE TITLE
rpID seems to have changed meaning a bit

### ISSUE THREAD

**Issue by leshi** [w3c/webauthn#416]
Previously, the rpID was an optional field that you only overwrite if you want to change the security semantics of how the credential was bound.

However, the rpID has now moved into the `ScopedCredentialEntity` structure:
```
dictionary ScopedCredentialEntity {
    DOMString id;
    DOMString name;
    USVString icon;
};
```

But the general meaning of this structure is "display information for the authenticator account chooser".  It feels like the move resulted in a semantic change from "security knob" to "metadata".

**Comment by mikewest** [comment]
Technically, the field is still optional, so I think it has the same semantics as it used to. That said, I can see how the way it's presented to developers might have shifted in a way that makes it less likely to be used correctly. *shrug* I'm open to recommendations. What would you like to see change?

**Comment by equalsJeffH** [comment]
I have several rpId/origin issues to address, will add this one to my list...(they have percolated up to the top of my stack I'm hoping...)

**Comment by equalsJeffH** [comment]
things were further refined since @leshi submitted this issue, and the RP ID is now conveyed in via `MakeCredentialOptions.rp.id`, and all of `MakeCredentialOptions.rp` is RP-specific, plus, as a part of  PR #464 we have clarified the optionality of setting the RP ID (the default is the caller's effective domain and origin).

**Comment by equalsJeffH** [comment]
things were further refined since @leshi submitted this issue, and the RP ID is now conveyed in via `MakeCredentialOptions.rp.id`, and all of `MakeCredentialOptions.rp` is RP-specific, plus, as a part of  PR #464 we have clarified the optionality of setting the RP ID (the default is the caller's effective domain and origin).  So I assert that we can close this upon merge of PR #464.

**Comment by equalsJeffH** [comment]
this is fixed by PR 464, closing.
