### ISSUE TITLE
Consider allowing authenticators to randomise signed hashes.

### ISSUE THREAD

**Issue by agl** [w3c/webauthn#453]
In order to frustrate differential power analysis, hardware authenticators will typically randomise as many inputs to cryptographic processing as possible. However, as currently constructed, they don't have an obvious way to randomise the hashes to be signed.

If the [authenticator data](https://www.w3.org/TR/2017/WD-webauthn-20170505/#sec-authenticator-data) structure contained an opaque, 16-byte field then authenticators that wished to do so could fill it with random data, thus randomising the hash to be signed. (Those that don't care can fill it with zeros.)

The `signCount` field might have been intended to help with this problem, but since maintaining a count would involve a flash write for each signature, and would leak tracking information, I imagine most implementations would simply set it to zero every time. (Indeed, that field is not mentioned anywhere else in the spec that I can see and might be a candidate for removal.)

**Comment by rlin1** [comment]
When receiving a signatureCounter, the relying party should 
a) compare that the value is greater than the previously stored one and
b) store the new value.

When putting random data in the field, the RP would have to understand when to ignore the counter value.  
This makes it more complicated for the RP.

I propose to close this issue as won't fix.

**Comment by equalsJeffH** [comment]
so @jyasskin notes that: discussion in PR #539 supersedes the discussion in this issue. all decisions are getting made in PR #539

**Comment by AngeloKai** [comment]
I don't see any reason for us to talk about this issue within a W3C web spec. At the end of the day, this spec is a web spec that aims at standardizing the behaviors of the user agents. This spec doesn't attempt to standardize or define the hardware design. Please, if you want to talk about hardware design, go talk about it in CTAP land, in U2F land, or in UAF land. @agl @rlin1 @equalsJeffH 

The spec will **describe** what the authenticators' fields mean and the differences between the different authenticators. But that doesn't mean we make design decisions here. 

We should close the issue asap to avoid distraction since the ask here is to re-do hardware interface design (like by next Tuesday).

**Comment by agl** [comment]
> We should close the issue asap to avoid distraction since the ask here is to re-do hardware interface design 

Isn't webauthn the source of things like section 9.3 (Generic Transaction Authorization Extension), and 9.7 (Location Extension)? If these sections are echoing things defined elsewhere then I have misunderstood the relation between the specs. But if webauthn is defining things that can be signed then saying "there should be something arbitrary so that tokens can randomise inputs" is related.

Although I do agree that if the specific idea of describing the signature counter as arbitrary is rejected (as it appears from #539 ) then this gets more complex, probably involves an extension and can be worried about in the future.

**Comment by AngeloKai** [comment]
@agl At the end of the day, the WebAuthn spec is a web spec and should only define the web interface. Defining an extension involves defining a web interface and a set of authenticator operation. If there's an ask to add a new extension, both the UA and the underlying authenticators need to accept the ask. If the ask here requires change to the authenticator interface, the ask should start from there. 

Which layer to start the ask from can be confusing given that there is a couple of extensions that only require web interface change. For example, the FIDO AppId extension will only require web interface addition since the authenticator protocol (U2F) already defined the AppId interface. The Generic Transaction Authorization Extension only requires the UA to show additional texts in authentication prompt so there's no need to go down to the authenticator layer.

**Comment by agl** [comment]
In any case, putting this in an extension is highly problematic because extensions are optional, and a side-channel defense that the attacker can choose to deny to the token isn't useful.

Repurposing the signature counter seemed like a solid win because we eliminate the counter (which I believe would be positive) and can use those bytes for optional randomisation. However, it all depends on eliminating the signature counter, and enough people seem to believe that it still has value.
