### ISSUE TITLE
Enable web developers to migrate keys from one domain to another

### ISSUE THREAD

**Issue by AngeloKai** [w3c/webauthn#458]
In the password world, a website can migrate their user credentials (passwords) from one domain to another simply by changing configs on the server. Now with the passwordless world, keys are locked in with a domain. If a site chose to migrate their domain for reasons such as acquisition, they may risk losing all of their user accounts. Currently I don't know of a good way to do this. I would imagine this must be a tightly controlled process so that we don't the break the web.

**Comment by AxelNennker** [comment]
The openid foundation's [MODRNA](https://openid.net/wg/mobile/) working group is discussing the similar problem to link an user account from one OpenID provider to another OpenID provider.

The current spec is here: [Account Linking](https://xml2rfc.tools.ietf.org/cgi-bin/xml2rfc.cgi?Submit=Submit&format=ascii&mode=html&type=ascii&url=https://bitbucket.org/openid/mobile/raw/tip/openid-connect-account-porting-1_0.xml?at=default)

OpenID Connect creates Pairwise Pseudonymous Identifiers to make linking profiles intentionally hard. So linking accounts while protecting user privacy is tricky. Not to mention other foot guns like allowing any provider to steal all user accounts of other providers.
Please join the discussion at http://lists.openid.net/mailman/listinfo/openid-specs-mobile-profile

**Comment by AngeloKai** [comment]
The WebAppSec WG also had a discussion related to this: [Single Trust and Same Origin Policy 2.0](https://lists.w3.org/Archives/Public/public-webappsec/2017Apr/0002.html). From the discussion, it appears that the Tracking Protection WG is also discussing this: [Status Resource](http://www.w3.org/TR/tracking-dnt/#status-resource). 

As for the OpenID suggestion, I am not familiar with that world so I will defer that to my team's experts: @selfissued @nadalin

**Comment by equalsJeffH** [comment]
@AngeloKai this is a really good question.  Offhand, it would seem to me to be a topic for "WebAuthn Deployment Considerations"  (which presently we lump in into "implementation considerations" aka [[doc:impl-cons](https://github.com/w3c/webauthn/labels/doc%3Aimpl-cons)])

An obvious approach for the corp acquisition use case that you outlined would be for the being-acquired webapp to work with the acquiring-webapp to effect overall cross-webapp flows such that when visiting the being-acquired webapp, users are put through a flow having them register with the acquiring-webapp.  Such machinations would need to handle all credential types (i.e., the union of types defined by CredMan & WebAuthn) because most all existing webapps will have to handle a mix of cred types for the foreseeable future. 

Nominally this topic could addressed in an Impl Cons subsection.  It perhaps ought to be discussed overall in CredMan  (cc @mikewest @battre), with per-Cred Type particulars discussed in impl-cons sections of particular cred types (eg in webauthn impl-cons)

[ note that this issue is another example of a "we ought to think about this..." issue, as discussed in https://github.com/w3c/webauthn/issues/176#issuecomment-303894095 ]

**Comment by AngeloKai** [comment]
@equalsJeffH I moved this back to CR because some IDPs may find this as adoption blocker for achieving passwordless. I agreed this is a hard problem and will need many rounds of discussions. I am moving this back to CR for now so that we have a conversation about where we'd like to address this.

**Comment by AngeloKai** [comment]
One interesting thing to note here is that the Chrome's implementation of Credential Management API does allow credentials to be shared between origins through the use of [digital asset links](https://developers.google.com/digital-asset-links/v1/getting-started). It seems a relatively risky decision given that the file may be hacked. But I am sure @mikewest have given it some thoughts. Could we use similar mechanism here?

**Comment by jyasskin** [comment]
I think @AngeloKai's original problem is of a small organization moving from old.example.com to new.example.com. They have a trusted credential-source bound to old.example.com and need to either move it to new.example.com or create a new trusted credential-source bound to new.example.com.
1. User visits new.example.com/login.
2. User is redirected to old.example.com/move-credential
3. Server, which is shared between {old,new}.example.com, generates a capability token tied to user's identity, and redirects back to new.example.com/heres-your-credential?token=689347...
4. new.example.com/heres-your-credential?token=... generates a new credential-source and sends its public key along with the token back to the Server.
5. Server remembers the new token as trusted. The migration is complete.

**Comment by selfissued** [comment]
Most seemed to feel that federation was the right way to solve this - where an organization uses a single IdP for the FIDO RP and then uses federation, such as OpenID Connect, from the IdP to other domains.  For instance, you log into youtube.com and gmail.com at login.google.com.

@equalsJeffH suggested on today's call that the right place to do this in DNS.

On the call we also mentioned that Chrome supports something called Digital Asset Links but it's not in any W3C spec.

**Comment by arshadnoor** [comment]
While @AngeloKai's use-case in the original posting is a valid one, the right way to address this problem is through a business transaction, and to keep the authentication protocol true to one of its core principles: preserving a user's privacy.  I fear that the  compromise of web-applications at one site may be used to exploit FIDO credentials at another site if this privacy barrier is broken at the protocol layer.

When _acquirer.com_ merges with/buys out _acquisition.net_, there is a legitimate need to know that John Doe at acquirer.com is the same as John D. at acquisition.net.  However, once the merger has concluded, it is better for a business web-application on each site to request the authenticated user on their site, to identify themselves from the other company from the merger, so they can combine "assets" and provide a better experience for the user on both sites.  The merger of user-data is for **business** purposes, so it should appropriately be relegated to a business-transaction flow.

FIDO protocols are good.  Authenticators have been implemented to store/manage from 10 to Unlimited number of key-pairs.  Having multiple key-pairs on the Authenticator - one for each domain - is not the end of the world for devices that are likely to be "free" in 18-24 months.  But to start adding technological/protocol baggage for business transactions that get done/undone/redone is (to flog the same old horse) going down the path of PKI again.  

PKI - at its core - was as elegant as FIDO once upon a time (from a cryptographical and data-structure pov).  When ill-conceived business functions were added to digital certificates (through extensions, constraints, attribute certificates, etc.), it became the proverbial Gordian Knot.  And, that is why FIDO exists today.

While I don't track all the conversations on this forum - except for occasional catches like this - please use this litmus test when evaluating whether a protocol/specification change is necessary: _Is the problem being solved a BUSINESS function?_  If so, please stop right there and let business-application developers solve it where it belongs - in their applications.  

Thank you.

**Comment by equalsJeffH** [comment]
@selfissued mike jones reports on webauthn call today that he has spoken with folks requesting this and convinced them that identity federation and/or business processes are the way to address their overall use cases.
