### ISSUE TITLE
FIDO U2F Attestation Statement Format doesn't say what to do with AAGUID

### ISSUE THREAD

**Issue by jcjones** [w3c/webauthn#506]
The AAGUID field is a required part of the Authenticator Data structure. U2F devices may not have an AAGUID. (I think, if it exists, it's in the attestation certificate?)

We should define what the 128-bit AAGUID should be if if isn't known, instead of leaving it implementation-specific. Right now Firefox is leaving it as all zeroes (and not even trying to pull it out of the certificate -- that's a TODO), but we'll swap to whatever is appropriate.

**Comment by agl** [comment]
It could, plausibly, be defined as the truncated, SHA-256 hash of the raw, X.509 Subject field of the certificate. (I.e. including the SEQUENCE header so that it's a valid X.509 `Name` structure.)

However, at least some U2F devices have unique serial numbers in them, suggesting that either some complex normalisation needs to be defined, or perhaps that the hash of the Issuer could be used instead.

**Comment by kpaulh** [comment]
Just confirming we're also zeroing out the AAGUID.

**Comment by nadalin** [comment]
@selfissued to create PR to documents this and merge it

**Comment by AngeloKai** [comment]
Since we all confirm what our implementations are doing the same thing, this is no longer an issue that concerns implementation nor technicality. Removing the two flags.

**Comment by selfissued** [comment]
I will create a PR saying that we're zeroing out the AAGUIDS.

**Comment by jcjones** [comment]
Will be resolved by https://github.com/w3c/webauthn/pull/539

**Comment by equalsJeffH** [comment]
this will be fixed by PR #539

**Comment by rlin1** [comment]
I think this is addressed in FIDO CTAP2 spec.

**Comment by equalsJeffH** [comment]
pr #539 fixed this. closing.
