### ISSUE TITLE
Make U2F Attestation Format "sig" more precise

### ISSUE THREAD

**Issue by jcjones** [w3c/webauthn#530]
[Section 7.6](https://w3c.github.io/webauthn/#fido-u2f-attestation) defines the syntax of the **sig** field for the U2F Attestation Format as "The attestation signature." The Firefox [implementation chose (incorrectly)](https://bugzilla.mozilla.org/show_bug.cgi?id=1387820) to use the whole U2F signature response, including counter and flags, rather than the bare signature.

It would be good to adjust the language to something akin to "**sig**: The attestation signature alone, without protocol flags or counters."

**Comment by equalsJeffH** [comment]
However, note that the Firefox bug [1387820](https://bugzilla.mozilla.org/show_bug.cgi?id=1387820) is regarding the returned **_authentication assertion_** signature, rather than the **_attestation_** signature.  

that said, yes, [Section 7.6](https://w3c.github.io/webauthn/#fido-u2f-attestation)  [#fido-u2f-attestation](https://w3c.github.io/webauthn/#fido-u2f-attestation)  could use thorough review and likely some clarifications.
