### ISSUE TITLE
isUserVerifyingPlatformAuthenticatorAvailable() timeout really 10 minutes?

### ISSUE THREAD

**Issue by christiaanbrand** [w3c/webauthn#575]
Is [isUserVerifyingPlatformAuthenticatorAvailable()](https://w3c.github.io/webauthn/#isUserVerifyingPlatformAuthenticatorAvailable) really set as 10 minutes? Why not on the order of a couple of seconds? I don't really see a mechanism for fingerprinting if we wait for a random time within that couple of seconds before returning.

**Comment by kpaulh** [comment]
The lengthy timeout is to allow for user interaction. Even if the client supports a platform authenticator, the user has to approve the sharing of that information by responding to a prompt of some sort.

**Comment by AngeloKai** [comment]
The spec https://github.com/w3c/webauthn/blob/master/index.bs#L1080 merely recommends a value instead of defining one. The implementers can figure out among themselves which number they want to set. After that, you can come back with a new recommendation. 

Assigning the issue to PR time to allow implementers to experiment and come back with better recommendation. 

https://github.com/w3c/webauthn/blob/master/index.bs#L1080

**Comment by christiaanbrand** [comment]
We will be returning this without any user consent, and with no timeout value. We should update the spec accordingly.

**Comment by emlun** [comment]
@christiaanbrand Good catch - the entire last paragraph ("If the promise will return _False_, the client SHOULD wait a fixed period of time [...]") in [§5.1.7][spec] seems unnecessary to me. The method checks for the presence of an _authenticator_, not  a _credential_, so it should be fine to always return immediately. The text also motivates itself with not leaking information when asked to create a credential, which this method doesn't do.

[spec]: https://w3c.github.io/webauthn/#isUserVerifyingPlatformAuthenticatorAvailable

**Comment by equalsJeffH** [comment]
@emlun 
> ...so it should be fine to always return immediately

agreed, thx for the cogent analysis.

**Comment by akshayku** [comment]
Agreed. We do the same as @christiaanbrand mentioned.

**Comment by emlun** [comment]
@christiaanbrand Do you plan to open a PR for this?

**Comment by nadalin** [comment]
@christiaanbrand Create PR to remove timeout value

**Comment by christiaanbrand** [comment]
Just a note that we should also check the verify the behavior when an RP asks for a certain set of credentialIds, and none exist.

**Comment by emlun** [comment]
@christiaanbrand I think that would be a separate issue, though, right?

**Comment by equalsJeffH** [comment]
@kpaulh wrote in https://github.com/w3c/webauthn/issues/575#issuecomment-330594383:
> Even if the client supports a platform authenticator, the user has to approve the sharing of that information by responding to a prompt of some sort.

Well, neither the spec, nor PR #904, presently specifies that the user MUST be prompted -- rather, it just suggests that might occur.

Also, wrt @emlun wrote in https://github.com/w3c/webauthn/issues/575#issuecomment-386545474
> The method checks for the presence of an authenticator, not a credential, so it should be fine to always return immediately.

 However the situation this time-out stipulation is in regards to is:
> This is done so that callers cannot distinguish between the case where the user was unwilling to create a credential using one of the available user-verifying platform authenticators and the case where no user-verifying platform authenticator exists.

The rationale above (from that parag) is one of privacy. I do not recall offhand who championed adding the entire parag to the spec -- perhaps they can speak up?  Are we saying that we have thought about this and do not feel this privacy concern merits distinction in the spec?  I agree a huge long timeout would be problematic UX-wise in some edge cases (I presume the are edge cases assuming most users will be fine creating a platform cred, and ultimately most platforms will feature userVerifyingPlatformAuthnrs).

**Comment by emlun** [comment]
The paragraph was added in commit 8bf3b7e7cb803e459da9dfd239e68815cf40aaf7, which mentions #523.

I also don't understand why this method specifies that

>[...] the client then assesses whether the user is willing to create a credential using one of the available user-verifying platform authenticators. [...]

This seems to me like the responsibility of [`credentials.create()`][create]. In fact, if isUVPAA were to do that, then the user would be prompted twice for consent to create a credential if the RP calls isUVPAA first. Also, I interpret @christiaanbrand's comment https://github.com/w3c/webauthn/issues/575#issuecomment-386059592 as proposing the above part should be deleted.

The identifying information leak in create() is caused by the `excludeCredentials` parameter; since isUVPAA doesn't have that parameter, the same privacy concerns shouldn't apply to isUVPAA. However, the privacy concern noted here is about fingerprinting. isUVPAA could provide the RP with one additional bit of information to build a browser fingerprint from. Is that something we should be worried about? Chrome and Edge are clearly not... (https://github.com/w3c/webauthn/issues/575#issuecomment-386059592, https://github.com/w3c/webauthn/issues/575#issuecomment-386650507)

[create]: https://w3c.github.io/webauthn/#createCredential

**Comment by kpaulh** [comment]
Speaking for Christiaan since he's OOO - yes, we do intend to remove the confirmation prompt for the usability reasons emlun@ and @equalsJeffH noted above. He can correct me when he gets back, but last I heard Chrome is okay with leaking the bit.

(And If I recall correctly, the initial wording was vaguely written with 'suggestions' because the browser vendors weren't in total agreement with regards to the timeout and consent prompts. Since no one was actively implementing this, we were pretty hand-wavey with it.)

**Comment by equalsJeffH** [comment]
@kpaulh fessed-up with:
> (And If I recall correctly, the initial wording was vaguely written with 'suggestions' because the browser vendors weren't in total agreement with regards to the timeout and consent prompts. Since no one was actively implementing this, we were pretty hand-wavey with it.)

LOL, thx for explanation ;-)
