### ISSUE TITLE
Nothing required in PublicKeyCredentialEntity

### ISSUE THREAD

**Issue by apowers313** [w3c/webauthn#587]
Currently the [PublicKeyCredentialEntity](https://w3c.github.io/webauthn/#dictdef-publickeycredentialentity) has no required members, and it appears to be acceptable to pass an empty object to `publicKey.rp`. Was that the intent?

**Comment by apowers313** [comment]
Same concern for [PublicKeyCredentialUserEntity](https://w3c.github.io/webauthn/#dictdef-publickeycredentialuserentity), which also doesn't seem to have any meaningful information (such as an `id` for the user).

**Comment by apowers313** [comment]
Further, I think [4.1.3](https://w3c.github.io/webauthn/#ref-for-dictdef-makepublickeycredentialoptions①) step 3 actually refers to a `user.id` which no longer exists in the dictionary:

> If any of the name member of options.rp, the name member of options.user, the displayName member of options.user, or the id member of options.user are not present, return a TypeError simple exception.

**Comment by emlun** [comment]
>Currently the PublicKeyCredentialEntity has no required members, and it appears to be acceptable to pass an empty object to publicKey.rp. Was that the intent?

This looks like an editorial mistake. [§4.4][rp] specifies that `rp.name` is required.

>Same concern for PublicKeyCredentialUserEntity, which also doesn't seem to have any meaningful information (such as an id for the user).

That type inherits `id` in the 2017-08-11 draft. In the 2017-09-28 draft the property has been moved down, and is also specified in [§4.4][user] to be required.

[rp]: https://w3c.github.io/webauthn/#dom-makepublickeycredentialoptions-rp
[user]: https://w3c.github.io/webauthn/#dom-makepublickeycredentialoptions-user

**Comment by jyasskin** [comment]
https://w3c.github.io/webauthn/#createCredential step 3 says:

> If any of the name member of options.rp, the name member of options.user, the displayName member of options.user, or the id member of options.user are not present, return a TypeError simple exception.

Because `name` is required in both the `user` and `rp` fields, I think it is ok to mark it `required` in the base class. `id` wasn't marked `required` when it was in PublicKeyCredentialEntity because it was only required by one of the sub-dictionaries, but now it probably could be marked `required` in `PublicKeyCredentialUserEntity`.

**Comment by AngeloKai** [comment]
This issue has to do with which dictionary member should be marked as required and can be potentially breaking. Assigning this to milestone WD-07. 

@equalsJeffH @nadalin @YubicoDemo for tracking.

**Comment by YubicoDemo** [comment]
@apowers313 only reported the issue. He is not working on it. Can @AngeloKai or @jyasskin take this.

**Comment by equalsJeffH** [comment]
Our prior discussion on this topic is here: https://github.com/w3c/webauthn/issues/538

**Comment by emlun** [comment]
The current prose is equivalent to making `PublicKeyCredentialEntity.name`, `PublicKeyCredentialUserEntity.id` and `PublicKeyCredentialUserEntity.displayName` required in the IDL. However, it looks like it's been deliberately decided to specify this in text instead of IDL. In #538 @AngeloKai says

>The issue was brought up in past discussions around CredMan. [...] I believe the required keyword on IDL is omitted due to the need to integrate with CredMan. @mikewest probably has better memory about this. The argument is that it is ok for the keyword to be omitted as long as a DOM Exception error would be thrown.
>[...]
>We decided to remove the required keyword and let JS throw the TypeError so that the inheritance would be clearer.

I don't understand why having them not required is needed for integration with CredMan, since all these types are specific to WebAuthn and we can have required members in other dictionaries. I'm in favor of making the members required in IDL; but I'm also in favor of closing this with no action if it would break CredMan integration, and since nothing seems to have changed to make the decision in #538 out of date.

@AngeloKai @mikewest Any objections to making the required members required in IDL?

**Comment by emlun** [comment]
I see no objections, so I'll write up a PR for making the required members required in the IDL.
