### ISSUE TITLE
clarify isPlatformAuthenticatorAvailable's semantics

### ISSUE THREAD

**Issue by balfanz** [w3c/webauthn#627]
The reason we introduced `isPlatformAuthenticatorAvailable` is so that RPs can find out whether they're running on a platform that supports Windows Hello, or Apple TouchID-like systems (i.e., user-verifying reauthentication mechanisms).

The current wording makes it sound like `isPlatformAuthenticatorAvailable` merely looks for platform-attached authenticators. We need to make sure that RPs can use this function to look for user-verifying platform-attached authenticators.

**Comment by AngeloKai** [comment]
Good point. I believe we didn't word it that way because the belief is all platform authenticators should have user-verifying capability. We can certainly add it in the authenticator taxonomy to clarify: https://github.com/w3c/webauthn/issues/422. 

It seems like this is a good clarification to make before CR. 

@equalsJeffH @nadalin for tracking.

**Comment by nadalin** [comment]
@balfanz to clarify text, no renaming

**Comment by AngeloKai** [comment]
isPlatformAuthenticatorAvailable section: https://w3c.github.io/webauthn/#isPlatformAuthenticatorAvailable
