### ISSUE TITLE
credentials.get() should have optional parameters for userVerification and userPresence

### ISSUE THREAD

**Issue by balfanz** [w3c/webauthn#629]
When requesting an assertion from an Authenticator in `credentials.get()`, the RP should be able to specify whether a test of user presence is required, whether user verification is required, or whether neither is required (a "silent signature").

Note: [`credentials.get()`](https://w3c.github.io/webappsec-credential-management/#dom-credentialscontainer-get), in the webauthn case, is implemented by the algorithm given by the [#getAssertion](https://w3c.github.io/webauthn/#getAssertion) section in the webauthn spec.

By default (i.e., when not mentioning either user verification or test of user presence), it should be assumed that test of user presence is required.

Proposal 1:
have a parameter `userPresence` with values `test`, `verify`, `none`, with default value `test`.

Proposal 2:
have two parameters:
- boolean parameter `requireUserVerification`, default value `false`
- boolean parameter `requireUserPresence`, default value `true`

Note that in this case, the combination `requireUserVerification = true` and `requireUserPresence = false` is invalid.

**Comment by akshayku** [comment]
Proposal 2 looks better to me.

**Comment by akshayku** [comment]
Thinking more about this, doesn't silent signatures problematic as they leak information without user knowing? 

How does one make sure that, user has given consent the first time and then it can be used at later stage without user presence but no silent signatures without user consent at some earlier time?

**Comment by emlun** [comment]
The authenticator signs over the user presence and user verification flags, so it won't be possible to assert later that a silent signature was made with user consent. But the RP does need to take care to actually verify those flags (or store the signature), so that should probably be added to [§6.2. Verifying an authentication assertion][verify].

What would be the use case for silent signatures? I suppose they can't do much harm assuming the RP is trusted, but could XSS/XSRF attacks make it an issue?

[verify]: https://w3c.github.io/webauthn/#verifying-assertion

**Comment by idamlaj** [comment]
Enabling silent authentication might be problematic from a privacy standpoint.

Ad trackers will be able to silently create and use "super cookies" that track the machine across apps, and can't be easily deleted by the user.

As for making user verificatIon optional, can you provide a use case for this? The user agent can already do this at the CTAP level which enables some use cases relevant to the web (e.g. "I forgot my CTAP device PIN" button when the user agent asks for PIN entry)

**Comment by equalsJeffH** [comment]
fyi, silent authenticators aka "touchless" are the topic of this existing issue: https://github.com/w3c/webauthn/issues/199

**Comment by equalsJeffH** [comment]
I prefer proposal 1, tho I suggest an enum name of `userVerificationOrPresenceRequirement` with values of `present`, `verify`, `none`, with default value `present`.  

Having two booleans seems needlessly complex and leads to needing to specify things like which combinations are valid.

**Comment by emlun** [comment]
@idamlaj Silent credential creation has been rejected before for precisely the reason you describe, but what's described here is specifically the authentication operation. Ad trackers thus won't be able to silently create credentials. There's also been talk of applying the same origin policy here as well, but I'm not sure where we currently stand on that.

**Comment by equalsJeffH** [comment]
see also #644, #536, #524

**Comment by akshayku** [comment]
**Regarding Silent signatures and user presence:**

- Thinking more about this, silent signatures from web should not be allowed due to privacy reasons. User presence should always be there similar to current U2F model. U2F does not allow silent signatures and that IMO is the right security model. Silent signatures can detect user accounts without user knowing and IMO, user should always know if someone is trying to detect their accounts.

**Regarding User verification:**

RP does not know what kind of authenticators user has currently plugged in as well as future dynamic authenticators user will plug in/TAP/etc. So it can't make any authenticator based decision beforehand. 

- If RP care about user verification and authenticator by default is capable of it, platform will ask for user verification from the authenticator, signature will reflect user verification and RP is happy.

- If RP care about user verification but authenticator is not capable of it, RP can reject such signature without UV bit when it receives.

- If RP does not care about user verification but is OK if it gets it as part of signature due to default authenticator behaviour, it can simply ignore UV bit. 

- If RP does not want user verification to happen even if authenticator is capable of doing user verification and only care about user presence, I propose to introduce one boolean variable called `UVNotRequired`. This way, platform will only send "UP" to authenticator even if authenticator is capable of user verification if it sees this variable set to true.

**Proposal:**
Introduce boolean variable `UVNotRequired` to `get` method which can be set to `true` if RP does not want user verification. Default behavior is of this variable is `false` and in that case platform will follow default authenticator semantics.

**Comment by emlun** [comment]
>Introduce boolean variable `UVNotRequired` to `get` method which can be set to `true` if RP does not want user verification. Default behavior is of this variable is `false` and in that case platform will follow default authenticator semantics.

If we're to do this, in the interest of eliminating double negation I instead propose a parameter `UVRequired` with default value `true`, which the RP can set to `false` if it does not want user verification.

**Comment by akshayku** [comment]
By `UVNotRequired` proposal, RP can decide different authorization levels for user depending upon whether the signature contains UV bit or not for future not plugged in/TAP authenticators default behaviour. I am referring to a case where RP kind of says, tell me what you have and I will decide whether whether I will allow it or not and to what level.

With `UVRequired`, RP has to decide before hand what it wants which it can't do without knowing user/authenticator and will not be able to support different behavior.

**Comment by emlun** [comment]
See, this is why I wanted to eliminate the double negation: you and I interpreted it in different ways. :)

- I read "`UVNotRequired` defaults to `false`" as "by default, the RP requires UV".
- You seem to read "`UVNotRequired` defaults to `false`" as "by default, the RP will decide after receiving the signature whether it requires UV".

But you're right, both proposals are confusing since we're not actually talking about a boolean parameter, it's a true/false/maybe parameter ("maybe" if not explicitly set).

Either way, having thought a bit more about this: it would make for a bad user experience to go through the ceremony with everything seemingly going all right until the RP rejects the signature right at the end. In that case the RP evidently _does_ require user verification - it doesn't matter what authenticators the user has available, so it's just frustrating for the user if the RP pretends otherwise. Especially if the user has one authenticator capable of UV and one not, and chooses to use the one incapable because the RP didn't indicate that it requires UV. It's just plain better to announce it up front. And in that case I think it's better to go with `UVRequired` which if `true` indicates that the RP requires UV and if `false` or missing indicates the RP accepts signatures both with and without UV.

**Comment by emlun** [comment]
All that aside I agree with @akshayku and @idamlaj that optional user presence seems dangerous, but I could be convinced if there's a concrete use case. The one I've heard so far is to enable a "heartbeat" polling mechanism to detect if the user unplugs the authenticator; is that the main one being considered?

**Comment by nadalin** [comment]
@balfanz we decided on this a while back that it was a bad idea, so this should be closed no action

**Comment by akshayku** [comment]
I think Jeff's enum way of describing things is the right model. I propose enum name of `userVerificationRequirement` with values of `Required`, 'NotRequired` and `AuthenticatorBehavior`, with default value being `AuthenticatorBehavior`.

- `Required`: Authenticator MUST enforce user verification and signature MUST
have `UV` bit set.

- `NotRequired`: Authenticator MUST not ask for user verification even if authenticator is capable of it. This if for scenario where touch is enough for RP and it does not want UI pops on authenticator or platform for ClientPin Case. May be in case it wants to use the authenticator as a second factor device.

- `AuthenticatorBehavior`: Platform performs the default behavior of authenticator and signature reflects that. It is kind of RP saying, tell me what you have and I will decide what level of authentication you can have or RP does not care about user verification but OK if it receives it as it ignores it. For Authenticators, which don't support user verification, it will not set "UV" bit set. For authenticators that can support user verification, platform will send such a request and signature will reflect "UV" bit.

**Comment by akshayku** [comment]
As discussed in WebAuthN call on 10/18 Authenticators default behavior is reflected in the signature at authenticatorGetAssertion time and RP can act of it whether it wants user verification or not. So the current behaviour is ok. Closing this.
