### ISSUE TITLE
5.6. Authentication Extensions name confusing

### ISSUE THREAD

**Issue by jovasco** [w3c/webauthn#648]
[P 5.6 ](https://w3c.github.io/webauthn/#iface-authentication-extensions) talks about Authentication Extensions and refers to  [p 9](https://w3c.github.io/webauthn/#extensions) which subdivides "webauthn extensions" into "authentication" and "registration" extensions.

The "authentication extensions" term in [5.6](https://w3c.github.io/webauthn/#iface-authentication-extensions) refers to both "authentication"  and  "registration" extensions of [p 9](https://w3c.github.io/webauthn/#extensions).

Suggest renaming this to CredentialExtensions or WebAuthnExtensions in 5.6

**Comment by selfissued** [comment]
I disagree with changing this name.  The name was chosen deliberately, as these are *extensions* to web *authentication*.  As we were revising the then-sloppy extensions language so that it was self-consistent and complete, we needed a name for extensions which could extend either or both operations.  This was the name chosen.  The extensions language changes were widely reviewed, including by Jeff Hodges and others.  I think that this issue should be closed with no action.

**Comment by jovasco** [comment]
So you want the same name for two different concepts?

**Comment by equalsJeffH** [comment]
Well, I tend to agree with @jovasco that our extension language is at least somewhat confusing, even though @selfissued's efforts improved it greatly.  See also issue #471 which we recently closed with no action for the renaming portions of the issue.  This issue intersects with #471.

**Comment by equalsJeffH** [comment]
sigh, sad but true
