### ISSUE TITLE
CTAP/U2F doesn't status indicating the user cancelled the operation 

### ISSUE THREAD

**Issue by AngeloKai** [w3c/webauthn#658]
In the authenticator parallel processing section (https://github.com/w3c/webauthn/blob/master/index.bs#L738), it says: 

`        :   If any |authenticator| returns a status indicating that the user cancelled the operation,
        ::  1. [=set/Remove=] |authenticator| from |issuedRequests|.
            2. [=set/For each=] remaining |authenticator| in |issuedRequests| invoke the [=authenticatorCancel=] operation on
                |authenticator| and [=set/remove=] it from |issuedRequests|.
`

Looking at both CTAP and U2F specs, I haven't found an error matching this indication. Should we remove this from the algorithm?

**Comment by AngeloKai** [comment]
@akshayku @leshi can one of you educate me on which status match this indication?

**Comment by jehrensvard** [comment]
Is this the one you're looking for ?

0x2D  CTAP2_ERR_KEEPALIVE_CANCEL Pending keep alive was cancelled.

**Comment by nadalin** [comment]
@AngeloKai Can we close this issue with no action ?

**Comment by AngeloKai** [comment]
@akshayku @equalsJeffH to confirm.

**Comment by AngeloKai** [comment]
@jcjones to add comment about U2F.

**Comment by jcjones** [comment]
There's no indication for this with U2F on the wire; we're not intending to treat authenticators going way (unplug, out-of-range) as a cancellation for all, right? I'm not implementing it that way, at least.

**Comment by equalsJeffH** [comment]
the webauthn spec steps cited in the original post (OP) (https://github.com/w3c/webauthn/issues/658#issue-267072876) address the case where a (presumably platform) authenticator _MAY_ return some form of "user cancelled the entire operation" indication.  

Since our "authenticator model" is so far "loosely defined"--such that it can accommodate both CTAP-speaking authenticators and platforms' authnr APIs--the cited step in the OP seems reasonable to me as presently written. 

If the [CTAP2 error response](https://fidoalliance.org/specs/fido-v2.0-rd-20170927/fido-client-to-authenticator-protocol-v2.0-rd-20170927.html#error-responses) value of  CTAP2_ERR_KEEPALIVE_CANCEL is actually intended to convey that the user somehow signaled _to the authnr_ that they wish to cancel the entire operation (i.e., either registration or authn), then we _could_ add the possibility of explicitly receiving that CTAP2 error response value to the cited alg step. 

However, I note that the CTAP2_ERR_KEEPALIVE_CANCEL error response value is not actually expliclity employed or otherwise documented in the CTAP spec at this time.  Thus I am inclined to leave the cited alg step as-is, and only perhaps add a Note: explaining the steps' purpose.

**Comment by equalsJeffH** [comment]
decided on 1-nov webauthn call that we will leave the cited alg step as-is, and  add a Note: explaining the steps' purpose.

**Comment by selfissued** [comment]
@equalsJeffH if you don't have time to write this note this week, please let me know where you think the note should go and I'll then create a PR.  Note that this step presently occurs in two places:
  - In 5.1.3 Create https://w3c.github.io/webauthn/#createCredential step 20.
  - In 5.1.3 Get https://w3c.github.io/webauthn/#getAssertion step 18.

Should the note occur in both of these locations and if so, in the same sentence, or somewhere else?  Or should it only occur once, and if so, where?

**Comment by equalsJeffH** [comment]
see PR #760
