### ISSUE TITLE
JSON deserialization is not defined

### ISSUE THREAD

**Issue by annevk** [w3c/webauthn#713]
The prose would read much clearer if this was an operation that returned something.

**Comment by emlun** [comment]
What part(s) of the spec is this in reference to?

**Comment by annevk** [comment]
7.1 and 7.2 both use this term.

**Comment by emlun** [comment]
Ok. Seems like a good idea to me.

**Comment by equalsJeffH** [comment]
setting this to CR milestone since we triaged the PR #713 as CR

**Comment by emlun** [comment]
Decided on 2018-01-17 call to close this. Since 7.1 and 7.2 are the RP operations, it would be confusing to have these operations refer to Infra for instance. Since the RP operations need to be platform agnostic, there's value in keeping them not too strictly defined.

**Comment by annevk** [comment]
FWIW, I object to this resolution. You do actually need to define this in detail. E.g., we don't want some platforms to support other encodings than UTF-8 here, we need all of them to strip a leading BOM, if any.

**Comment by emlun** [comment]
Those are good points, perhaps @selfissued, @equalsJeffH and/or someone else (@agl, @jcjones?) should take another look at this.

**Comment by selfissued** [comment]
I will write a PR addressing the rest of this issue shortly.

**Comment by emlun** [comment]
@selfissued Would you like me to salvage some of the changes from #718?

**Comment by selfissued** [comment]
A lot of the problem here is that it's talking about JSON at all, whereas the data structures we're serializing from and into are JavaScript.  It makes a difference, because for instance, In JavaScript you can have ArrayBuffers to represent byte arrays, which serialize naturally into CBOR.  I plan to root out the incorrect uses of "JSON" when what was actually meant was "JavaScript".

If there are changes in #718 that you can salvage that do this, then sure, resurrect them @emlun.  But if the text you would salvage talks about JSON rather than JavaScript, I wouldn't bother.  Thanks.

**Comment by emlun** [comment]
It's worth noting that the occurrences @annevk mentions are in the RP operations and act on the _serialized client data_, which is explicitly a `CollectedClientData` (whose fields are all JSON serializable) serialized to JSON, so I think it should be fine to talk about JSON there as it'll not necessarily run in a browser.

The changes in #718 do solve this, I think, but instead have the issue that they refer to browser APIs, which might be confusing since these are RP operations and not client operations.

**Comment by selfissued** [comment]
I agree @emlun that these distinctions matter.  If you want to contribute text towards addressing these issues, by all means, please do.

**Comment by annevk** [comment]
@emlun requirements can always be implemented in any manner, as long as the end result is the same. So that should not matter in theory.

**Comment by emlun** [comment]
Ok. The substantive changes proposed in #718 look like this: https://github.com/emlun/webauthn/pull/1 , branching from #752. @selfissued should I submit that as a PR?

**Comment by selfissued** [comment]
Yes, @emlun - please create a PR for this along the lines of the changes in https://github.com/emlun/webauthn/pull/1/files.  Thanks!
