### ISSUE TITLE
FIDO U2F Attestation Statement Format needs to clarify that user handle will be empty

### ISSUE THREAD

**Issue by jcjones** [w3c/webauthn#715]
FIDO U2F devices have no mechanism to store a `userHandle` field, so if an RP passes a user handle to `make credential` and gets back a U2F attestation type, the RP must be prepared that subsequent calls to `get assertion` will not have a user handle.

I recommend modifing the last step of **Verification procedure** to:
> If successful, return attestation type Basic with the attestation trust path set to `x5c` _and the user handle set to an empty buffer_.

**Comment by emlun** [comment]
I think the verification procedure doesn't seem like the right place to put it, since there's nothing anywhere else suggesting that the verification procedures would have anything to do with the user handle. I'm more inclined to make it a "Note:" to either [§5.2.2 AuthenticatorAssertionResponse][auasre] or to [§7.2 Verifying an authentication assertion][verify] (the latter of which currently makes no mention at all of the user handle).

Perhaps we should add a conformance subclass for backwards compatibility to [§2 Conformance 2. Authenticators][conf], where we can list the U2F exceptions, and refer back to that? Otherwise it seems weird to specify that "the user handle is required, except when it isn't".

[auasre]: https://w3c.github.io/webauthn/#iface-authenticatorassertionresponse
[conf]: https://w3c.github.io/webauthn/#conforming-authenticators
[verify]: https://w3c.github.io/webauthn/#verifying-assertion

**Comment by Kieun** [comment]
I think it would be better to add more description regarding this at step 1 of §7.2 Verifying an authentication assertion. We need to provide detailed procedures for the RP server to look up credential public key with credential id and user handle. 
We need to mention the fact that the RP server should look up credential public keys with user id before sending an challenge and then select one from the keys after getting an assertion with credential Id in case of 2nd factor use cases.

**Comment by jcjones** [comment]
I will write a PR.

**Comment by equalsJeffH** [comment]
I note, in arrears (apologies), that PR #740 does not seem to address everything that @jcjones and @emlun were discussing adding to the spec in https://github.com/w3c/webauthn/issues/715#issue-280161012 and https://github.com/w3c/webauthn/issues/715#issuecomment-350019689 

-- i.e., adding one (or more) **Note:** in some appropriate place(s) that refer back to the newly-added [#conforming-authenticators-u2f](https://w3c.github.io/webauthn/#conforming-authenticators-u2f) subsection.

I am re-opening this issue due to the above -- we can close it if we feel that such **Note:(s)** are not actually warranted.

Also, @Kieun -- you should perhaps, if you feel strongly about the items you mention in https://github.com/w3c/webauthn/issues/715#issuecomment-351100623, submit new issue(s) and also create a PR addressing them.

**Comment by emlun** [comment]
I'd like to note that with #730 merged, the need is lesser than it was at the time of my previous comment. [`AuthenticatorAssertionResponse.userHandle`][uh] is now nullable, so it's no longer weird that "the user handle is required, except when it isn't"; and both authenticator and client algorithms now specify excplicitly when to return null for the user handle ([§5.1.4.1 step 18.3][uhnull], [§6.2.1][amc] step 7.4, [§6.2.2][aga] step 13 point 4).

[uh]: https://w3c.github.io/webauthn/#dom-authenticatorassertionresponse-userhandle
[uhnull]: https://w3c.github.io/webauthn/#ref-for-dom-authenticatorassertionresponse-userhandle%E2%91%A0
[amc]: https://w3c.github.io/webauthn/#op-make-cred
[aga]: https://w3c.github.io/webauthn/#op-get-assertion

**Comment by jcjones** [comment]
Yeah, I agree with  @emlun; I went through the relevant sections of the doc when I was writing that PR, and I think this is all we needed. Open to other interpretations, certainly, though!

**Comment by jcjones** [comment]
In call on 17 January we agreed that this is indeed resolved by the updates from #730 per https://github.com/w3c/webauthn/issues/715#issuecomment-357317394 and this can be closed.
