### ISSUE TITLE
U2F Attestation Statement Format does not define "self attestation" steps

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webauthn#745]
The U2F Attestation Statement Format does not define steps for performing "self attestation", which e.g. [is done in the packed attestation stmt format section](https://w3c.github.io/webauthn/#ref-for-self-attestation%E2%91%A0%E2%91%A1).

**Comment by jcjones** [comment]
This may not be necessary since 'self attestation' doesn't exactly translate for U2F devices.

**Comment by agl** [comment]
Unclear if this will be used. In practice, I don't know of any U2F tokens that do self-attestation via an X.509 certificate. It _is_ possible that a soft-token could do this, but a soft-token could also return a webauthn self attestation directly, rather than going via U2F.

**Comment by equalsJeffH** [comment]
hm.  I suppose we could simply delete "Self Attestation" from the **Attestation types supported** list in [8.6. FIDO U2F Attestation Statement Format](https://w3c.github.io/webauthn/#fido-u2f-attestation) .  WDYT?

If we do not do that, we might be able to refer to the **_packed_** attstn format section for how to deal with self attestation, however, self attestation is signaled therein by an empty _x5c_ array -- and I seem to recall that @jcjones is self-constructing an attstn cert when doing self attstn...  ?

**Comment by emlun** [comment]
Well, _technically_ self attestation is just a special case of basic attestation with an anonymous attestation public key. So everything an authenticator needs to do for self attestation is also possible as a basic attestation - you just have to jump through a few more hoops to do it, which all U2F authenticators necessarily do already because U2F only supports x5c certificates for delivering the attestation public key.

So I think it should be safe to drop the self attestation type from the fido-u2f format.
