### ISSUE TITLE
Images not visible in published spec

### ISSUE THREAD

**Issue by rlin1** [w3c/webauthn#784]
on https://www.w3.org/TR/webauthn/

the image URL in the document is (for example) "images/fido-signature-formats-figure1.svg"
The image file at this time exists under https://www.w3.org/TR/webauthn/fido-signature-formats-figure1.svg

**Comment by equalsJeffH** [comment]
we had this difficulty at least once before, and had it fixed, though I cannot find the relevant msgs/postings

**Comment by equalsJeffH** [comment]
per the OP https://github.com/w3c/webauthn/issues/784#issue-295132212 the problem here is that the image svg files apparently did not land in an `images` subdirectory relative to the spec's directory.  rather, they landed in the spec's directory.

ostensibly, all that needs to happen to fix this is to create such a directory and put the *.svg image files in it. 

It appears this problem presently applies only to https://www.w3.org/TR/webauthn/ which is AKA https://www.w3.org/TR/2017/WD-webauthn-20171205/ --- earlier spec revs have the figure *.svg files in an `images` subdirectory (tho i did not check them all).

When WD-07 (aka [WD-webauthn-20171205](https://www.w3.org/TR/2017/WD-webauthn-20171205)) was originally published, were the figures properly appearing?  (I do not recall specifically checking)

I am concerned that if we do not determine how and why this occurred this problem will continue to appear.  It seems we need help from folks who understand the W3C spec publishing workings...

a related question:  is having figure source files in an `images` subdirectory of the spec's directory the standard practice for the `https://www.w3.org/TR/` namespace?

**Comment by wseltzer** [comment]
Fixed by creating the images subdirectory under https://www.w3.org/TR/2017/WD-webauthn-20171205/ and uploading the images there. 

It should work so long as the images match the links to them, so if the links are using the "images/" convention, let's make sure there's an images directory. :)

(previous issue https://github.com/w3c/webauthn/issues/486 )

**Comment by equalsJeffH** [comment]
thanks @wseltzer :)   
Images have re-appeared, yay!

is there something specific that one needs to do when publishing to `www.w3.org/TR/` in order to ensure an `images` subdirectory is created?

**Comment by wseltzer** [comment]
@equalsJeffH 
Possibly BSPublishAdditionalFiles(files), as described in https://tabatkins.github.io/bikeshed/#echidna-hooks. Or ping team contacts with a pointer to this issue :)

**Comment by rlin1** [comment]
as of today, the images are back.  Does anyone know whether this issue is not permanently fixed?
Should I close the issue?

**Comment by wseltzer** [comment]
ok to close

**Comment by rlin1** [comment]
issue solved.

**Comment by equalsJeffH** [comment]
Issue **NOT**  solved -- WD-08's figures do not appear
cf: https://www.w3.org/TR/webauthn/#fig-authData

IIUC, per @wseltzer in https://github.com/w3c/webauthn/issues/784#issuecomment-366078342, we perhaps need to write a `bs-extensions.include` file containing an impl for `BSPublishAdditionalFiles(files)` that ensures the image/figure files end up in the correct subdirectory of the `w3.org/TR/` backing store.

I would reopen this issue but the repo is apparently not re-opened for heathens, sigh :(

**Comment by equalsJeffH** [comment]
reopending

**Comment by wseltzer** [comment]
and WD-08 fixed manually

**Comment by deniak** [comment]
How is that spec published on echidna? Is someone calling a script manually? From a quick look, it doesn't seem to be called from travis.

**Comment by equalsJeffH** [comment]
^ @AngeloKai ?

**Comment by deniak** [comment]
We just published the CR today so unless that spec is returning to WD again, that spec will not be published by echidna  anymore so the bug won't occur again. I guess we can close that ticket but I'll leave that decision to you.

**Comment by equalsJeffH** [comment]
seems fine to me to close this....
