### ISSUE TITLE
Clarify byte size requirements for UVI

### ISSUE THREAD

**Issue by gmandyam** [w3c/webauthn#823]
Current text says "The UVI is encoded as CBOR byte string (type 0x58)."  Then it goes on to say "Servers supporting UVI extensions MUST support a length of up to 32 bytes for the UVI value."

What does this mean in terms of UVI byte size?  For instance, 
(1) Are authenticators allowed to produce UVI's more than 32 bytes, but the RP's can ignore the extra bytes?  
(2) Should authenticators always produce UVI's of no more than 32 bytes? 
(3) Can authenticators produce UVI's of less than 32 bytes and pad to 32?

Relevant to PR https://github.com/w3c/webauthn/pull/821.

**Comment by Kieun** [comment]
As I understand it and refer current implementations of UVI extension supported by FIDO UAF, authenticators should generate UVI value up to 32 bytes. And those value should be sent to RP Server without any loss of data.

**Comment by gmandyam** [comment]
>As I understand it and refer current implementations of UVI extension supported by FIDO UAF, authenticators should generate UVI value up to 32 bytes.

Can you point to the relevant standards text that states this?  The current web authn description is essentially replicated from https://fidoalliance.org/specs/fido-uaf-v1.1-ps-20170202/fido-uaf-reg-v1.1-ps-20170202.html#tags-used-in-the-protocol, and there is no text currently written there that places a limit on how many bytes that the authenticator can generate for UVI.  The requirement in the UAF registry is "FIDO Servers supporting UVI extensions MUST support a length of up to 32 bytes for the UVI value. "

Moreover - assuming such a requirement exists for UAF authenticators, is the intention to apply a similar 32 byte limit to all webauthn authenticators?

**Comment by Kieun** [comment]
There is no such section and spec to describe the requirements of authenticators for UVI extension directly.  But if you read followings, you may understand that the way for authenticators to generate UVI value. The spec describes the max length of UVI value implicitly by defining FIDO Server requirements.

> Each UVI value must be specific to the related key (in order to provide unlinkability). It also must contain sufficient entropy that makes guessing impractical. UVI values must not be reused by the Authenticator (for other biometric data or users).

For making clearly, it would be better to provide the requirements of authenticators.
In short, the length of UVI value is up to authenticator but can not exceed 32 bytes and UVI value should be sent to FIDO server without any loss of data.

Regarding webauthn authenticators, since webauthn spec does define extensions including UVI, I think webauthn authenticators supporting UVI feature should meet such requirements.

**Comment by rlin1** [comment]
Proposal: don't change the CR version for this.

**Comment by gmandyam** [comment]
Addressed via https://github.com/w3c/webauthn/pull/821
