### ISSUE TITLE
Description of CollectedClientData is outdated

### ISSUE THREAD

**Issue by emlun** [w3c/webauthn#870]
The description of [CollectedClientData][ccd] seems outdated:

>The **client data** represents the contextual bindings of both the Relying Party and the client platform. It is a key-value mapping with string-valued keys. Values can be any type that has a valid encoding in JSON. Its structure is defined by the following Web IDL.

Issues:

- This seems to contradict itself, saying both that values are strings and that they are any JSON-able type.
- Not all values are strings now that `tokenBinding` is a dictionary.

[ccd]: https://www.w3.org/TR/webauthn/#sec-client-data

**Comment by equalsJeffH** [comment]
@emlun 
> This seems to contradict itself, saying both that values are strings and that they are any JSON-able type.

actually, [IIUC](https://en.wiktionary.org/wiki/IIUC), it is saying that [(collected) client data](https://w3c.github.io/webauthn/#sec-client-data) is a key-value mapping whose keys are string-valued.  The _client data values_ associated with the latter string-valued keys can be any type that has a valid encoding in JSON.

> Not all values are strings now that tokenBinding is a dictionary.

I am thinking this is not a problem both because of the above disambiguation of the uses of the term "value" in the quoted spec text, and also because [IDL dictionary values can be converted to to ES objects](https://heycam.github.io/webidl/#es-dictionary). 

Perhaps we ought to clarify the quoted spec text like so...
```
The <dfn>client data</dfn> represents the contextual bindings 
of both the [=[RP]=] and the client platform. It is a key-value
mapping whose keys are string-valued. The _client data values_ 
associated with the latter string-valued keys can be any type that 
has a valid encoding in JSON. Its structure is defined by the
following Web IDL.
```
..?

**Comment by arnar** [comment]
Jeff is correct, "string-valued keys" only implies that the keys must be strings. We can be even clearer by spelling it out:

> The client data represents the contextual bindings of both the Relying Party and the client platform. It is a key-value mapping. Its keys must be strings, but values can be any type that has a valid encoding in JSON. Its structure is defined by the following Web IDL.

**Comment by emlun** [comment]
Oh, I see. I seems like I read my quoted passage as "with strings as keys and values" - I think "string-valued keys" was the culprit. Now that you both point it out it's obvious that the current wording is indeed correct.

A minor clarification like what @equalsJeffH suggests would probably be good, though, but I think it would be enough to change "with string-valued keys" to "whose keys are strings":

```
The client data represents the contextual bindings of both the Relying Party and the client platform. It is a key-value mapping whose keys are strings. Values can be any type that has a valid encoding in JSON. Its structure is defined by the following Web IDL.
```

**Comment by equalsJeffH** [comment]
either @arnar's re-wording or @emlun's works for me.
