### ISSUE TITLE
Client-generated challenges

### ISSUE THREAD

**Issue by davedoesdev** [w3c/webauthn#902]
I have a question about https://www.w3.org/TR/webauthn/#cryptographic-challenges

> Therefore, both challenge's and challenge's value MUST be randomly generated by Relying Parties in an environment they trust (e.g., on the server-side)

I'd like to ask what the reason for this is please?

I'm interested in using WebAuthn to sign JWTs that are generated by script in the page (according to user input). This would be done by an administrative user, to generate tokens which can be presented to the server by other users to get access to limited server functionality.

Is there something in the spec, or the implementations of it, which precludes this use case?

**Comment by emlun** [comment]
I don't think I fully understand your use case, but the general idea is that whatever runs on the client side is controlled by the user, and any security checks in that code can therefore be bypassed.

It doesn't quite sound like that's what you're describing, though. Did I get this right?

1. Alice logs in and proves she's an admin (e.g. by signing a challenge generated on the server, which is then verified on the server).
2. Alice uses client side script to generate a JWT.
3. Client side script uses Alice's public key credential to sign the JWT.
4. JWT with Alice's admin signature is sent to ordinary user Bob.
5. Bob sends signed JWT to server, and receives a perk.

If that's what you're describing, I _think_ that sounds reasonable enough. In this case you have the additional assumption that Alice is not evil (because she's an admin, and her signatures prove that)

**Comment by emlun** [comment]
Sorry, misclick...

**Comment by arnar** [comment]
1. Agree with Emil that it doesn't require the challenge generation to happen on the server. In the language of the spec, "server" is just an example of "an environment they trust". Obviously the RP needs to trust the browser and its own origin context as well, so it can certainly generate a challenge there.

2. However, you can't use WebAuthn to sign arbitrary data. I.e. when you say you want to use it to sign a JWT, I'm not sure it does what you want. You can use or include a JWT in the challenge, but that's not the exact byte buffer that gets signed, it's merely included in client data, which is hashed and that hash is part of what the authenticator actually signs.

You *can* extract your trust guarantees from that, as long as you have the public key on the verifier, but you'll need more than just the JWT - you'll need both the clientData and authenticatorData to verify that the challenge actually matched the JWT. Of course you can roll these into some base64 string, and define it as a custom signature algorithm that you use in your JWTs, but that sounds cumbersome.

**Comment by davedoesdev** [comment]
@emlun yes that's the use case, you described it much better than I did - apologies for that.

@arnar I didn't fully grok what gets signed. As you say, that means the signature won't pass standard JWT verification and I don't want to invent a new one.

Thanks to you both for clarifying things, appreciate it.

**Comment by davedoesdev** [comment]
For the record, I implemented this in [authorize-jwt](https://github.com/davedoesdev/authorize-jwt).

I leaves the (unsigned in this case) JWT verification unchanged and does the WebAuthn verification (signed, of course) as a separate step.
