### ISSUE TITLE
Allow clients to stop the `get` flow when certain conditions are met

### ISSUE THREAD

**Issue by agl** [w3c/webauthn#905]
Christiaan requests the following:

If an RP sends down a list of credentialIds to the platform, and:

1. The RP specifically asked only for built-in credentials (we're still debating how an RP would do this), and none matches any built-in credential, _or_
1. The user explicitly taps the &ldquo;wrong&rdquo; external authenticator which doesn't house any of the credential IDs that were sent down by the RP, _or_
1. The user explicitly cancels out of the flow that tells them to insert an external authenticator since the credential IDs couldn't be found on built-in authenticators

Then the client should render a dialog that says &ldquo;no credential found&rdquo; and, upon the user dismissing the dialog box, the RP should immediately be notified that no matching credentialIds could be found.

**Comment by agl** [comment]
emlun is knee-deep in this part of the spec in #900 so I'll try building upon that.

**Comment by emlun** [comment]
(2) is what's discussed in #863 , right?

**Comment by emlun** [comment]
As noted in https://github.com/w3c/webauthn/pull/906#pullrequestreview-119810884, I have some reservations regarding the specific implementations of (1) and (3). We need to be very careful so we don't accidentally make them open up leaks of identifying information (#184, #204).

**Comment by nadalin** [comment]
@agl Will discuss @ FIDO Plenary

**Comment by equalsJeffH** [comment]
@agl wrote:
> The RP specifically asked only for built-in credentials (we're still debating how an RP would do this) ....

by "built-in credentials" you mean "[client-side resident private key](https://w3c.github.io/webauthn/#client-side-resident-credential-private-key)" (which ought to define a "client-side resident credential" but does not as yet), yes?

Perhaps that ought to be a specific issue, e.g.: "allow RPs to specifically ask for only client-side resident credentials" -- and the

**Comment by equalsJeffH** [comment]
ah, hm, we seem to have some terminology vagueness here.

[platform credential](https://w3c.github.io/webauthn/#platform-credential) is defined as  being a "A public key credential bound to a platform authenticator".  per issue #462 it seems that "bound" is being used equivalently to "managed by". I argue that the latter term is more descriptive of the relationship, because, apparently, a given platform authenticator mey manage its credentials as [client-side](https://w3c.github.io/webauthn/#client-side)-resident [public key credential sources](https://w3c.github.io/webauthn/#public-key-credential-source), and another platform authenticator may manage its creds as server-side-resident [public key credential sources](https://w3c.github.io/webauthn/#client-side).

I've updated issue #358 to suggest replacing [Client-side-resident Credential Private Key](https://w3c.github.io/webauthn/#client-side-resident-credential-private-key) with a "Client-side-resident [Credential Public Key Source](https://w3c.github.io/webauthn/#public-key-credential-source)" term with "resident credential" as the abbreviated form.

we ought to define "client-side-resident" and "server-side-resident", see issue #462

**Comment by nadalin** [comment]
@akshayku Please review

**Comment by equalsJeffH** [comment]
parts 1 & 3 of this were closed by pr #906 
part 2 is alegedly addressed by #863

**Comment by akshayku** [comment]
Closing as per 18-Jul discussion.
