### ISSUE TITLE
Define meaning of "Scope"

### ISSUE THREAD

**Issue by apryamostanov** [w3c/webauthn#964]
Hello Authors,

In the specification, I could not find the definition of "Scoped" and "Scope" when applied to Authentication credentials.
Can you please explain what means "Scoped" Authentication credentials, and possibly consider adding this definition in the specification?

Thank you.

**Comment by equalsJeffH** [comment]
good question, hope this helps: 

scope (noun): extent or range of view, outlook, application, operation, effectiveness, etc.  See also: https://en.wikipedia.org/wiki/Scope_(computer_science)

From https://w3c.github.io/webauthn/#relying-party-identifier: 
----
Note: A Public key credential's scope is for a Relying Party's [origin](https://w3c.github.io/html/browsers.html#concept-cross-origin), with the following _restrictions_ and _relaxations_:

- The scheme is always https (i.e., a _restriction_), and,
- the host may be equal to the Relying Party's origin's [effective domain](https://html.spec.whatwg.org/multipage/origin.html#concept-origin-effective-domain), or it may be [equal to a registrable domain suffix](https://html.spec.whatwg.org/multipage/origin.html#is-a-registrable-domain-suffix-of-or-is-equal-to) of the Relying Party's origin's effective domain (i.e., an available _relaxation_), and,
- all (TCP) ports on that host (i.e., a _relaxation_).

This is done in order to match the behavior of pervasively deployed ambient credentials (e.g., cookies, [RFC6265]). Please note that this is a greater relaxation of "same-origin" restrictions than what document.domain's setter provides.
----

I added "scope" to our terms to define list here: https://github.com/w3c/webauthn/issues/462#issuecomment-399606355

**Comment by apryamostanov** [comment]
Hello, Jeff,

Thank you for feedback. Based on that I understand that normally Scope is limiting usage of credentials to Relying Party Origin (with certain restrictions and relaxations). Yes, it will be great to have it in the Terminology section.
